### ISSUE TITLE
Travis not triggered

### ISSUE THREAD

**Issue by dellaert** [borglab/gtsam#100]
## Description

Travis request is not handled correctly in release branch.
Travis says: Not found: borglab/gtsam/.travis.yml@942a4d852bc74f2d

## Steps to reproduce

1. push release/3.2.3 (where I added travis.yml and travis.sh)

## Expected behavior

Travis does CI

## Environment

Pushed from Mac, but irrelevant?

**Comment by dellaert** [comment]
@jlblancoc any idea?

**Comment by jlblancoc** [comment]
The option "build pushed branches" was disabled, and it allowed me to enable it so... in theory, the next commit should trigger a build!

**Comment by dellaert** [comment]
Hmmmm, no :-(

**Comment by varunagrawal** [comment]
Perhaps try adding the safelist directive to `.travis.yml`?

https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches

**Comment by dellaert** [comment]
Turns out I missed the dot in the travis files....
