### ISSUE TITLE
jetson nx internal compiler error

### ISSUE THREAD

**Issue by jimmy9925** [borglab/gtsam#1046]
hello everyone
I tried to build gtasm ,but I got some error 
ubuntu 18.04 and I tried gcc 5 ,gcc 6 ,gcc 7 ,gcc 8 ,gcc9

c++: internal compiler error: Segmentation fault signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
gtsam/CMakeFiles/gtsam.dir/build.make:1574: recipe for target 'gtsam/CMakeFiles/gtsam.dir/linear/GaussianBayesNet.cpp.o' failed
make[3]: *** [gtsam/CMakeFiles/gtsam.dir/linear/GaussianBayesNet.cpp.o] Error 4
CMakeFiles/Makefile2:1596: recipe for target 'gtsam/CMakeFiles/gtsam.dir/all' failed
make[2]: *** [gtsam/CMakeFiles/gtsam.dir/all] Error 2
CMakeFiles/Makefile2:640: recipe for target 'CMakeFiles/check.dir/rule' failed
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
Makefile:223: recipe for target 'check' failed
make: *** [check] Error 2
Have someone can help me?, thank you

**Comment by ProfFan** [comment]
Most likely you don't have enough memory. Please cross compile or find the reason why you have such low memory (GUI, etc.)
