### ISSUE TITLE
Clang `-march=native` fails on Apple M1  

### ISSUE THREAD

**Issue by Shikhargupta** [borglab/gtsam#1057]
When I try to build from source on my M1 Mac, I get this error:
`clang: error: the clang compiler does not support '-march=native'`

Is there a quick workaround for this?

Thanks!

**Comment by dellaert** [comment]
Turn off the option ;-) But we should change cmake to detect the platform do it automatically, so will re-open issue.

**Comment by Shikhargupta** [comment]
Yeah, changing it automatically would be great. I found the quick fix myself that's why closed the issue. 
You can use it to track the problem.

**Comment by dellaert** [comment]
PS @Shikhargupta if you know how to fix the cmake thing, please feel free to PR :-)
