### ISSUE TITLE
Why the H1 is filled with the bottom row of rotation matrix for RelativeElevationFactor?

### ISSUE THREAD

**Issue by FishInWave** [borglab/gtsam#1061]
https://github.com/borglab/gtsam/blob/3d86bc729463bf17369137d8451092413a6b1d17/gtsam_unstable/slam/RelativeElevationFactor.cpp#L25

As h(pose, pt) = h.z() - pt.z() , the H1 should be (0,0,0,0,0,1) and H2 be (0,0,0,0,0,-1).
Is there anything wrong?

**Comment by dellaert** [comment]
Derivative in GTSAM can be unintuitive. Can you share the output of a unit test that fails?

**Comment by varunagrawal** [comment]
Closing due to lack of response. We recommend continuing this on the Google group.
