### ISSUE TITLE
typo error in doc/math.pdf

### ISSUE THREAD

**Issue by huanglilong** [borglab/gtsam#1063]
typo error in 5.3
![Image from iOS (2)](https://user-images.githubusercontent.com/7278867/150990307-0b841982-d05a-4f6d-ae73-2dba7b8d20a0.jpg)

**Comment by dellaert** [comment]
OK, wait, the last line *is* correct, it's the second to last line that's wrong. Got it :-) Thanks!

**Comment by dellaert** [comment]
Closed with #1064
