### ISSUE TITLE
Request python 3.10 wheel for GTSAM pypi

### ISSUE THREAD

**Issue by AchmadFathoni** [borglab/gtsam#1122]
The latest [GTSAM PyPI](https://pypi.org/project/gtsam/#files) wheel package is still for python 3.9 (cp39).

**Comment by AchmadFathoni** [comment]
Arch linux, I'm the maintainer of AUR for python-gtsam

**Comment by ProfFan** [comment]
I can add a build target for 3.10 after 4.2a6 is done

**Comment by shteren1** [comment]
@ProfFan any ETA for 4.2a6?

**Comment by varunagrawal** [comment]
GTSAM 4.2.0 wheels for Python 3.8-3.11 are now [available on PyPI](https://pypi.org/project/gtsam/#files).

Closing this as resolved!
