### ISSUE TITLE
RangeISAMExample Error 'gtsam::ValuesKeyDoesNotExist'

### ISSUE THREAD

**Issue by KierenSama2** [borglab/gtsam#1130]
I am fairly new to GTSAM and am trying to run the RangeISAMExample.cpp. When I run the code as is I get the following error:
`[100%] Built target RangeISAMExample_plaza2
terminate called after throwing an instance of 'gtsam::ValuesKeyDoesNotExist'
  what():  Attempting to at the key "L2", which does not exist in the Values.
Aborted (core dumped)
make[3]: *** [examples/CMakeFiles/RangeISAMExample_plaza2.run.dir/build.make:57: examples/CMakeFiles/RangeISAMExample_plaza2.run] Error 134
make[2]: *** [CMakeFiles/Makefile2:21082: examples/CMakeFiles/RangeISAMExample_plaza2.run.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:21089: examples/CMakeFiles/RangeISAMExample_plaza2.run.dir/rule] Error 2
make: *** [Makefile:8556: RangeISAMExample_plaza2.run] Error 2`

**Comment by dellaert** [comment]
You are right. The initialization was totally wrong. Probably was originally the smaller plaza1 dataset.
I cleaned up this old example up and fixed this in #1131
I did *not* check whether the result makes sense. Maybe you can visualize from that branch and paste an image here?

**Comment by KierenSama2** [comment]
@dellaert thank you for the quick reply. After pulling a different error occurred. 

`[100%] Built target RangeISAMExample_plaza2
terminate called after throwing an instance of 'gtsam::IndeterminantLinearSystemException'
  what():  
Indeterminant linear system detected while working near variable
3086 (Symbol: 3086).

Thrown when a linear system is ill-posed.  The most common cause for this
error is having underconstrained variables.  Mathematically, the system is
underdetermined.  See the GTSAM Doxygen documentation at
http://borg.cc.gatech.edu/ on gtsam::IndeterminantLinearSystemException for
more information.
Aborted (core dumped)
`

**Comment by dellaert** [comment]
Hmm. I don’t have this. Try with a different random seed for `rng` ?

**Comment by KierenSama2** [comment]
Error still occurs with other random seeds. The same instance is thrown but is detected near other variables
`Indeterminant linear system detected while working near variable
5476377146882523139 (Symbol: L3).
`
Will provide an update if solved.

**Comment by KierenSama2** [comment]
Still not solved, do you think it has something to do with the config @dellaert ?
`- ================  Configuration Options  ======================
--  CMAKE_CXX_COMPILER_ID type                       : GNU
--  CMAKE_CXX_COMPILER_VERSION                       : 9.3.0
--  CMake version                                    : 3.16.3
--  CMake generator                                  : Unix Makefiles
--  CMake build tool                                 : /usr/bin/make
-- Build flags                                               
--  Build Tests                                      : Enabled
--  Build examples with 'make all'                   : Enabled
--  Build timing scripts with 'make all'             : Disabled
--  Build Docs                                       : Enabled
--  Build shared GTSAM libraries                     : Enabled
--  Put build type in library name                   : Enabled
--  Build libgtsam_unstable                          : Enabled
--  Build GTSAM unstable Python                      : Enabled
--  Build MATLAB Toolbox for unstable                : Disabled
--  Build for native architecture                    : Enabled
--  Build type                                       : Release
--  C compilation flags                              :  -O3 -DNDEBUG
--  C++ compilation flags                            :  -O3 -DNDEBUG
--  GTSAM_COMPILE_FEATURES_PUBLIC                    : cxx_std_11
--  GTSAM_COMPILE_OPTIONS_PUBLIC                     : -march=native
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC                 : 
--  GTSAM_COMPILE_OPTIONS_PUBLIC_DEBUG               : 
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC_DEBUG           : 
--  GTSAM_COMPILE_OPTIONS_PUBLIC_RELEASE             : 
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC_RELEASE         : 
--  GTSAM_COMPILE_OPTIONS_PUBLIC_TIMING              : 
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC_TIMING          : 
--  GTSAM_COMPILE_OPTIONS_PUBLIC_PROFILING           : 
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC_PROFILING       : 
--  GTSAM_COMPILE_OPTIONS_PUBLIC_RELWITHDEBINFO      : 
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC_RELWITHDEBINFO  : 
--  GTSAM_COMPILE_OPTIONS_PUBLIC_MINSIZEREL          : 
--  GTSAM_COMPILE_DEFINITIONS_PUBLIC_MINSIZEREL      : 
--  Use System Eigen                                 : OFF (Using version: 3.3.7)
--  Use Intel TBB                                    : Yes (Version: 2020.1)
--  Eigen will use MKL                               : MKL not found
--  Eigen will use MKL and OpenMP                    : OpenMP found but GTSAM_WITH_EIGEN_MKL is disabled
--  Default allocator                                : TBB
--  Cheirality exceptions enabled                    : YES
--  Build with ccache                                : Yes
-- Packaging flags
--  CPack Source Generator                           : TGZ
--  CPack Generator                                  : TGZ
-- GTSAM flags                                               
--  Quaternions as default Rot3                      : Disabled
--  Runtime consistency checking                     : Disabled
--  Rot3 retract is full ExpMap                      : Enabled
--  Pose3 retract is full ExpMap                     : Enabled
--  Allow features deprecated in GTSAM 4.1           : Enabled
--  Metis-based Nested Dissection                    : Enabled
--  Use tangent-space preintegration                 : Enabled
-- MATLAB toolbox flags
--  Install MATLAB toolbox                           : Disabled
-- Python toolbox flags                                      
--  Build Python module with pybind                  : Disabled
-- ===============================================================
-- Configuring done
-- Generating done
`

**Comment by dellaert** [comment]
Turns out it was a parsing error in c++, see #1131 . Waiting on @jerredchen to approve and merge that PR, which now also has a notebook example with graphics. See PR for more details.
