### ISSUE TITLE
Incorrect Jacobian specified in Python Code for Custom Factor

### ISSUE THREAD

**Issue by NickPerezCarletonUniversity** [borglab/gtsam#1134]
It looks like [the C++ code](https://github.com/borglab/gtsam/blob/develop/examples/LocalizationExample.cpp#L96) and [python code](https://github.com/borglab/gtsam/blob/develop/python/gtsam/examples/CustomFactorExample.py#L45) have different Jacobians defined for GPS measurements.

**Comment by dellaert** [comment]
I fixed the docs at least in PR #1139 and copied to 
https://gtsam.org/tutorials/intro.html#magicparlabel-65484

@ProfFan could you fix the python code please?

**Comment by ProfFan** [comment]
Wait no. The "GPS" in the Python is for a 1-D car!

**Comment by ProfFan** [comment]
@NickPerezCarletonUniversity
