### ISSUE TITLE
Issue building wrap-export branch

### ISSUE THREAD

**Issue by husseinalijaafar** [borglab/gtsam#1141]
Hi,

I have been having difficuilty building gtsam (need it for gpmp2). 

I do
```
git clone https://github.com/borglab/gtsam.git
cd gtsam
git checkout wrap-export
mkdir build && cd build
cmake ..
make check  # optional, run unit tests
sudo make install
```

However, once I do `make check`, it floods my terminal with warnings relating to Eigen etc.
Thats not the problem though. It fails at 37%:

Here is the end of the error message.

```
                                           ^~~~~~~~~~~~~~~~~~
make[3]: *** [gtsam/base/tests/CMakeFiles/testSerializationBase.dir/build.make:63: gtsam/base/tests/CMakeFiles/testSerializationBase.dir/testSerializationBase.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:3408: gtsam/base/tests/CMakeFiles/testSerializationBase.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2445: CMakeFiles/check.dir/rule] Error 2
make: *** [Makefile:236: check] Error 2
```

I can provide the entire error message, but it is really long (several thousand lines).

Thanks in advance

**Comment by varunagrawal** [comment]
Why are you building `wrap-export`? That may be an old branch that is very outdated and doesn't work.
