### ISSUE TITLE
How to use Equirectangular/spherical image for Projection Factor

### ISSUE THREAD

**Issue by KibaekJeong** [borglab/gtsam#1160]
I am trying to run Bundle adjustment with GTSAM using equirectangular image. 
I have tried to use GenericProjectionFactor with setting Cal3_S2, setting FOV to 360, and image size only. 
But seem to obtain high reprojection error at final result. 

Is there any other way to do this? or is this the only way I can do this?

**Comment by ProfFan** [comment]
Hi, please use the mailing list (Google Group) for questions, thanks!
