### ISSUE TITLE
Missing "this->" in evaluateError() in BearingRangeFactor.h

### ISSUE THREAD

**Issue by daanwildiers** [borglab/gtsam#1162]
When using the  
`Vector evaluateError(const A1& a1, const A2& a2, boost::optional<Matrix&> H1 = boost::none, boost::optional<Matrix&> H2 = boost::none) const`
function in BearingRangeFactor.h, it is not possible to compile using _catkin build_ in a catkin workspace.
On line 82 in `const Vector error = unwhitenedError({{keys[0], genericValue(a1)}, {keys[1], genericValue(a2)}}, Hs);`
there is a missing `this->` before `unwhitenedError(`. When prepending `this->` the code compiles perfectly.
So it should be nice if `this->` is added before `unwhitenedError(` on Github.

**Comment by dellaert** [comment]
I assume you have a fork, can you PR this change to develop?
