### ISSUE TITLE
typo issue in comments

### ISSUE THREAD

**Issue by huanglilong** [borglab/gtsam#1201]
https://github.com/borglab/gtsam/blob/da00870ee1a7ce8fe746008abde62ad012dd177b/gtsam/geometry/Rot3.cpp#L295
https://github.com/borglab/gtsam/blob/da00870ee1a7ce8fe746008abde62ad012dd177b/gtsam/geometry/Rot3.cpp#L296
should be
// c10 = a10 * cy + a11 * sx * sy + a12 * cx * sy
// c11 = a11 * cx - a12 * sx
![image](https://user-images.githubusercontent.com/7278867/169197327-43824013-ffe0-46cb-bad0-bda067a5cb1d.png)

**Comment by huanglilong** [comment]
@Eskilade typo issue in comments.

**Comment by Eskilade** [comment]
Indeed, thanks !

**Comment by varunagrawal** [comment]
@huanglilong can you please make a PR? I'll happily review and help merge it in. Bonus: you get to call yourself a GTSAM contributor.
