### ISSUE TITLE
documentation for python users for landmark base SLAM

### ISSUE THREAD

**Issue by orangeRobot990** [borglab/gtsam#1208]
## Feature

Hi, I would like to use this library for in python but it seems that theres no documentation available on how to do so.

## Motivation

I would like to reproduce a paper using GTSAM as a backend and ai models predictions as landmarks. If anyone has done such or have any tips, please let me know.

**Comment by varunagrawal** [comment]
The Python API strongly mirrors the C++ API so you should be able to translate it relatively easily. I recommend looking at some of the Python examples and familiarizing yourself with the 2D SLAM examples.

**Comment by varunagrawal** [comment]
If you are still having issues, please ask on the Google Group :)
