### ISSUE TITLE
How to cross-compile gtsam to arm linux?

### ISSUE THREAD

**Issue by YGD159** [borglab/gtsam#1210]
How to cross-compile gtsam to arm linux ?
Any suggestions are greatly appreciated.

**Comment by varunagrawal** [comment]
I believe this would involve some significant CMake updates for the relative hardware. We are able to compile GTSAM for M1 macbooks which means that we do support the ARM architecture. For linux specifically, you may have to do some research on your own.

If you still have questions, please ask on the Google Group for faster responses. 🙂

**Comment by ProfFan** [comment]
GTSAM works no problem on ARM (Tested last year on Jetson Nano). No special instruction is necessary.
