### ISSUE TITLE
double free or corruption (out) when using smart factor

### ISSUE THREAD

**Issue by tccoin** [borglab/gtsam#1211]
## Description

I am currently using `SmartProjectionPoseFactor` with `CombinedImuFactor` in my project and sometimes the program will fail with the error `double free or corruption (out)`. By using address sanitizer, I managed to find the code which triggers the error.

![image](https://user-images.githubusercontent.com/4727900/171556159-fb5b0b40-4434-45b7-987e-39aff9482091.png)
![image](https://user-images.githubusercontent.com/4727900/171556166-64bcda1a-76f9-4330-94d1-9d3fd783a110.png)

## Steps to reproduce

My experience is, using `SmartProjectionPoseFactor` or  `CombinedImuFactor` alone won't trigger this error, but using them both will. I am not sure how this is related to the memory error but in case I just provide what I found.

## Expected behavior

The systems should not fail.

## Environment

Ubuntu 20.04 in docker.

**Comment by ProfFan** [comment]
My gut feeling is that this is b/c a missing lock and the two threads are having a race condition. Don't have the bandwidth to debug this, but I feel that if you add locking to the two mutable `cameraPosesTriangulation_` it should not crash

**Comment by tccoin** [comment]
Thank you! I will have a try.
