### ISSUE TITLE
Bundle Adjustment Landmark Visibility

### ISSUE THREAD

**Issue by goktugyildirim** [borglab/gtsam#1212]
Hello, I'm a dummy for graph optimization and my aim is to solve the bundle adjustment problem incrementally. My question is about points visibility. All landmarks should be visible from all camera poses? When I try to add some landmark that is not visible all views, optimization, or update function is stuck. How can I solve this problem? Can you help me?

**Comment by dellaert** [comment]
As indicated, this type of question is more for the GTSAM user group. But, no, landmarks do not have to be visible from all poses. Just from enough such that dim(measurements)>=dim(point), OR you have a prior on the point.
