### ISSUE TITLE
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)

### ISSUE THREAD

**Issue by leegence** [borglab/gtsam#1222]
When testing the python code version of GTSAM, the code outputs error message saying "RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)" after running the follow

params = gtsam.LevenbergMarquardtParams()
optimizer = gtsam.LevenbergMarquardtOptimizer(graph, initial_estimate, params)

Could anyone tell the reason?

**Comment by ProfFan** [comment]
Hmm, are you using the CustomFactor? Are you compiling the Python wrapper yourself?

**Comment by leegence** [comment]
Yes, I am using the CustomFactor with Python wrapper.

**Comment by ProfFan** [comment]
You are probably using it wrong. Note you should return an errorVector (NP array), not a number, even if it's 1D

**Comment by ProfFan** [comment]
@leegence Did this solve your problem?
