### ISSUE TITLE
Expression support in MATLAB/Python

### ISSUE THREAD

**Issue by varunagrawal** [borglab/gtsam#125]
## Feature

Currently, the wrappers don't have support for Expressions. It would be great to have this supported so that one can work with these features at a higher level.

## Motivation

Expressions are pretty awesome?

## Alternatives

No alternative exists.

**Comment by ProfFan** [comment]
Could be a little bit difficult with the current python I/F. I think to implement this we need to associate `Expression` objects in C++ and Python. Also if we want new non-arithmetic ops we need to either implement in C++ or Cythonize a function and pass ptr to C++.

**Comment by varunagrawal** [comment]
This is not really a must-have feature so I am closing this.
