### ISSUE TITLE
Attribute error in ISAM2 Python examples (Pose2,Pose3 and Visual)

### ISSUE THREAD

**Issue by dars-99** [borglab/gtsam#1264]
## Description

While running the examples of iSAM2 related to Pose2, Pose3 and Visual, there appears an attribute error in **iSAM2Params()** . It happens at the line
```
parameters.relinearizeSkip = 1
```
Changing the above line to 
```
parameters.setRelinearizeSkip(1)
```
fixes the issue.

**Comment by varunagrawal** [comment]
Are you using the pip version or the building the python wrapper from scratch? I just ran `Pose2ISAM2Example.py` and it works well. I thought maybe it was an issue with the .i file but that seems okay too. :confused:

**Comment by dars-99** [comment]
I am just cloning the whole repository using git and building the package and directly running it

**Comment by dars-99** [comment]
I have installed gtsam using pip3 and the examples are working fine now. But when I run my code  I get an attribute error. 

Currently gtsam is located in the following path **~/.local/lib/python3.6/site-packages/gtsam**.  

I am not sure if this is the right installation path.

**Comment by dars-99** [comment]
I think I found out the problem. The installation through pip3 works perfectly because the examples has the change I mentioned above. But the examples on the git doesn't have the change which throws an attribute error.

**Comment by varunagrawal** [comment]
I tried running the examples on GitHub directly and they work well for me. Can you please post how you are running your code?

**Comment by dars-99** [comment]
Well I tried to remove my installation and rebuilt the package from scratch. The package is built successfully. But I am getting an error saying that the **gtsam** module is not found. Not sure what is the issue. But the install process completed without any error.

**Comment by dars-99** [comment]
I tried to rebuild the package from source by completely removing the previous installation. I was able to build the wrappers successfully. But for some reason it is throwing an error saying **gtsam** module not found. I am not sure why this is happening. But the installation completed successfully.

**Comment by varunagrawal** [comment]
Did you run `make python-install`?

**Comment by dars-99** [comment]
Yep that fixed my issue and also the examples are running without any error. I'm not sure why it is working now. But thanks for your help!

**Comment by varunagrawal** [comment]
Ah that's because that command installs the built package so that Python can use it. I am guessing Python was using the pip installed version previously.

Glad we figured this out.
