### ISSUE TITLE
Custom binary factor python

### ISSUE THREAD

**Issue by dars-99** [borglab/gtsam#1272]
Hello,

I'm trying to create a custom factor between two different kind of variables in python. The variables are camera pose and landmark pose. I am estimating the relative pose between the camera and landmark using a single frame since I know the object's dimension in real world. I am able to get the relative pose but I am unable to add this to the graph because I don't know how to create a custom factor between two different variables in python. The python examples only give an overview for unary factors. It would be nice to know if there is already a function for the above mentioned problem or is there any examples of custom factors for two different kind of variables in python.

Thanks!

**Comment by ProfFan** [comment]
I think https://github.com/borglab/gtsam/blob/d3544d4c06c6ebe1af7f4d810c932a7785348d10/python/gtsam/examples/CustomFactorExample.py#L50 is what you need? It takes 2 variables as input.

**Comment by dars-99** [comment]
So in this examples the two variables belong to same type(X). I want to pass two different type of variables(X and L). Is it possible?

**Comment by ProfFan** [comment]
It's the same.

**Comment by dars-99** [comment]
I will look into this. Thanks for your input
