### ISSUE TITLE
wrapper does support return by reference

### ISSUE THREAD

**Issue by MandyXie** [borglab/gtsam#129]
## Description

I am trying to wrap my own project which uses GTSAM. I have some functions that return by reference. It does not work if I declare functions in the header file for the wrapper with ampersand symbol, however, it works if I take the ampersand symbol away. 

## Steps to reproduce

1. declare gtsam::Matrix6& func() in project_name.h, does not work
2. declare gtsam::Matrix6 func() in project_name.h, works

**Comment by dellaert** [comment]
Yeah, that’s expected behavior. What will really happen is that a copy will be created for Matlab/python. The wrap program parses something that’s not exactly c++. Some comments can be found at the top of gtsam.h, which should really go in a wrap readme file.
