### ISSUE TITLE
Warp EssentialMatrixConstraint into Matlab toolbox

### ISSUE THREAD

**Issue by fwf-lernen** [borglab/gtsam#1291]
I want to use EssentialMatrixConstraint in my work(based on matlab). I find that EssentialMatrix and EssentialMatrixFactor have been wrapped. However, after searching hard, I didn't find any m-files or code samples related to EssentialMatrixConstraint in the toolbox. Is this feature wrapped and if not how can I add it to matlab? (I found in an earlier [issue](https://github.com/borglab/gtsam/pull/962) about wrapping this feature into python.)

**Comment by dellaert** [comment]
The .i files are shared between python and MATLAB wrappers, so if it works in python it *should* work in MATLAB. Closing but feel free to re-open if you can't make it work.
