### ISSUE TITLE
error: ‘identity’ is not a member of ‘gtsam::Pose3’  

### ISSUE THREAD

**Issue by wolfcanli** [borglab/gtsam#1298]
## Description

Hi, there. When I tried to build some [code,](https://github.com/MIT-SPARK/Kimera-VIO-ROS), I got this error :error: ‘identity’ is not a member of ‘gtsam::Pose3’
## Steps to reproduce

1. [MIT-SPARK/Kimera-VIO-ROS](https://github.com/MIT-SPARK/Kimera-VIO-ROS)
2.

`In file included from /home/timsir/ws/kimera_vio_ros/src/Kimera-VIO/include/kimera-vio/common/VioNavState.h:27:0,
                 from /home/timsir/ws/kimera_vio_ros/src/Kimera-VIO/include/kimera-vio/dataprovider/DataProviderInterface-definitions.h:25,
                 from /home/timsir/ws/kimera_vio_ros/src/Kimera-VIO/src/dataprovider/DataProviderInterface-definitions.cpp:14:
/home/timsir/ws/kimera_vio_ros/src/Kimera-VIO/include/kimera-vio/common/vio_types.h:70:13: warning: ‘void VIO::getValidKeypointsFromStatusKeypointsCV(const StatusKeypointsCV&, VIO::KeypointsCV*)’ defined but not used [-Wunused-function]
 static void getValidKeypointsFromStatusKeypointsCV(
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[proxychains] DLL init: proxychains-ng 4.16-git-9-g060801d
[proxychains] DLL init: proxychains-ng 4.16-git-9-g060801d
[proxychains] DLL init: proxychains-ng 4.16-git-9-g060801d
[proxychains] DLL init: proxychains-ng 4.16-git-9-g060801d
[proxychains] DLL init: proxychains-ng 4.16-git-9-g060801d
In file included from /home/timsir/ws/kimera_vio_ros/src/Kimera-VIO/include/kimera-vio/frontend/StereoFrame-definitions.h:20:0,
                 from /home/timsir/ws/kimera_vio_ros/src/Kimera-VIO/include/kimera-vio/frontend/StereoMatchingParams.h:17,
                 from /home/timsir/ws/kimera_vio_ros/src/Kimera-VIO/include/kimera-vio/frontend/StereoCamera.h:28,
                 from /home/timsir/ws/kimera_vio_ros/src/Kimera-VIO/src/frontend/StereoCamera.cpp:15:
/home/timsir/ws/kimera_vio_ros/src/Kimera-VIO/include/kimera-vio/frontend/Tracker-definitions.h: In constructor ‘VIO::TrackerStatusSummary::TrackerStatusSummary()’:
/home/timsir/ws/kimera_vio_ros/src/Kimera-VIO/include/kimera-vio/frontend/Tracker-definitions.h:119:33: error: ‘identity’ is not a member of ‘gtsam::Pose3’
     lkf_T_k_mono_(gtsam::Pose3::identity()),
                                 ^~~~~~~~
/home/timsir/ws/kimera_vio_ros/src/Kimera-VIO/include/kimera-vio/frontend/Tracker-definitions.h:120:35: error: ‘identity’ is not a member of ‘gtsam::Pose3’
     lkf_T_k_stereo_(gtsam::Pose3::identity()),

`

## Environment
UBUNTU18.04 
C++
Gtsam 4.2.0

## Additional information
I tried to modify  the file "/gtsam/gtsam/config.h.in", enabled this command " #cmakedefine GTSAM_ALLOW_DEPRECATED_SINCE_V42 --->cmakedefine GTSAM_ALLOW_DEPRECATED_SINCE_V42". But I got more errors, like follows:
`/home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/Matrix.cpp:649:73:   required from here
/usr/local/include/eigen3/Eigen/src/Core/DenseBase.h:78:17: error: no members matching ‘Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0>, 0>}::rows’ in ‘Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka class Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0>, 0>}’
     using Base::rows;
                 ^~~~
/usr/local/include/eigen3/Eigen/src/Core/DenseBase.h:79:17: error: no members matching ‘Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0>, 0>}::cols’ in ‘Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka class Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0>, 0>}’
     using Base::cols;
                 ^~~~
/usr/local/include/eigen3/Eigen/src/Core/DenseBase.h:80:17: error: no members matching ‘Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0>, 0>}::size’ in ‘Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka class Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0>, 0>}’
     using Base::size;
                 ^~~~
/usr/local/include/eigen3/Eigen/src/Core/DenseBase.h:81:17: error: no members matching ‘Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0>, 0>}::rowIndexByOuterInner’ in ‘Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka class Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0>, 0>}’
     using Base::rowIndexByOuterInner;
                 ^~~~~~~~~~~~~~~~~~~~
/usr/local/include/eigen3/Eigen/src/Core/DenseBase.h:82:17: error: no members matching ‘Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0>, 0>}::colIndexByOuterInner’ in ‘Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka class Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0>, 0>}’
     using Base::colIndexByOuterInner;
                 ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/eigen3/Eigen/Core:435:0,
                 from /usr/local/include/eigen3/Eigen/Dense:1,
                 from /home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/OptionalJacobian.h:22,
                 from /home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/Matrix.h:27,
                 from /home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/Matrix.cpp:19:
/usr/local/include/eigen3/Eigen/src/Core/DenseBase.h:363:45: error: ‘Derived& Eigen::DenseBase<Derived>::setLinSpaced(const Scalar&, const Scalar&) [with Derived = Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0>; Eigen::DenseBase<Derived>::Scalar = double]’ conflicts with a previous declaration
     EIGEN_DEVICE_FUNC Derived& setLinSpaced(Index size, const Scalar& low, const Scalar& high);
                                             ^~~~~
/usr/local/include/eigen3/Eigen/src/Core/DenseBase.h:363:45: note: previous declaration ‘Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0>& Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::setLinSpaced’
In file included from /usr/local/include/eigen3/Eigen/Core:436:0,
                 from /usr/local/include/eigen3/Eigen/Dense:1,
                 from /home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/OptionalJacobian.h:22,
                 from /home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/Matrix.h:27,
                 from /home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/Matrix.cpp:19:
/usr/local/include/eigen3/Eigen/src/Core/MatrixBase.h: In instantiation of ‘class Eigen::MatrixBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >’:
/usr/local/include/eigen3/Eigen/src/Core/Product.h:115:7:   required from ‘class Eigen::internal::dense_product_base<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0, 8>’
/usr/local/include/eigen3/Eigen/src/Core/Product.h:147:7:   required from ‘class Eigen::ProductImpl<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0, Eigen::Dense>’
/usr/local/include/eigen3/Eigen/src/Core/Product.h:71:7:   required from ‘class Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0>’
/usr/local/include/eigen3/Eigen/src/Householder/BlockHouseholder.h:95:66:   required from ‘void Eigen::internal::apply_block_householder_on_the_left(MatrixType&, const VectorsType&, const CoeffsType&, bool) [with MatrixType = Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>; VectorsType = Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>; CoeffsType = Eigen::Block<Eigen::Matrix<double, -1, 1>, -1, 1, false>]’
/usr/local/include/eigen3/Eigen/src/QR/HouseholderQR.h:339:44:   required from ‘static void Eigen::internal::householder_qr_inplace_blocked<MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne>::run(MatrixQR&, HCoeffs&, int, typename MatrixQR::Scalar*) [with MatrixQR = Eigen::Matrix<double, -1, -1>; HCoeffs = Eigen::Matrix<double, -1, 1>; MatrixQRScalar = double; bool InnerStrideIsOne = true; typename MatrixQR::Scalar = double]’
/home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/Matrix.cpp:649:73:   required from here
/usr/local/include/eigen3/Eigen/src/Core/MatrixBase.h:72:17: error: no members matching ‘Eigen::MatrixBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >}::rows’ in ‘Eigen::MatrixBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka class Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >}’
     using Base::rows;
                 ^~~~
/usr/local/include/eigen3/Eigen/src/Core/MatrixBase.h:73:17: error: no members matching ‘Eigen::MatrixBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >}::cols’ in ‘Eigen::MatrixBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka class Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >}’
     using Base::cols;
                 ^~~~
/usr/local/include/eigen3/Eigen/src/Core/MatrixBase.h:74:17: error: no members matching ‘Eigen::MatrixBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >}::size’ in ‘Eigen::MatrixBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >::Base {aka class Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Transpose<const Eigen::Matrix<double, -1, -1, 1> >, 1>, Eigen::Matrix<double, -1, -1>, 0> >}’
     using Base::size;
                 ^~~~
In file included from /usr/local/include/eigen3/Eigen/Core:439:0,
                 from /usr/local/include/eigen3/Eigen/Dense:1,
                 from /home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/OptionalJacobian.h:22,
                 from /home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/Matrix.h:27,
                 from /home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/Matrix.cpp:19:
/usr/local/include/eigen3/Eigen/src/Core/Product.h: In instantiation of ‘struct Eigen::internal::traits<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0> >’:
/usr/local/include/eigen3/Eigen/src/Core/Product.h:115:7:   required from ‘class Eigen::internal::dense_product_base<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0, 8>’
/usr/local/include/eigen3/Eigen/src/Core/Product.h:147:7:   required from ‘class Eigen::ProductImpl<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0, Eigen::Dense>’
/usr/local/include/eigen3/Eigen/src/Core/Product.h:71:7:   required from ‘class Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0>’
/usr/local/include/eigen3/Eigen/src/Householder/BlockHouseholder.h:96:22:   required from ‘void Eigen::internal::apply_block_householder_on_the_left(MatrixType&, const VectorsType&, const CoeffsType&, bool) [with MatrixType = Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>; VectorsType = Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>; CoeffsType = Eigen::Block<Eigen::Matrix<double, -1, 1>, -1, 1, false>]’
/usr/local/include/eigen3/Eigen/src/QR/HouseholderQR.h:339:44:   required from ‘static void Eigen::internal::householder_qr_inplace_blocked<MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne>::run(MatrixQR&, HCoeffs&, int, typename MatrixQR::Scalar*) [with MatrixQR = Eigen::Matrix<double, -1, -1>; HCoeffs = Eigen::Matrix<double, -1, 1>; MatrixQRScalar = double; bool InnerStrideIsOne = true; typename MatrixQR::Scalar = double]’
/home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/Matrix.cpp:649:73:   required from here
/usr/local/include/eigen3/Eigen/src/Core/Product.h:34:79: error: no type named ‘StorageIndex’ in ‘struct Eigen::internal::traits<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5> >’
                                       typename RhsTraits::StorageIndex>::type StorageIndex;
                                                                               ^~~~~~~~~~~~
In file included from /usr/local/include/eigen3/Eigen/Core:434:0,
                 from /usr/local/include/eigen3/Eigen/Dense:1,
                 from /home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/OptionalJacobian.h:22,
                 from /home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/Matrix.h:27,
                 from /home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/Matrix.cpp:19:
/usr/local/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h: In instantiation of ‘class Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0>, 0>’:
/usr/local/include/eigen3/Eigen/src/Core/DenseBase.h:41:34:   required from ‘class Eigen::DenseBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0> >’
/usr/local/include/eigen3/Eigen/src/Core/MatrixBase.h:48:34:   required from ‘class Eigen::MatrixBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0> >’
/usr/local/include/eigen3/Eigen/src/Core/Product.h:115:7:   required from ‘class Eigen::internal::dense_product_base<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0, 8>’
/usr/local/include/eigen3/Eigen/src/Core/Product.h:147:7:   required from ‘class Eigen::ProductImpl<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0, Eigen::Dense>’
/usr/local/include/eigen3/Eigen/src/Core/Product.h:71:7:   required from ‘class Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0>’
/usr/local/include/eigen3/Eigen/src/Householder/BlockHouseholder.h:96:22:   required from ‘void Eigen::internal::apply_block_householder_on_the_left(MatrixType&, const VectorsType&, const CoeffsType&, bool) [with MatrixType = Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>; VectorsType = Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>; CoeffsType = Eigen::Block<Eigen::Matrix<double, -1, 1>, -1, 1, false>]’
/usr/local/include/eigen3/Eigen/src/QR/HouseholderQR.h:339:44:   required from ‘static void Eigen::internal::householder_qr_inplace_blocked<MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne>::run(MatrixQR&, HCoeffs&, int, typename MatrixQR::Scalar*) [with MatrixQR = Eigen::Matrix<double, -1, -1>; HCoeffs = Eigen::Matrix<double, -1, 1>; MatrixQRScalar = double; bool InnerStrideIsOne = true; typename MatrixQR::Scalar = double]’
/home/timsir/ws/kimera_vio_ros/src/gtsam/gtsam/base/Matrix.cpp:649:73:   required from here
/usr/local/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:58:17: error: no members matching ‘Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0>, 0>::Base {aka Eigen::EigenBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0> >}::rows’ in ‘Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0>, 0>::Base {aka struct Eigen::EigenBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0> >}’
     using Base::rows;
                 ^~~~
/usr/local/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:59:17: error: no members matching ‘Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0>, 0>::Base {aka Eigen::EigenBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0> >}::cols’ in ‘Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0>, 0>::Base {aka struct Eigen::EigenBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0> >}’
     using Base::cols;
                 ^~~~
/usr/local/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:60:17: error: no members matching ‘Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0>, 0>::Base {aka Eigen::EigenBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0> >}::size’ in ‘Eigen::DenseCoeffsBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0>, 0>::Base {aka struct Eigen::EigenBase<Eigen::Product<Eigen::TriangularView<const Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>, 5>, Eigen::Matrix<double, -1, -1>, 0> >}’
     using Base::size;
                 ^~~~
`

**Comment by ProfFan** [comment]
It's now `Identity` (note the case)
