### ISSUE TITLE
How to specify gtsam under non-standard path in cmake?

### ISSUE THREAD

**Issue by wugeshenhuaking** [borglab/gtsam#1320]
I installed version 4.0.0 of gtsam in a custom path. I used the following statement to configure this version in cmakelist.txt, but it failed.Cmake always finds the gtsam installed in the /usr/local/path.

`
set(GTSAM_DIR "/home/wyw/3rdparty/gtsam_4.0.0/lib/cmake/GTSAM")
find_package(GTSAM REQUIRED)
`

**Comment by varunagrawal** [comment]
@wugeshenhuaking please ask this question on the Google Group. Since this is not a code issue, I am closing this.
