### ISSUE TITLE
fisheye camera distortion issue

### ISSUE THREAD

**Issue by huanglilong** [borglab/gtsam#1325]
https://github.com/borglab/gtsam/blob/256c664aaaa27a3204411e461d4d93c0e168bd6b/gtsam/geometry/Cal3Fisheye.cpp#L57

@ghaggin according to https://arxiv.org/pdf/1807.08957.pdf and https://users.aalto.fi/~kannalj1/publications/tpami2006.pdf

`const double s = scaling * K.dot(T);` should be `const double s = scaling * K.dot(T) * t;`

because K.dot(T)  is not equals to d(t) in (27)
![image](https://user-images.githubusercontent.com/7278867/201515735-ac20669d-292f-43ea-99a6-4e5eb9e5967c.png)

cc: @dellaert @varunagrawal

**Comment by huanglilong** [comment]
the issue is from this pull https://github.com/borglab/gtsam/pull/307 @ghaggin @dellaert 
![image](https://user-images.githubusercontent.com/7278867/201516409-b9e2dd0b-606c-4e14-a6bf-fcd0341d3bdc.png)

**Comment by varunagrawal** [comment]
That's interesting. Looks like we don't have the correct unit test coverage for this.

**Comment by huanglilong** [comment]
from kalibr: https://github.com/ethz-asl/kalibr/blob/master/aslam_cv/aslam_cameras/include/aslam/cameras/implementation/EquidistantDistortion.hpp#L23
<img width="586" alt="image" src="https://user-images.githubusercontent.com/7278867/201530182-879c3193-f2b9-4f27-8885-f4aae5eb0309.png">

**Comment by huanglilong** [comment]
@varunagrawal @ghaggin @roderick-koehle @dellaert please review https://github.com/borglab/gtsam/pull/1326
