### ISSUE TITLE
Python warpped install error:pyparsing.exceptions.ParseException

### ISSUE THREAD

**Issue by Wjt-shift** [borglab/gtsam#1342]
I want to install gtsam in anaconda virtual enviroment.use follow commend:
**mkdir <gtsam_dir>/build
cd <gtsam_dir>/build
cmake .. -DGTSAM_BUILD_PYTHON=1 -DGTSAM_PYTHON_VERSION=3.9.15 -DCMAKE_INSTALL_PREFIX=/home/wjt/software/anaconda3/envs/slam
make python-install**
And get this error.I don't know what cause it.I try install diferent version pyparsing.But can't solve it.Can someobe help me?Thank you a lot!
![image](https://user-images.githubusercontent.com/78065132/207806043-c6cd9b5d-4eb4-4739-bd01-8eb38132f04c.png)

**Comment by varunagrawal** [comment]
What version of pyparsing do you have installed?

**Comment by hjxwhy** [comment]
@varunagrawal hello, I have also the same problem, I have tried pyparsing 2.4.2 and 3.0.9, the problem can not be solved.

**Comment by ProfFan** [comment]
@hjxwhy Could you provide the output of you entire shell history?

Also please provide your CMakeCache.txt contents in a gist.

Thank you!

**Comment by VladDok** [comment]
May be we have similar issues.
![123](https://user-images.githubusercontent.com/84400404/209843136-66954830-c3c4-4dbc-8206-3a0a0d2f0809.jpg)

**Comment by varunagrawal** [comment]
@VladDok @hjxwhy we will need more information than that please.
Please give us your OS, your python version, the version of pyparsing and any other relevant information (e.g. did you change any files?).

**Comment by VladDok** [comment]
@varunagrawal, additional information:
**Ubuntu 22.04.01
Python 3.9.12
pyparsing 3.0.9

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0**

No, I didn't change anything.

**Comment by varunagrawal** [comment]
And are you using the develop branch of GTSAM?

**Comment by VladDok** [comment]
I am using MAIN.

**Comment by varunagrawal** [comment]
@VladDok @Wjt-shift it seems both of you are trying to compile NeRF-SLAM. This seems to be an issue with that codebase and not GTSAM.
Have you tried cloning GTSAM separately and compiling it?

**Comment by varunagrawal** [comment]
I am able to reproduce this with NeRF-SLAM. This is a problem in that repo so please raise an issue there.

**Comment by VladDok** [comment]
@varunagrawal, thank for answer.
