### ISSUE TITLE
Incomplete type 'gtsam::HybridGaussianFactorGraph'

### ISSUE THREAD

**Issue by varunagrawal** [borglab/gtsam#1382]
## Description

Compiling a project that uses GTSAM's new hybrid module throws an error

```
../../../include/gtsam/hybrid/HybridNonlinearFactorGraph.h:71:3: error: incomplete type 'gtsam::HybridGaussianFactorGraph' named in nested name specifier
  HybridGaussianFactorGraph::shared_ptr linearize(
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/gtsam/hybrid/HybridNonlinearFactorGraph.h:25:7: note: forward declaration of 'gtsam::HybridGaussianFactorGraph'
class HybridGaussianFactorGraph;
```

This error only happens when compiling a project that depends on GTSAM.

The RCA is that the `#include` for `HybridGaussianFactorGraph` was removed and replaced with a forward declaration. The forward declaration works within the GTSAM framework but errors out once we go to an external project.

Tagging @dellaert for his information.

## Steps to reproduce

1. Create a project with a script that uses the `HybridNonlinearFactorGraph`.
2. Compile it with CMake.

## Expected behavior

External project should compile cleanly.

**Comment by varunagrawal** [comment]
Fix is to include in the .h file (even though the usage is only in the .cpp file).

**Comment by dellaert** [comment]
I can add it in next PR

**Comment by dellaert** [comment]
> Fix is to include in the .h file (even though the usage is only in the .cpp file).

@varunagrawal maybe I misunderstood: you mean the .h file in your project, and hence it is not a GTSAM issue? In that case I'll close again.

**Comment by varunagrawal** [comment]
@dellaert I added the comment in #1383

**Comment by varunagrawal** [comment]
@dellaert I am rethinking this issue and I find it odd that a user needs to include `HybridGaussianFactorGraph.h` even when they don't use it. Moreover, this is easy to break since in routine code cleanup, someone may delete that header and then get this weird issue. Thoughts?

**Comment by dellaert** [comment]
What happens if you don’t use ::shared_ptr, but use boost::shared_ptr instead?

**Comment by varunagrawal** [comment]
That works! Adding it to #1387
