### ISSUE TITLE
HybridFactorGraph `discreteKeys` has duplicate keys

### ISSUE THREAD

**Issue by varunagrawal** [borglab/gtsam#1384]
## Description

Calling `HybridFactorGraph::discreteKeys` results in duplicate keys which can lead to subtle bugs.
For example, if we pass in the result to `gtsam::DiscreteValues::CartesianProduct();` this would result in a much more expensive computation since instead of 3 discrete keys, we now have many more.

We can't use `discreteKeySet` since that method throws away the cardinality of the discrete keys.

## Steps to reproduce

Call `HybridFactorGraph::discreteKeys` and print out the result.

**Comment by dellaert** [comment]
Good catch, fixed in #1380, please approve that ASAP as I want to build on it.
