### ISSUE TITLE
Expose GPSFactor and GPSFactor2 in the Python wrapper

### ISSUE THREAD

**Issue by octopuscabbage** [borglab/gtsam#141]
## Feature

We would like GPSFactor and GPSFactor2 exposed in the python API. 
Currently we have tried wrapping it ourselves in gtsam.h but are having problems with building it.

## Motivation

It would be useful to be able to use the full NavState in the python API. Currently only the IMU factors are implemented.

## Pitch

GPSFactor and GPSFactor2 to be usable in the python wrapper.

## Alternatives

Expose the ability to create custom factors in the python API.

## Additional context

None

**Comment by dellaert** [comment]
I would love to assist. Could you create a PR with your attempt at wrapping?
By the way, the language that gtsam.h accepts is close to c++ but not quite. See comments at top. My approach to debugging it is to start with an empty class and then add methods one by one to find problem. Error reporting is terrible, but we are working on a new wrap...

**Comment by octopuscabbage** [comment]
Will do, I'll talk with my colleague and put what we have so far in a fork. 

We read the preamble and think our code conforms to it but yeah it has some weird bad parsing error.

**Comment by octopuscabbage** [comment]
We actually got it to build - we'll post our PR later.

**Comment by dellaert** [comment]
Excellent!! Look forward to it 👍

**Comment by dellaert** [comment]
@octopuscabbage don't forget the PR :-)

**Comment by dellaert** [comment]
Fixed by PR #155 . Thanks @MandyXie !
