### ISSUE TITLE
Status of removing boost from gtsam

### ISSUE THREAD

**Issue by kartikarcot** [borglab/gtsam#1414]
# Remaining tasks/issues with removing boost.

As of PR #1444 we have the option of completely removing boost, but we need to do some cleanup:

- [x] BIGGEST ISSUE: python wrapper needs boost, @ProfFan and @varunagrawal ?
- [ ] Related: how can we conditionally compile things into the wrapper: GncOptimizer will not work without boost...

- [ ] Ordering and FactorGraph need their += operators re-instated as deprecated functionality (default on) when we turn BOOST off by default.

- [ ] GnC Optimizer was deactivated because there was no easy replacement for `Chi2Inv`. It was deactivated in both
python bindings as well as in Cpp code. It will have to be brought back. Maybe @lucacarlone and team can take this one.

- [x] Python bindings DONT COMPILE because `EliminateAbleFactorGraph` moved away fram `boost::variant` to `std::variant`. This in turn led to moving to using `std::reference_wrapper`. Which causes issues with python bindings. **Resolution(dellaert): refactored in PR #1442** 

- [x] CppUnitLite library uses `boost::lexical_cast` that needs to be replaced with `std::to_string` maybe
Maybe @varunagrawal has a PR for that...

- [ ] All timing functionality provided by `timing.h` were conditionally compiled away since `boost::timers` did not have an easy stand-in replacement
- [ ] `Scheduler` and it's examples and it's tests were disabled because it used boost::tokenizer and boost::escaped_list_seperator
- [ ] `QPSolver` and it's examples, and it's tests were disabled

- [ ] `FindSeperator-inl.h` has usage of `boost::shared_array` that needs to be replaced or deactivated

- [ ] update docs, root/README.md "Quickstart" - change boost to optional prerequisite

- [ ] I disabled two segfaulting PoseRTV-related tests in unstable after replacing +=, maybe resurrect?

## Other things

Apart from this there is a bunch of stuff in Values.h regarding iterators and graphs which use boost's graphing features that need to be replaced as well.

Resolution(dellaert): gone in #1408

**Comment by ProfFan** [comment]
@dellaert I think the custom operators should be removed, as `Ordering` moves to being a std container

**Comment by dellaert** [comment]
This is done :-)
