### ISSUE TITLE
TangentPreintegration 

### ISSUE THREAD

**Issue by RobotGithubLee** [borglab/gtsam#143]
In TangentPreintegration.cpp, updatePreintegrated()  function:

"Vector9 preintegratedPlus;
  preintegratedPlus << // new preintegrated vector:
  theta + w_tangent * dt, // theta
  position + velocity * dt + a_nav * dt22, // position
  velocity + a_nav * dt; // velocity"

Why not consider gravity?

**Comment by dellaert** [comment]
Excellent question, but better for the GTSAM Google group? The short answer is that the whole idea behind pre-integration is to integrate the IMU and gravity separately. They are then brought together in the IMUFactor, where the unknown gravity orientation is optimized for. The long story can be found in the papers by us but also Lipton & Sukkarieh, who had this brilliant idea.
