### ISSUE TITLE
cmake error.

### ISSUE THREAD

**Issue by JohnSengers** [borglab/gtsam#1435]
Hi,

In the quickstart guide it shows the following structure to install GTSAM.

`mkdir build`
`cd build`
`cmake ..`
`make check # (optional, runs unit tests)`
`make install`

I reckon it also assumes you have copied the github repository in your root library folder.

This means that the current folder is  .../.../lib/build  
The next step is to use the command " cmake .."  but this leads to a cmake error since there is no cmakelists.txt in the designated location. 
Is there something I am missing?
Should I change my directory to .../.../lib/GTSAM perhaps?

Thanks in advance

**Comment by ProfFan** [comment]
Please use the forums for questions
