### ISSUE TITLE
testSmartStereoProjectionFactorPP unstable

### ISSUE THREAD

**Issue by dellaert** [borglab/gtsam#1445]
## Description

testSmartStereoProjectionFactorPP.cpp is unstable after PR #1442, i.e. fails in *some* workflows.

## Steps to reproduce

Unfortunately: run CI on #1442....

## Expected behavior

Should fail deterministically, or succeed on all platforms.

## Environment

Seems special cases workflow, especially TBB, fails.
https://github.com/borglab/gtsam/actions/runs/4099700133/jobs/7069846556

## Additional information

I turned GTSAM_SINGLE_TEST_EXE off as we look into it, we should turn it back ON if a PR fixes this issue.

I have no idea what's up, but SmartStereoProjectionFactorPP is a complex class that does some funky things, so my hunch is that it is there. For now I will exclude it from the CI.

**Comment by varunagrawal** [comment]
@dellaert I tried this again since I did a lot of looking into TBB when implementing the hybrid bayes tree. It seems like this issue is resolved, since I can't reproduce it on my machine. I'll create a PR to re-enable the test and we can look into it.
