### ISSUE TITLE
Why the optimizer didn't work and the deltaTij_ is zero?

### ISSUE THREAD

**Issue by JiangWeiHn** [borglab/gtsam#1446]
I change the ImuFactorsExample.cpp to  fit my dataset.It works well  at the IMU preintegration part. Bug when use LevenbergMarquardtOptimizer. I find that the optimizer didn't work,the result exactly equal to the prop_state.And
it has nothing to do with gps data. After debug the programme, I find that when calculate the ImuFactor error ,the  deltaTij is zero.But the preintegration part the deltaTij is not zero.It confuse me . Please help me ,I do not know how to fix it.Here is my code:

      GPSFactor gps_factor(X(correction_count),gps, correction_noise);
      graph->add(gps_factor);
      // Now optimize and compare results.
      prop_state = preintegrated->predict(prev_state, prev_bias);
        
      initial_values.insert(X(correction_count), prop_state.pose());
      initial_values.insert(V(correction_count), prop_state.v());
      initial_values.insert(B(correction_count), prev_bias);
      Values result;
      if (use_isam) {
        isam2->update(*graph, initial_values);
        result = isam2->calculateEstimate();

        // reset the graph
        graph->resize(0);
        initial_values.clear();

      } else {
        LevenbergMarquardtOptimizer optimizer(*graph, initial_values);
        result = optimizer.optimize();
      }
       
      prev_state = NavState(result.at<Pose3>(X(correction_count)),
                            result.at<Vector3>(V(correction_count)));
      prev_bias = result.at<imuBias::ConstantBias>(B(correction_count));

**Comment by dellaert** [comment]
Where is the IMUFactor?

**Comment by JiangWeiHn** [comment]
sorry ,i didn't paste all the code.This is it.

#include <boost/program_options.hpp>

// GTSAM related includes.
#include <gtsam/inference/Symbol.h>
#include <gtsam/navigation/CombinedImuFactor.h>
#include <gtsam/navigation/GPSFactor.h>
#include <gtsam/navigation/ImuFactor.h>
#include <gtsam/nonlinear/ISAM2.h>
#include <gtsam/nonlinear/LevenbergMarquardtOptimizer.h>
#include <gtsam/nonlinear/NonlinearFactorGraph.h>
#include <gtsam/slam/BetweenFactor.h>
#include <gtsam/slam/dataset.h>
#include <gtsam/navigation/OdometerFactor.h>
#include <gtsam/navigation/ImuFactor.h>
#include <cstring>
#include <fstream>
#include <iostream>
#include <cmath>

#define PI 3.141592653589793
#define R2D 57.295779513082320876798154814105f
#define D2R 0.017453292519943295769236907684886f

using namespace gtsam;
using namespace std;

using symbol_shorthand::B;  // Bias  (ax,ay,az,gx,gy,gz)
using symbol_shorthand::V;  // Vel   (xdot,ydot,zdot)
using symbol_shorthand::X;  // Pose3 (x,y,z,r,p,y)
using symbol_shorthand::A;  // DeltaAngle Vector3(r,p,y)
using symbol_shorthand::M;  //DeltaArm Vector3(x,y,z)



// namespace po = boost::program_options;
double starttime = 440190;
double endtime = 442050;
struct ImuRaw {
    double sow;       /* s */
    double dtheta[3]; /* gyro, rad */
    double dvel[3];   /* acce, m/s */
};


boost::shared_ptr<PreintegratedCombinedMeasurements::Params> imuParams(double imuGravity) {
  // We use the sensor specs to build the noise model for the IMU factor.
  double accel_noise_sigma = 0.05;
  double gyro_noise_sigma = 0.001;
  double accel_bias_rw_sigma = 0.005;
  double gyro_bias_rw_sigma = 0.0008;
  Matrix33 measured_acc_cov = I_3x3 * pow(accel_noise_sigma, 2);
  Matrix33 measured_omega_cov = I_3x3 * pow(gyro_noise_sigma, 2);
  Matrix33 integration_error_cov =
      I_3x3 * 1e-4;  // error committed in integrating position from velocities
  Matrix33 bias_acc_cov = I_3x3 * pow(accel_bias_rw_sigma, 2);
  Matrix33 bias_omega_cov = I_3x3 * pow(gyro_bias_rw_sigma, 2);
  Matrix66 bias_acc_omega_init =
      I_6x6 * 1e-4;  // error in the bias used for preintegration


  auto p = PreintegratedCombinedMeasurements::Params::MakeSharedD(imuGravity);
  // PreintegrationBase params:
  p->accelerometerCovariance =
      measured_acc_cov;  // acc white noise in continuous
  p->integrationCovariance =
      integration_error_cov;  // integration uncertainty continuous
  // should be using 2nd order integration
  // PreintegratedRotation params:
  p->gyroscopeCovariance =
      measured_omega_cov;  // gyro white noise in continuous
  // PreintegrationCombinedMeasurements params:
  p->biasAccCovariance = bias_acc_cov;      // acc bias in continuous
  p->biasOmegaCovariance = bias_omega_cov;  // gyro bias in continuous
  p->biasAccOmegaInt = bias_acc_omega_init;

  return p;
}

Point3 LLA2NED(Point3& now,Point3& origin){
  double Ea = 6378137.0000000000;
  Point3 O;
  double Eb = 6356752.3142451793;
  now(0) = now(0)*D2R;
  now(1) = now(1)*D2R;
  O(0) = origin(0)*D2R;
  O(1) = origin(1)*D2R;
  O(2) = origin(2);
  double Ec = Ea*(1.0-(Ea-Eb)/Ea*pow(sin(now(0)),2))+now(2);
  double Ed = Ec*cos(now(0));
  double d_lat = now(0)-O(0);
  double d_lon = now(1)-O(1);
  double x = d_lat*Ec;
  double y = d_lon*Ed;
  double z = O(2)-now(2);
  return (Point3(x,y,z));
}
static double gravity(const Vector3 &blh) {

        double sin2 = sin(blh[0]);
        sin2 *= sin2;

        return 9.7803267715 * (1 + 0.0052790414 * sin2 + 0.0000232718 * sin2 * sin2) +
               blh[2] * (0.0000000043977311 * sin2 - 0.0000030876910891) + 0.0000000000007211 * blh[2] * blh[2];
    } 

int main(int argc, char* argv[]) {
  string output_filename,odOut;
  ImuRaw imu_raw={0};
  bool use_isam = false;
  Vector3 gyroai,acceai;
  Vector3 Zk,Rk;
  Point3 origin;
  Point3 now;
     
  ifstream ifimu,ifgnss,ifrefer,ifodo;
  std::cout<<"finding the file"<<std::endl;
  ifimu.open("/home/room/workspace/JW/gtsam/gtsam-develop/dataset/IMU_data.bin",ifstream::binary);
  ifgnss.open("/home/room/workspace/JW/gtsam/gtsam-develop/dataset/GNSS_data.txt");
  ifodo.open("/home/room/workspace/JW/gtsam/gtsam-develop/dataset/odometer_speed.txt");
  std::cout<<"find the file"<<std::endl;
  double odot = 0.0,odovl,odovr;
  double tk =0.0;
  double gnsst =0.0;
  while (tk <starttime){
    ifimu.read((char*)&imu_raw,sizeof(ImuRaw));
    tk=imu_raw.sow;
    gyroai<<imu_raw.dtheta[0],imu_raw.dtheta[1],imu_raw.dtheta[2];
    acceai<<imu_raw.dvel[0],imu_raw.dvel[1],imu_raw.dvel[2];
  }
  while (gnsst<starttime){
   ifgnss>>gnsst>>origin(0)>>origin(1)>>origin(2)>>Rk(0)>>Rk(1)>>Rk(2);
  }
  ifgnss>>gnsst>>now(0)>>now(1)>>now(2)>>Rk(0)>>Rk(1)>>Rk(2);
  while (odot<starttime){
    ifodo>>odot>>odovl>>odovr;
  }
  ifodo>>odot>>odovl>>odovr;
  std::cout<<"got the start time data"<<std::endl;
  double measuredOd = (odovl+odovr)/2.0*0.1;

  output_filename = "/home/room/workspace/JW/gtsam/gtsam-develop/examples/result/imuFactorExampleResults.csv";
  ISAM2* isam2  =0;
  odOut =  "/home/room/workspace/JW/gtsam/gtsam-develop/examples/result/odFactorExampleResults.csv";
  use_isam = true;
  if (use_isam) {
    printf("Using ISAM2\n");
    ISAM2Params parameters;
    parameters.relinearizeThreshold = 0.01;
    parameters.relinearizeSkip = 1;
    isam2 = new ISAM2(parameters);

  } else {

    printf("Using Levenberg Marquardt Optimizer\n");
  }

  // Set up output file for plotting errors
  FILE* fp_out = fopen(output_filename.c_str(), "w+");
  FILE* fd_out = fopen(odOut.c_str(), "w+");
  fprintf(fp_out,
          "#time(s),r(deg),p(deg),y(deg),vx(m/s),vy(m/s),vz(m/s),x(m),y(m),z(m),gt_x(m),gt_y(m),gt_z(m),current_position_error\n");
  
  fprintf(fd_out,
          "#time(s),arm_x(m),arm_y(m),arm_z(m),install_angle_x(deg),install_angle_y(deg),install_angle_z(deg)\n");
  std::cout<<"start init"<<std::endl;
  Vector10 initial_state;

  
  Rot3 prior_rotation = Rot3::RzRyRx(-0.62393*D2R,0.30724*D2R,174.75054*D2R);

  Point3 prior_point(0.0,0.0,0.0);
  Vector3 init_position(30.5299589600*D2R,114.3560904417*D2R,17.6010000000);

  Vector3 prior_position=prior_point;
  Vector3 prior_attitude_angle = prior_rotation.rpy();
  Pose3 prior_pose(prior_rotation, prior_point);
  Vector3 prior_velocity(0,0,0);
  imuBias::ConstantBias prior_imu_bias;  // assume zero initial bias
  Point3 prior_delta_arm(0.0,0.0,0.0);
  Vector3 prior_delta_installangle(0.0,0.0,0.0);
  Vector3 InstallAngle(10.0,3.5,-8.5);
  Point3 arm(0.05,0.35,0.1);
  
  Values initial_values,odintial_values;
  int correction_count = 0;
  int od_correction_count = 0;
  initial_values.insert(X(correction_count),prior_pose);
  initial_values.insert(V(correction_count), prior_velocity);
  initial_values.insert(B(correction_count), prior_imu_bias);
  odintial_values.insert(A(od_correction_count),prior_delta_installangle);
  odintial_values.insert(M(od_correction_count),prior_delta_arm);
  // Assemble prior noise model and add it the graph.`
  auto pose_noise_model = noiseModel::Diagonal::Sigmas(
      (Vector(6) << 0.01, 0.01, 0.01, 0.5, 0.5, 0.5)
          .finished());  // rad,rad,rad,m, m, m
  auto velocity_noise_model = noiseModel::Isotropic::Sigma(3, 0.1);  // m/s
  auto bias_noise_model = noiseModel::Isotropic::Sigma(6, 1e-3);
  auto arm_noise_model = noiseModel::Isotropic::Sigma(3, 0.003);
  auto angle_noise_model = noiseModel::Isotropic::Sigma(3, 0.001);
  // Add all prior factors (pose, velocity, bias) to the graph.
  NonlinearFactorGraph* graph = new NonlinearFactorGraph();
  NonlinearFactorGraph* odgraph = new NonlinearFactorGraph();
  graph->addPrior(X(correction_count), prior_pose, pose_noise_model);
  graph->addPrior(V(correction_count), prior_velocity, velocity_noise_model);
  graph->addPrior(B(correction_count), prior_imu_bias, bias_noise_model);
  odgraph->addPrior(A(od_correction_count),prior_delta_installangle,angle_noise_model);
  odgraph->addPrior(M(od_correction_count),prior_delta_arm,arm_noise_model);
  double g = gravity(init_position);
  auto p = imuParams(g);
  std::shared_ptr<PreintegrationType> preintegrated =
      std::make_shared<PreintegratedImuMeasurements>(p, prior_imu_bias);
  std::shared_ptr<PreintegratedOdometerMeasurement> odpreintegrated = std::make_shared<PreintegratedOdometerMeasurement>();
  assert(preintegrated);

  // Store previous state for imu integration and latest predicted outcome.
  NavState prev_state(prior_pose, prior_velocity);
  NavState prop_state = prev_state;
  imuBias::ConstantBias prev_bias = prior_imu_bias;

  // Keep track of total error over the entire run as simple performance metric.
  double current_position_error = 0.0, current_orientation_error = 0.0;
  
  double output_time = 0.0;
  double dt = 0.005;  // The real system has noise, but here, results are nearly
                      // exactly the same, so keeping this for simplicity.
  double S0 = 1.2;
  double allOd = 0.0;
  Vector3 rk(0.0,0.0,0.0);
  Vector3 thetaPrior(0.0,0.0,0.0),thetaCurrent;

  auto preint_imu =
          dynamic_cast<const PreintegratedImuMeasurements&>(*preintegrated);
  // All priors have been set up, now iterate through the data file.
  std::cout<<"start compute the data"<<std::endl;
  while (!ifimu.eof()&&!ifgnss.eof()&&!ifodo.eof()&&(tk<endtime)) {

      Vector6 imu;
      ifimu.read((char*)&imu_raw,sizeof(ImuRaw));
      tk=imu_raw.sow;
      for(int i = 0;i<3;i++){
        imu(i)=imu_raw.dvel[i]/dt;
        imu(i+3)=imu_raw.dtheta[i]/dt;
      } 
      
      // Adding the IMU preintegration.
      preintegrated->integrateMeasurement(imu.head<3>(), imu.tail<3>(), dt);
     
      // adding the odometer preintegration
      
     
    // } else if (type == 1) {  // GPS measurement
    if (tk>gnsst+0.0005){    
      Point3 gps;
      gps = LLA2NED(now,origin);
      correction_count++;
      std::cout<<"start combine the gnss data"<<std::endl;
      // Adding IMU factor and GPS factor and optimizing.
      
      auto preint_odo = dynamic_cast<const PreintegratedOdometerMeasurement&>(*odpreintegrated);
      ImuFactor imu_factor(X(correction_count - 1), V(correction_count - 1),
                           X(correction_count), V(correction_count),
                           B(correction_count - 1), preint_imu);
      graph->add(imu_factor);
      imuBias::ConstantBias zero_bias(Vector3(0, 0, 0), Vector3(0, 0, 0));
      graph->add(BetweenFactor<imuBias::ConstantBias>(
          B(correction_count - 1), B(correction_count), zero_bias,
          bias_noise_model));

      auto correction_noise = noiseModel::Isotropic::Sigma(3, 0.1);
      GPSFactor gps_factor(X(correction_count),gps, correction_noise);
      graph->add(gps_factor);

      // Now optimize and compare results.
      prop_state = preintegrated->predict(prev_state, prev_bias);
        
      initial_values.insert(X(correction_count), prop_state.pose());
      initial_values.insert(V(correction_count), prop_state.v());
      initial_values.insert(B(correction_count), prev_bias);
      Values result;
      if (use_isam) {
        isam2->update(*graph, initial_values);
        result = isam2->calculateEstimate();

        // reset the graph
        graph->resize(0);
        initial_values.clear();

      } else {
        LevenbergMarquardtOptimizer optimizer(*graph, initial_values);
        result = optimizer.optimize();
      }
       
      prev_state = NavState(result.at<Pose3>(X(correction_count)),
                            result.at<Vector3>(V(correction_count)));
      prev_bias = result.at<imuBias::ConstantBias>(B(correction_count));
     
 
       // Print out the position and orientation error for comparison.
      Vector3 gtsam_position = prev_state.pose().translation();
      Vector3 AttitudeAngle = result.at<Pose3>(X(correction_count)).rotation().rpy();
      Vector3 velocity =  result.at<Vector3>(V(correction_count));
      Vector3 position_error = gtsam_position - Vector3(gps(0),gps(1),gps(2));
      current_position_error = position_error.norm();
      // display statistics
      std::cout << "Position error:" << current_position_error << "\t ";

      fprintf(fp_out, "%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f\n",
              output_time,AttitudeAngle(0),AttitudeAngle(1),AttitudeAngle(2),velocity(0),velocity(1),velocity(2), gtsam_position(0), gtsam_position(1),
              gtsam_position(2), gps(0), gps(1), gps(2),current_position_error);

      output_time += 1.0;

      // preintegrated->resetIntegrationAndSetBias(prev_bias);
      // OdometerFactor odo_factor(M(od_correction_count),A(od_correction_count),preint_odo);
     
      // std::cout<<"start combine the odometer data"<<std::endl;
      // Values OdResult;
      // std::default_random_engine e1(time(0));
      // std::normal_distribution<double> distribution(0.0,0.1);
      // double DeltaS = distribution(e1)*1.0;
      // std::cout<<DeltaS<<std::endl;
  
     
      // Vector3 DeltaPosition = result.at<Pose3>(X(correction_count)).translation()- prior_position;
      // Vector3 theta = AttitudeAngle - prior_attitude_angle;
      // Vector3 Omega = Vector3(imu(3),imu(4),imu(5))-result.at<imuBias::ConstantBias>(B(correction_count)).accelerometer();
      // odo_factor.UpdataParam(allOd,InstallAngle,rk,AttitudeAngle, DeltaS,DeltaPosition,theta,Omega,1.0);
      // odgraph->add(odo_factor);
      // // Overwrite the beginning of the preintegration for the next step.
      // LevenbergMarquardtOptimizer OdOptimizer(*odgraph, odintial_values);
      // OdResult = OdOptimizer.optimize();

      // Vector3 deltaAngle = OdResult.at<Vector3>(A(od_correction_count));
      // Point3 deltaArm = OdResult.at<Point3>(M(od_correction_count));
      // InstallAngle=InstallAngle-deltaAngle;
      // arm=arm -deltaArm;
      // od_correction_count +=1;
      // odintial_values.insert(M(od_correction_count),deltaArm);
      // odintial_values.insert(A(od_correction_count),deltaAngle);

      // odo_factor.ResetRK(0.0);
      // Vector3 rk(0.0,0.0,0.0);
      //fprintf(fd_out,"%f,%f,%f,%f,%f,%f,%f\n",output_time,arm(0),arm(1),arm(2),InstallAngle(0),InstallAngle(1),InstallAngle(2));
      // allOd = 0;
      // prior_attitude_angle = AttitudeAngle;
      // // Reset the preintegration object.
      // prior_position = result.at<Pose3>(X(correction_count)).translation();
      ifgnss>>gnsst>>now(0)>>now(1)>>now(2)>>Rk(0)>>Rk(1)>>Rk(2);
    }
    if (tk>odot){
      // thetaCurrent  =  preint_imu.preintegrated().head(3)-prev_state.pose().rotation().rpy();
      // odpreintegrated->OdIntegrateMeasurement(measuredOd,InstallAngle,rk,S0,
      //                                       thetaCurrent,thetaPrior,arm);
      // thetaPrior = thetaCurrent;
      // ifodo>>odot>>odovl>>odovr;
      // measuredOd = (odovl+odovr)/2.0*0.1;
      // allOd +=measuredOd;

     
    }

  }
  fclose(fp_out);
  fclose(fd_out);
  cout << "Complete, results written to " << output_filename << "\n\n";

  return 0;
}

**Comment by JiangWeiHn** [comment]
when i try the isam2,there is a error:
terminate called after throwing an instance of 'gtsam::IndeterminantLinearSystemException'
  what():  
Indeterminant linear system detected while working near variable
7061644215716937728 (Symbol: b0).

Thrown when a linear system is ill-posed.  The most common cause for this
error is having underconstrained variables.  Mathematically, the system is
underdetermined.  See the GTSAM Doxygen documentation at
http://borg.cc.gatech.edu/ on gtsam::IndeterminantLinearSystemException for
more information.

**Comment by JiangWeiHn** [comment]
I print the initial_values,it's this:
Values with 6 values:
Value b0: (gtsam::imuBias::ConstantBias)
acc = 0 0 0 gyro = 0 0 0

Value b1: (gtsam::imuBias::ConstantBias)
acc = 0 0 0 gyro = 0 0 0

Value v0: (Eigen::Matrix<double, 3, 1, 0, 3, 1>)
[
        0;
        0;
        0
]

Value v1: (Eigen::Matrix<double, 3, 1, 0, 3, 1>)
[
        -0.773251;
        0.0277616;
        0.039793
]

Value x0: (gtsam::Pose3)
R: [
        -0.995791, -0.0914287, -0.00633581;
        0.0914909, -0.995752, -0.0103532;
        -0.00536232, -0.0108893, 0.999926
]
t: 0 0 0

Value x1: (gtsam::Pose3)
R: [
        -0.995054, -0.098555, -0.0124033;
        0.0986521, -0.995094, -0.00747505;
        -0.0116057, -0.00866169, 0.999895
]
t:   -0.155385 0.000114898   0.0186261

**Comment by JiangWeiHn** [comment]
I find my fault, i put the preint_imu in the begin，and it point to default PreintegratedImuMeasurements,the preintMeasCov is zero.thanks a lot for help!
