### ISSUE TITLE
nightly build fails on ubuntu 18.04 with unrecognized command line option "-Wmissing"

### ISSUE THREAD

**Issue by berndpfrommer** [borglab/gtsam#1468]
Whenever the source tree is updated the Ubuntu nightly packages are rebuilt (the "develop" repository).
As of yesterday night the build for Ubuntu bionic (18.04) fails with the below error message. It looks to me as if it is failing while cmake is probing (like autoconf).
The log file says it's using this version of gcc: `gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) `
On the more modern Ubuntu versions (20.04 and 22.04) GTSAM builds just fine.

```
Source file was:
int main() { return 0; }
	cd obj-x86_64-linux-gnu && tail -v -n \+0 CMakeFiles/CMakeError.log
==> CMakeFiles/CMakeError.log <==
Performing C++ SOURCE FILE Test COMPILER_HAS_WMISSING_OVERRIDE failed with the following output:
Change Dir: /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_3e948/fast"
make[2]: Entering directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_3e948.dir/build.make CMakeFiles/cmTC_3e948.dir/build
make[3]: Entering directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_3e948.dir/src.cxx.o
/usr/bin/c++    -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DCOMPILER_HAS_WMISSING_OVERRIDE   -Wmissing -o CMakeFiles/cmTC_3e948.dir/src.cxx.o -c /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option '-Wmissing'; did you mean '-Waliasing'?
CMakeFiles/cmTC_3e948.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_3e948.dir/src.cxx.o' failed
make[3]: *** [CMakeFiles/cmTC_3e948.dir/src.cxx.o] Error 1

```

**Comment by varunagrawal** [comment]
@berndpfrommer the only change that would seem to do this would be updating from `add_definitions` to `add_compile_definitions`. Would that be the case? It doesn't seem to be related but I can't think of anything else.

**Comment by varunagrawal** [comment]
I'll wait till #1464 gets merged before making a new PR. @berndpfrommer seems like `add_compile_definitions` is a CMake 3.12 feature and Ubuntu 18.04 supports CMake 3.10 in the apt repository *sigh.

**Comment by berndpfrommer** [comment]
@varunagrawal nice catch!
supporting the old versions of Ubuntu is a drag but many robots still run on 18.04 or even 16.04. It was only a few months ago that NVidia released an upgraded Jetpack for my AGX Xavier to support Ubuntu 20.04.

**Comment by varunagrawal** [comment]
@berndpfrommer can you please confirm if the build works now?

**Comment by berndpfrommer** [comment]
I've had close to 40 build error warnings in my mail box related to failed gtsam builds on ubuntu's servers.
I'm not sure if it is because of this commit or because around the same time building-with-debug-symbols was enabled in the PPA.
CC'ing @jlblancoc so he's aware of us debugging a separate build issue right now.
```
- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/lib/cmake/GTSAMCMakeTools/FindNumPy.cmake
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/lib/cmake/GTSAMCMakeTools/README.html
make[1]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
   dh_install
dh_install: warning: Cannot find (any matches for) "usr/lib/*/libgtsam.so" (tried in ., debian/tmp)

dh_install: warning: libgtsam-dev missing files: usr/lib/*/libgtsam.so
	install -d debian/libgtsam-dev/usr/include/gtsam/
	cp --reflink=auto -a debian/tmp/usr/include/gtsam/3rdparty debian/tmp/usr/include/gtsam/base debian/tmp/usr/include/gtsam/basis debian/tmp/usr/include/gtsam/config.h debian/tmp/usr/include/gtsam/discrete debian/tmp/usr/include/gtsam/dllexport.h debian/tmp/usr/include/gtsam/geometry debian/tmp/usr/include/gtsam/global_includes.h debian/tmp/usr/include/gtsam/hybrid debian/tmp/usr/include/gtsam/inference debian/tmp/usr/include/gtsam/linear debian/tmp/usr/include/gtsam/navigation debian/tmp/usr/include/gtsam/nonlinear debian/tmp/usr/include/gtsam/precompiled_header.h debian/tmp/usr/include/gtsam/sam debian/tmp/usr/include/gtsam/sfm debian/tmp/usr/include/gtsam/slam debian/tmp/usr/include/gtsam/symbolic debian/libgtsam-dev/usr/include/gtsam//
dh_install: warning: Cannot find (any matches for) "usr/lib/*/libgtsam.so.*" (tried in ., debian/tmp)

dh_install: warning: libgtsam4 missing files: usr/lib/*/libgtsam.so.*
dh_install: warning: Cannot find (any matches for) "usr/lib/*/libgtsam_unstable.so.*" (tried in ., debian/tmp)

dh_install: warning: libgtsam-unstable4 missing files: usr/lib/*/libgtsam_unstable.so.*
dh_install: warning: Cannot find (any matches for) "usr/lib/*/libgtsam_unstable.so" (tried in ., debian/tmp)

dh_install: warning: libgtsam-unstable-dev missing files: usr/lib/*/libgtsam_unstable.so
dh_install: error: missing files, aborting
	install -d debian/.debhelper/generated/libgtsam-dev
	install -d debian/.debhelper/generated/libgtsam4
	install -d debian/.debhelper/generated/libgtsam-unstable4
	install -d debian/.debhelper/generated/libgtsam-unstable-dev
make: *** [debian/rules:9: binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```

**Comment by varunagrawal** [comment]
Building with Debug symbols may have caused the library name to change, e.g. libgtsamDebug which would explain the missing file issue.

Of course this is me shooting from the hip so I may be completely wrong.

**Comment by berndpfrommer** [comment]
I think you are on the right track there.

**Comment by jlblancoc** [comment]
That's indeed the case!  Building with debug symbols shouldn't change the .so names... it's ok for custom builds, but definitively not compliant with Debian packaging. 

Please, @berndpfrommer , change the debian/rules so it adds the cmake flag:

`-DGTSAM_BUILD_TYPE_POSTFIXES=Off`

**Comment by berndpfrommer** [comment]
@jlblancoc thanks, I would not have figured this one out on my own.
I made the changes to the 4.1.1 release repo and now it is building.
Installing the debug symbol packages is not  that easy. If found these instructions pretty unweildy:
https://wiki.ubuntu.com/Debug%20Symbol%20Packages
I was able to download the ".ddeb" package directly from the launchpad website and it has this content:
```
dpkg-deb -c libgtsam4-dbgsym_4.1.1-1ubuntu13_amd64.ddeb
drwxr-xr-x root/root         0 2023-02-18 10:31 ./
drwxr-xr-x root/root         0 2023-02-18 10:31 ./usr/
drwxr-xr-x root/root         0 2023-02-18 10:31 ./usr/lib/
drwxr-xr-x root/root         0 2023-02-18 10:31 ./usr/lib/debug/
drwxr-xr-x root/root         0 2023-02-18 10:31 ./usr/lib/debug/.build-id/
drwxr-xr-x root/root         0 2023-02-18 10:31 ./usr/lib/debug/.build-id/fd/
-rw-r--r-- root/root 134374536 2023-02-18 10:31 ./usr/lib/debug/.build-id/fd/a96d8a160b8e0d25e9d2c52dab4a37edebbb8d.debug

drwxr-xr-x root/root         0 2023-02-18 10:31 ./usr/share/
drwxr-xr-x root/root         0 2023-02-18 10:31 ./usr/share/doc/
lrwxrwxrwx root/root         0 2023-02-18 10:31 ./usr/share/doc/libgtsam4-dbgsym -> libgtsam4
```
Not sure how the debug symbols then find their way into the library but that's also how it looks for other packages.

**Comment by jlblancoc** [comment]
Despite the weird names of files, gdb finds them, no worries about that 😊

On how to install without manual download, I'll take a look. 

Thanks!

**Comment by berndpfrommer** [comment]
Now that the packaging has been updated the ubuntu builds should succeed. We'll find out on the next commit to the gtsam development branch.

**Comment by berndpfrommer** [comment]
Still failed on the last commit. Alas, it turns out *that flag was already switched off* in the debian/rules.
@jlblancoc can you pull another rabbit out of the hat?
In the meanwhile I'd love to understand why the debug symbols built correctly for the release 4.1.1 branch, but not for the nightly development snapshot. Working on it.

**Comment by berndpfrommer** [comment]
Making incremental progress.
- Found out that if no debug symbols are requested (that's the case that builds successfully), the build process is started with ``noautodbgsym``.  When this flag is missing, the build fails.
```
DEB_BUILD_OPTIONS=noautodbgsym parallel=4
```
Further, in the failing build log, the following ominous line appears:
```
-- GTSAM is a static library due to BUILD_SHARED_LIBS is OFF 
```
and in fact, the shared library is not built, only the static library., which obviously causes an error later during packaging, where a shared library is required.
But how come that without this flag only the static library is built?
Next step: trying to reproduce this behavior locally.

**Comment by jlblancoc** [comment]
What a funny trip... :-) 

@berndpfrommer  Please add this one to `debian/rules` too:  `-DBUILD_SHARED_LIBS=On`
and please, refresh me (once again... :roll_eyes: ) on what's the latest good and true GDB repo for gtsam... [this one](https://github.com/borglab-launchpad/gtsam-packaging) right? 

I can see the debian directory [in the branches](https://github.com/borglab-launchpad/gtsam-packaging/tree/ubuntu/snapshot), but not in the "master" branch which is the common case for GDB repos... can you refresh me on how it worked here? (just in case it's easy to reproduce the build locally with `gbp buildpackage`)

I could just change debian/rules on all the branches there myself but want to be sure the changes won't be overwritten by another script later on.

**Comment by berndpfrommer** [comment]
@jlblancoc Yes, you got the right repo there.
I'm not really familiar with this gbp stuff and I did not know that the debian build directory is supposed to be in the master branch. Truth be told I found gbp pretty unwieldy to work with which is why so much documentation was necessary. The master branch [has instructions on how to modify the debian directory](
https://github.com/borglab-launchpad/gtsam-packaging#how-to-modify-the-debian-files-for-nightly-snapshot-and-existing-releases).
Now part of the issues we are having is because we are not actually building the binary package but a source package, so we don't really know what's going to happen when the Ubuntu servers later build the binary from the source package. The steps of building of the source package are [outlined here](https://github.com/borglab-launchpad/gtsam-packaging#how-to-create-a-new-gtsam-release). Under step 4 there is a comment on how to build the binary instead of the source package. I will give that a try with your latest suggestion.
I really don't mean to be territorial but if you don't mind please delegate modifications to the packaging repo to me. The reason is that there is this hidden state on the Ubuntu packaging side: it remembers the version number so you are forced to bump it, and it remembers the pristine tarball. In the beginning there were several times I had to resort to nuking the PPA repo just to get rid of bad state and for the build servers to accept the source package. I'm not sure if people can still to "apt update" if I ever have to purge the repo again (so far that has not been necessary). It's easy to screw up the ppa but difficult to diagnose what's wrong and it is hard to get it back into shape.
