### ISSUE TITLE
Which is correct, `biasAccOmegaInt` or `biasAccOmegaInit`?

### ISSUE THREAD

**Issue by amadoantonini** [borglab/gtsam#1472]
This variable seems to have been renamed multiple times (along with comment) between "init" and "int". Currently the variable says "int" but the getter and setter say "init".
https://github.com/borglab/gtsam/blob/0a524dd02eb16ff0e474732dcfb4953e0fc8e4e6/gtsam/navigation/CombinedImuFactor.h#L64

**Comment by varunagrawal** [comment]
`Init` as in initialization is the correct one. This is a typo that's throwing a lot of people off, including @plusk01.

cc @dellaert, I can make the change if you're okay. It will also help to be consistent with the report @raabuchanan and I are writing up on the CombinedImuFactor.
