### ISSUE TITLE
tag: wrap-export file: gtsam/gtsam_unstable/slam/PartialPriorFactor.h:124:53: error: invalid initialization of reference of type ‘const std::vector&’ from expression of type ‘const std::vector’

### ISSUE THREAD

**Issue by dbdxnuliba** [borglab/gtsam#1491]
tag: wrap-export
file: gtsam/gtsam_unstable/slam/PartialPriorFactor.h:124:53: error: invalid initialization of reference of type ‘const std::vector&’ from expression of type ‘const std::vector’

**Comment by varunagrawal** [comment]
Hi @dbdxnuliba. Any reason you're using wrap-export and not the develop or master branch?

**Comment by varunagrawal** [comment]
Closing due to lack of a response.
