### ISSUE TITLE
Gtsam will throw an exception when optimizing a factor graph with a large number of nodes

### ISSUE THREAD

**Issue by CogmanCVN** [borglab/gtsam#1494]
When gtsam optimizes a factor graph with a large number of nodes, it throws an exception and the program exits directly (for example, there are 6933 nodes in the factor graph). Is there a solution to this problem?

**Comment by CogmanCVN** [comment]
The specific exception thrown is in this line of code： isam->update(gtSAMgraph, initialEstimate);

**Comment by ScottMcMichael** [comment]
I encountered this earlier and ended up implementing a fix on a fork:  

https://github.com/borglab/gtsam/issues/1434
https://github.com/ScottMcMichael/gtsam/tree/fix_large_graph_serialization_stack_overflow

**Comment by ProfFan** [comment]
I think we already fixed the serialization part, in #1441 ?

**Comment by ScottMcMichael** [comment]
I haven't gone back and tested anything since I put together my own fix, but just looking at that PR it doesn't seem like the same thing.

**Comment by dellaert** [comment]
Most likely fixed by #1441
