### ISSUE TITLE
add cmake option to build with memory sanitizer library

### ISSUE THREAD

**Issue by berndpfrommer** [borglab/gtsam#1499]
## Feature
Building with libsanitzer has helped me greatly in debugging memory issues. The way to build gtsam with it is described here:
https://gist.github.com/jlblancoc/44be9d4d466f0a973b1f3808a8e56782
Could this be made a cmake build option in GTSAM?
## Motivation
When users see the option they know it's easily possible to compile with sanitizer support and don't have to first find the instructions above.
@jlblancoc if you think this makes sense, then please leave this feature request open as a reminder to add this feature when you get around to it.

**Comment by ProfFan** [comment]
I think you can build with ASAN easily if you use Clang - just add `-fsanitize=address,undefined` to the CXX arguments when you run CMake

**Comment by berndpfrommer** [comment]
I agree that it can easily be accomplished (the link above gives the details). The rationale for adding an option is that people don't have to first search to find out how to do it (see Motivation above).

**Comment by ProfFan** [comment]
I think the "recommended" way is using the CMake presets, but not sure

**Comment by dellaert** [comment]
Happy to look at a PR - if none forthcoming we should probably close the issue.
