### ISSUE TITLE
matlab example NonlinearFactorGraph not found 

### ISSUE THREAD

**Issue by xzwang12345** [borglab/gtsam#1521]
Hi,
When I tested the matlab example Pose2SLAMExample.m, I  had encounter an error:
Undefined function or variable 'NonlinearFactorGraph'.
Error in Pose2SLAMExample (line 24)
I already added the gtsam toolbox path to matlab path, how can I solve this problem? 
Thanks

**Comment by varunagrawal** [comment]
Hi @xzwang12345 what system are you running this on? The Issue Template had a bunch of items to fill-in, can you please add all those details?

**Comment by xzwang12345** [comment]
Thanks for your reply!
Let me fill in the information:
My system is Ubuntu 18.04, gtsam version is 4.1.1,
My Compile command is 
```
cmake .. -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF -DGTSAM_BUILD_METIS_EXECUTABLES=ON -DGTSAM_USE_SYSTEM_EIGEN=ON -DGTSAM_INSTALL_MATLAB_TOOLBOX=ON -DGTSAM_UNSTABLE_INSTALL_MATLAB_TOOLBOX=ON  -DEXAMPLES_BUILD_MATLAB_TOOLBOX:OPTION=ON  -DGTSAM_PYTHON_VERSION=3.7.16 -DGTSAM_BUILD_PYTHON=1 -DGTSAM_BUILD_EXAMPLES_ALWAYS=ON
```
Then is compile successfully,and install gtsam_toolbox file in default path /usr/local/gtsam_toolbox,the file in the path is:
![2023-04-28 09-50-11屏幕截图](https://user-images.githubusercontent.com/13215990/235035318-bc8b46c0-8bb7-4871-ad5d-ffe22c573b05.png)
Next I add the gtsam_toolbox path to matlab path ,and run the example , Report an error: Undefined function or variable 'NonlinearFactorGraph'

**Comment by xzwang12345** [comment]
One more thing to add,the matlab version is R2018a

**Comment by mattking-smith** [comment]
@xzwang12345 can you please try adding the `GTSAM_ALLOW_DEPRECATED_SINCE_V = OFF` command to your `cmake` compile command? Also you are using the `develop` branch right? 

I just recently verified the latest GTSAM on my Linux OS, so it should work.
