### ISSUE TITLE
what X, Y and Z respectively represent in KittiGps_converted.txt

### ISSUE THREAD

**Issue by lifeiyu01** [borglab/gtsam#1525]
Hello,
I would like to know what X, Y and Z respectively represent in KittiGps_converted.txt
![image](https://user-images.githubusercontent.com/125882478/236182483-76e69b10-4e09-475d-919b-38e6ecd379ec.png)

**Comment by mikesheffler** [comment]
They're positions in either a local ENU or a local NED coordinate frame, but I'm not sure what the geodetic coordinates are for the local origin. You can take a look at the [GTSAM MATLAB Kitti dataset example](https://github.com/borglab/gtsam/blob/develop/matlab/gtsam_examples/IMUKittiExampleGPS.m) to figure out how to interpret the data (including a link to the Kitti benchmark data repository).

If you have more questions about the dataset, please ask in the GTSAM Users Google group. :)
