### ISSUE TITLE
Add UWBFactor

### ISSUE THREAD

**Issue by 520sp** [borglab/gtsam#1529]
Dear sir, I am doing UWB-related work and want to use your factor library. Could you please add UWBFactor in Navigation to optimize the GTSAM library?

**Comment by dellaert** [comment]
@ProfFan :-)
BTW there is already a Range factor...

**Comment by 520sp** [comment]
> Ok, thanks for the answer, I'll try to apply it.

**Comment by dellaert** [comment]
Great. Please re-open if it does not do the trick.
