### ISSUE TITLE
ISAM2 smart factors example - prior on each pose

### ISSUE THREAD

**Issue by tamasso-parec** [borglab/gtsam#1540]
Hi, I am not sure if this is the correct approach for this kind of questions, if I should just write an email let me know.

In the example: `ISAM2Example_SmartFactor.cpp` I see that a prior on the pose is added at the beginning of every iteration of the iSAM2 update: 

```
graph.addPrior(X(i), poses[i], noise);
initialEstimate.insert(X(i), poses[i].compose(delta));
```

I noticed that in other iSAM2 examples, this is not done, so I wonder if it makes sense to add a prior with the same noise at the beginning of every iteration or if one should use the marginal covariance of the latest pose from the previous iteration? Does iSAM2 take care of marginalization autonomously? When I look into the marginal covariances at the very end of the process, I have very small uncertainties. 

My question comes from me trying to tackle the same problem with a full smoothing approach on a simulated trajectory of 60 seconds. The marginals at the end are much higher in this case and I was wondering if the actual reason is that I am not  "forcefully" adding priors with a selected noise at every iteration. 

I do not have a very good understanding of the theory behind iSAM to be honest, although I did my research I am going through trial and error. Thanks for any help.

**Comment by varunagrawal** [comment]
@tamasso-parec I recommend asking these type of questions on the Google Group. The people there respond faster and are very knowledgeable. They should be able to help you answer these questions well.

As a quick answer, setting the same prior is not typical, we've just done it as a simple example. iSAM2 can perform marginalization but you need to call the marginalize method, and the marginals depend on the information provided through the factors.
