### ISSUE TITLE
GTSAM_UNSTABLE Multiple Defined Symbols

### ISSUE THREAD

**Issue by varunagrawal** [borglab/gtsam#1541]
When compiling GTSAM on Windows, `GTSAM_UNSTABLE` throws a compilation error due to multiple defined symbols in `LPInitSolver.obj`.

This could indicate some badness in the `GTSAM_UNSTABLE_EXPORT` in the files related to `LPInitSolver.obj`. Below is the output from the MSVC compiler:

```sh
Build started...
1>------ Build started: Project: gtsam_unstable, Configuration: Release x64 ------
1>gtsam.lib(gtsam.dll) : error LNK2005: "public: __cdecl std::map<unsigned __int64,unsigned __int64,struct std::less<unsigned __int64>,class std::allocator<struct std::pair<unsigned __int64 const ,unsigned __int64> > >::~map<unsigned __int64,unsigned __int64,struct std::less<unsigned __int64>,class std::allocator<struct std::pair<unsigned __int64 const ,unsigned __int64> > >(void)" (??1?$map@_K_KU?$less@_K@std@@V?$allocator@U?$pair@$$CB_K_K@std@@@2@@std@@QEAA@XZ) already defined in LPInitSolver.obj
1>   Creating library C:/Mike/Work/Build/gtsam/lib/Release/gtsam_unstable.lib and object C:/Mike/Work/Build/gtsam/lib/Release/gtsam_unstable.exp
1>C:\Mike\Work\Build\gtsam\gtsam_unstable\bin\Release\gtsam_unstable.dll : fatal error LNK1169: one or more multiply defined symbols found
1>Done building project "gtsam_unstable.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 69 up-to-date, 0 skipped ==========
```

**Comment by mikesheffler** [comment]
I have tried a few different games with `GTSAM_UNSTABLE_EXPORT` and checking CMake. So far, no luck.

I have a feeling (that's not terribly scientific) that it's something like the inclusion of a complete type from `gtsam` (vs. `gtsam_unstable`) in a .h file. For example, `InequalityFactorGraph` in `gtsam_unstable/linear/LPInitSolver.h`. That particular type doesn't seem to be a problem, but I'm trying to find an issue along those lines.

I'm going to be out of the country for a few weeks, so I won't be looking at this again until about mid-July.
