### ISSUE TITLE
Trouble using a Custom Factor

### ISSUE THREAD

**Issue by nikolaskoutroulakis** [borglab/gtsam#1543]
Hey, I am trying to use the CustomFactor class in Python, but I keep running into issues. I have looked at 1 or 2 examples, and they have helped a little, but I am still having trouble.

```
RuntimeError: A JacobianFactor was attempted to be constructed with a matrix block of
inconsistent dimension.  The JacobianFactor has 1 rows (i.e. length of
error vector) but the provided matrix block has 4 rows.
```

 I keep getting an error that says I am passing 4 rows to a Jacobian matrix, when it was only expecting one. However, I am passing a row matrix, as it specified, but it seems like every time I try, it the output looks like this 

```
JacobianVector[-0.451411
-0.610733
-0.650563
        1, , , ]
```

But when I print out the array that I passed, it looks like this
`[-0.4514114  -0.61073307 -0.65056349  1.       ]`

I have tried transposing the vector, unpacking each of the elements individually, adjusting the number of variables, and as a temporary fix to see if I could get the program to just move along, I tried implementing an identity matrix similar to the one in the examples. Nothing has worked, and I am running out of ideas. 

Some useful information: Transposing the Jacobian returned from the Jacobian function for some reason passes a zero dimensional matrix to the optimizer. Usually if I am running the debugger, these two actions allow me to finishing returning the error function, however, unpacking the variables, and a couple other things I have tried threw an error as soon as I was assigned to the Jacobian Vector.

Here are the functions that might be relevant, let me know if you need more code to help:
The error function:

```
# Is passed to CustomFactor
def Error(sat: Satellite, this: CustomFactor, values: Values, jacobians: np.ndarray):
    # Extract Values from initial estimate
    x_val = initialEst.atDouble(x.key())
    y_val = initialEst.atDouble(y.key())
    z_val = initialEst.atDouble(z.key())
    
    #Figure out the estimated distance, then compute the residual
    distance = Scenario.dist(sat, (x_val, y_val, z_val), sat.coords)
    estimate  = distance/c
    residual = sat.timeMeasurement - estimate
    
    test = np.array(jacobian(x_val, y_val, z_val, sat.coords, distance))
    
    # Fill in the Jacobian matrix
    if jacobians is not None:
        jacobians[0] = test
        
        
        
        print(test)
        print(jacobians)
    #Compute delta x, add to last prediction
    
    return [residual]
```
And how I fill up the factor graphs

```
# Symbols representing the unknown position of the receiver
n = scenario.numberOfSats
x = Symbol('x', n + 1) 
y = Symbol('y', n + 1)
z = Symbol('z', n + 1)
tau = Symbol('t', n + 1)

#Initial Estimates
initialEst = Values()
initialEst.insert(x.key(), 0.0)
initialEst.insert(y.key(), 0.0)
initialEst.insert(z.key(), 0.0)
initialEst.insert(tau.key(), 0.0)



# List of keys associated with the symbols
keys = [x.key(), y.key(), z.key(), tau.key()]

for i, sat in enumerate(scenario.sats, start=0):
    # Symbols representing the variables for each satellite
    sx = Symbol('x', i)
    sy = Symbol('y', i)
    sz = Symbol('z', i)
    stau = Symbol('t', i)

    # Create a factor, add it to the graph
    factor = CustomFactor(R, [sx.key(), sy.key(), sz.key(), stau.key()], partial(Error, sat))
    graph.add(factor)
```

This is my first time using GTSAM, and it seems like there is not a lot of resources out there to learn about, so I would it appreciate the help. Thanks in advance

**Comment by ProfFan** [comment]
If you look at the examples more closely you will see that it requires you vectors to be stored with `order='F'`, this is a limit by Pybind11. Also your Jacobian should have dimension `(1,n)` not `(1,)`, they are different.
