### ISSUE TITLE
Custom factor without Jacobian

### ISSUE THREAD

**Issue by shounak873** [borglab/gtsam#1547]
Hi, I want to create a custom factor but I am not sure how to get the analytic Jacobian. Can I just create the factor with the error formula z - f(x) and let gtsam calculate the Jacobian numerically?

**Comment by yetongumich** [comment]
You create a custom function that computes `z-f(x)`. Then, in the `evaluateError` function of your customized function, you can call the `numericalDerivative` function to compute the Jacobian numerically.

**Comment by shounak873** [comment]
Hi @yetongumich,  I am implementing a square root factor which basically looks like `sqrt(g(y - f(x)))`. `numericalDerivative`  should work fine for this?

**Comment by goodgoodliving** [comment]
> You create a custom function that computes `z-f(x)`. Then, in the `evaluateError` function of your customized factor, you can call the `numericalDerivative` function to compute the Jacobian numerically. Examples in `testNumericalDerivative.cpp` will help you get familiar with the function. 

@yetongumich 
Hello, may I ask if it's possible to automatically solve for the Jacobian using GTSAM if I'm implementing a custom factor in Python, where I only know the error function and am not familiar with how to perform the Jacobian calculation? Are there relevant interfaces for this in GTSAM?
