### ISSUE TITLE
Resizing factor graph when using iSAM

### ISSUE THREAD

**Issue by shounak873** [borglab/gtsam#1576]
Hello I have a conceptual question. 
All iSAM examples I have come across resize the factor graph to 0 and clear the initial values every time isam calculates an estimate. For example in `ISAM2Example_SmartFactor.cpp ` , `graph.resize(0)` and `initialEstimate.clear()` run within the loop. Why is it done this way? Can I not run iSAM real time but only resize after say 50 nodes have been added?

**Comment by varunagrawal** [comment]
Hi @shounak873. Please ask clarifying questions on the Google Group. You'll get a faster response there. The issues section is primarily for code related issues and bugs.
