### ISSUE TITLE
Serialization bug

### ISSUE THREAD

**Issue by tardifjp** [borglab/gtsam#158]
## Description
There seems to be a bug in CombinedImuFactor.h in the PreintegrationCombinedParams struct. When the serialize function is called,  only the data in PreintegratedRotation::Params will be serialized, but not the data in PreintegrationParams.

## Steps to reproduce

I didn't experience any segfault. I just came across while resolving some other issue.

## Expected behavior
In the current implementation, it is likely that the data in the superclass PreintegrationParams won't be serialized and only the one in PreintegratedRotationParams.

The fix apprears to be trivial:
ar& BOOST_SERIALIZATION_BASE_OBJECT_NVP(PreintegratedRotation::Params);
should probably be changed to:
ar& BOOST_SERIALIZATION_BASE_OBJECT_NVP(PreintegrationParams);
in the serialize function.

It would seem logical since PreintegrationParams that's the actual superclass. I tried the change already and It compiles just fine. However, I don't have a way to validate that change.

One would need to write a proper unit test.

**Comment by varunagrawal** [comment]
Thanks for reporting this @tardifjp. I'll take a look at it especially since you've already proposed a fix.
