### ISSUE TITLE
Error in test scrpipt  "TranslationAveragingExample.py"

### ISSUE THREAD

**Issue by anilesec** [borglab/gtsam#1604]
I run this [file](https://github.com/borglab/gtsam/blob/e36590aa456f968ae5314765eacadadb5d267d87/python/gtsam/examples/TranslationAveragingExample.py
) to test TranslationAveraging, I get the attached error.

![image](https://github.com/borglab/gtsam/assets/23581858/b1e525a6-63ad-4aca-9eab-676a61e686e9)

**Comment by varunagrawal** [comment]
Hi @anilesec. Are you using the develop branch of GTSAM? And are you compiling and installing the GTSAM python bindings, or installing the library from pip?

We can help you if you provide more information. I cannot reproduce this issue on my machine.

**Comment by anilesec** [comment]
Hi @varunagrawal 

Thanks for the response!
I have installed "pip install gtbook" and then run the TranslationAveraging.py

**Comment by varunagrawal** [comment]
Any particular reason you're using the `gtbook` python package? You should be able to get the example running by using `pip install gtsam==4.2a9`.

**Comment by varunagrawal** [comment]
@anilesec we've released 4.2 officially so this should be resolved. If you're still having issues, please reopen.
