### ISSUE TITLE
doc/CMakeLists.txt refers to non-existent variable

### ISSUE THREAD

**Issue by dkogan** [borglab/gtsam#1608]
Hello. Look here: https://github.com/borglab/gtsam/blob/d808d27507250a46cc9e5973294ec0f11ca9da82/doc/CMakeLists.txt#L59

This refers to `GTSAM_BUILD_EXAMPLES`. There are no other references to this. Did you mean `GTSAM_BUILD_EXAMPLES_ALWAYS`?

**Comment by ProfFan** [comment]
Yes, I think this needs to be fixed :)
