### ISSUE TITLE
PCL let GTSAM crash. 

### ISSUE THREAD

**Issue by lyliss** [borglab/gtsam#1612]
When gtsam and pcl are linked together in the cpp file, invoking isam2.update(graph, initial) results in a program crash with the error message "interrupted by signal 11: SIGSEGV"

**Comment by lyliss** [comment]
now I try it on other pc, error message changed to double free or corruption (out), if mask pcl code, the cpp is runing normally

**Comment by chxyfishge** [comment]
I have the same question，and I soved it. Let me explain my situation, maybe it would be helpful. 
Ubuntu 20.04 provided **PCL 1.10.0 in /usr/add and/usr/lib**, but I compiled another **PCL 1.10.0 and installed it in/usr/local/**. The conflict between these two PCLs resulted in 
`double free or corruption (out),`
**All we need to do is uninstall the compiled PCL.**
