### ISSUE TITLE
PyPI wheels for Python 3.11 on Linux

### ISSUE THREAD

**Issue by wbthomason** [borglab/gtsam#1643]
Similar to #1122, would it be possible to upload wheels for `manylinux` and Python 3.11? As well, could you add a `sdist` archive to support builds for other version/OS combinations?

**Comment by varunagrawal** [comment]
@dellaert looks like linux 3.11 is the only wheel not uploaded despite being successfully built. We should try resolving this since it is a quick thing.

**Comment by varunagrawal** [comment]
@wbthomason we have uploaded Linux wheels for Python 3.11. https://pypi.org/project/gtsam/#files
Thank you for pushing us into action.

I am closing this for now. If you have any issues, please re-open this.

**Comment by wbthomason** [comment]
Thank you very much!
