### ISSUE TITLE
Conda-forge win-64 package appears to be broken

### ISSUE THREAD

**Issue by sadsimulation** [borglab/gtsam#1657]
## Description

It seems like the conda-forge package for gtsam is currently broken for win-64.
The environment setup completes successfully, however the `gtsam` package can not be imported by Python.

## Steps to reproduce

1. `conda create -c conda-forge -n slam python=3.10 gtsam=4.2.0`
2. `conda activate slam`
```
(slam) C:\conda_envs>python
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:34:57) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gtsam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gtsam'
>>>
```

## Expected behavior

`gtsam` can be imported.

## Environment

OS: Win10 64-bit, Python 3.10, gtsam 4.2.0 from conda-forge.

**Comment by ProfFan** [comment]
I think this should be reported to conda-forge, they have some patches that are not upstreamed I believe

**Comment by sadsimulation** [comment]
I have reported this to conda-forge/gtsam-feedstock/issues/10, this issue seems to have persisted for over a year now.
Python bindings on my Linux machine seem to work fine.
