### ISSUE TITLE
In python, custom factor without Jacobian

### ISSUE THREAD

**Issue by goodgoodliving** [borglab/gtsam#1662]
> You create a custom function that computes `z-f(x)`. Then, in the `evaluateError` function of your customized factor, you can call the `numericalDerivative` function to compute the Jacobian numerically. Examples in `testNumericalDerivative.cpp` will help you get familiar with the function. 

@yetongumich 
Hello, may I ask if it's possible to automatically solve for the Jacobian using GTSAM if I'm implementing a custom factor in Python, where I only know the error function and am not familiar with how to perform the Jacobian calculation? Are there relevant interfaces for this in GTSAM?

_Originally posted by @goodgoodliving in https://github.com/borglab/gtsam/issues/1547#issuecomment-1782173621_

**Comment by chrisflesher** [comment]
There are several auto-diff libraries that can do this (e.g. autograd, JAX, SymPy, MyGrad, etc.).

I'm currently using JAX like this:
```
def measurement_residual(
        measurements: onp.ndarray,
        quaternions: onp.ndarray,
        relative_times: onp.ndarray,
        this: gtsam.CustomFactor,
        values: gtsam.Values,
        jacobians: typing.Optional[typing.List[onp.ndarray]],
        ) -> onp.ndarray:
    keys = this.keys()
    xi = values.atPose3(keys[0])
    vi = values.atVector(keys[1])
    vf = values.atVector(keys[2])
    xe_bi = onp.array([0., 0., 0., 0., 0., 0.])
    q_n_bi = xi.rotation().toQuaternion().coeffs()
    q_bi_b = quaternions
    predict_measurement = functools.partial(jax.jit(_predict_measurement), xe_bi, vi, vf, q_n_bi)
    predicted_measurements = [predict_measurement(q_bi_b[i], relative_times[i]) for i in range(relative_times.size)]
    if jacobians is not None:
        predict_jacobian = functools.partial(jax.jit(_predict_jacobian), xe_bi, vi, vf, q_n_bi)
        predicted_jacobians = [predict_jacobian(q_bi_b[i], relative_times[i]) for i in range(relative_times.size)]
        jacobians[0] = onp.stack([x[0] for x in predicted_jacobians])
        jacobians[1] = onp.stack([x[1] for x in predicted_jacobians])
        jacobians[2] = onp.stack([x[2] for x in predicted_jacobians])
    errors = (onp.array(predicted_measurements) - measurements)[:, onp.newaxis]
    return errors


def _predict_measurement(xe_bi, vi, vf, q_n_bi, q_bi_b, relative_time):
    re_bi = jax_scipy_spatial.transform.Rotation.from_rotvec(xe_bi[0:3])
    r_n_bi = jax_scipy_spatial.transform.Rotation.from_quat(q_n_bi) * re_bi
    r_bi_b = jax_scipy_spatial.transform.Rotation.from_quat(q_bi_b)
    r_n_b = r_n_bi * r_bi_b
    v_n = vi + relative_time * (vf - vi)
    v_b = r_n_b.inv().apply(v_n)
    return v_b


_predict_jacobian = jax.jacrev(_predict_measurement, argnums=[0, 1, 2])
```

**Comment by varunagrawal** [comment]
You need the Jacobians for linearizing the factor, but if `numericalDerivative` (aka finite differences) is not sufficient for your needs, @chrisflesher's comment about using Jax is really helpful.

Also since this is not quite a code issue, I highly recommend asking this question on the Google Group.
