### ISSUE TITLE
A small bug in gtsam/examples

### ISSUE THREAD

**Issue by zigfried-bit** [borglab/gtsam#1666]
Hi, I am new to GTSAM.

Path: [gtsam/examples/PlanarSLAMExample.cpp](https://github.com/borglab/gtsam/blob/develop/examples/PlanarSLAMExample.cpp)
Line44: `#include <gtsam/sam/BearingRangeFactor.h>`
`sam` should be `slam`

**Comment by varunagrawal** [comment]
This is not a bug since `BearingRangeFactor.h` is located inside `gtsam/sam` and the deprecated version is located in `gtsam/slam`.

**Comment by varunagrawal** [comment]
As a note, The `sam` directory contains code related to Smoothing And Mapping (aka SAM), hence the naming.
