### ISSUE TITLE
Possibly incorrect discretization of IMU noise

### ISSUE THREAD

**Issue by mnissov** [borglab/gtsam#1668]
## Description
Sorry if this is a false alarm, but I believe the noise discretization and parameter naming are slightly misleading and/or incorrect in the `CombinedImuFactor.cpp`. Below I detail why I believe this to be the case.

In line 141 of `CombinedImuFactor.cpp`:
```
  // first order uncertainty propagation
  // Optimized matrix mult: (1/dt) * G * measurementCovariance * G.transpose()
```
Already here the comment is not correct, the first order approximation of discrete noise propagation should be

$$Q_d = G Q G^\top  \Delta T$$

where $Q$ and $Q_d$ are the diagonal matrices of the spectral density (continuous noise power) and covariance (discrete), according to [1, sec 2.5.2], [3, eq. 4.111], [4, eq. 3.45], [5, eq. 25]. I tried to reference the same sources as `doc/ImuFactor.pdf`, but Simon in [2] doesn't seem to provide system definitions which include a noise input matrix (G), therefore I defaulted to what I believe are standard aided inertial navigation texts.

I'm assuming `measurementCovariance` is referring to the PSD, given that `PreintegrationParams.h` and `PreintegratedRotation.h` contain the following comments
```
  Matrix3 accelerometerCovariance; ///< continuous-time "Covariance" of accelerometer
  Matrix3 integrationCovariance; ///< continuous-time "Covariance" describing integration uncertainty
...
  Matrix3 gyroscopeCovariance;  ///< continuous-time "Covariance" of gyroscope measurements
```
If these values do actually correspond to PSD then I think the following operation (and the others like it) don't seem to make sense
```
  const Matrix3& aCov = p().accelerometerCovariance;
  const Matrix3& wCov = p().gyroscopeCovariance;
...
D_R_R(&G_measCov_Gt) =
      (theta_H_biasOmega * (wCov / dt) * theta_H_biasOmega.transpose()) ...
```
as dividing `wCov` with `dt` essentially performs the "conversion" to the equivalent covariance from PSD, following [1, eq. 129] and [4, eq. 14.83]. I'm not aware of how this first order discretization should look if the uncertainty is already discretized, so perhaps this is my misunderstanding.

In short, it looks like there is some discrepancy between what is implemented and a first order approximation for the discretization of covariance propagation. Looking more like individual PSDs are converted to covariances and then pre/post multiplied by the noise input matrix. I'm curious to hear your thoughts on this, if I am indeed correct the suggested fix should be simple assuming all noise values are in fact PSDs and not covariances.

## References
[1] Nikolas Trawny and Stergios I. Roumeliotis. Indirect kalman filter for 3 d attitude estimation. 2005.
[2] Dan Simon. Optimal state estimation: Kalman, H infinity, and nonlinear approaches. John Wiley & Sons, 2006.
[3] Jay Farrell. Aided Navigation: GPS with High Rate Sensors (1st. ed.). McGraw-Hill, Inc., 2008.
[4] Paul Groves, Principles of GNSS, Inertial, and Multisensor Integrated Navigation Systems, Second Edition, Artech, 2013.
[5] Janosch Nikolic. Characterisation, calibration, and design of visual-inertial sensor systems for robot navigation. PhD thesis, ETH Zurich, 2016.

**Comment by varunagrawal** [comment]
I believe the confusion is arising from the fact that you are using $Q$ and $Q_d$ to represent the process noise covariance (not the PSD which is related to the autocorrelation), while our math is using $Q$ to represent the measurement noise.

In `ImuFactor.pdf` if you look at the definition of $F$, you will see that there is appropriate scaling by $\Delta t$ where applicable. Hope that makes sense?

**Comment by varunagrawal** [comment]
Closing this issue for now. If this issue is still relevant after the above discussion, please feel free to reopen.

**Comment by mnissov** [comment]
Sorry for the delay. I think you're right, I see the misunderstanding.
