### ISSUE TITLE
Jacobian calculate in Pose3 translation function is correct?

### ISSUE THREAD

**Issue by Little99lantern** [borglab/gtsam#1699]
the file is geometry/Pose3.cpp
according to the code. I think Lie Group with Vectot6 is omega(3 dimensions) and translation(3 dimensions) 
sou why the jacobian is not  Z_3x3, I_3x3 ??
is there anything wrong with me?
need help thanks
```
/* ************************************************************************* */
const Point3& Pose3::translation(OptionalJacobian<3, 6> Hself) const {
  if (Hself) *Hself << Z_3x3, rotation().matrix();
  return t_;
}
```

**Comment by varunagrawal** [comment]
The `translation` function is defined as $f: \mathbb{R}^6 \rightarrow \mathbb{R}^3$, which is why the Jacobian has to be 3x6.

**Comment by Little99lantern** [comment]
thanks for your attention. 
yep, I know that is 3x6. I mean it should be  (Z_3x3, I_3x3) but not (Z_3x3, rotation().matrix())

**Comment by varunagrawal** [comment]
That's because translations are represented in the rotated coordinate frame for a pose $t_W = R^W_B * t_B$. A look at a textbook on robotic pose configuration (e.g. Murray & Sastry) should help with this understanding.

**Comment by Little99lantern** [comment]
thank you very much. I got it.
By the way, happy new year.
