### ISSUE TITLE
Cephes requires Cmake 3.12, breaks build on Ubuntu Bionic

### ISSUE THREAD

**Issue by berndpfrommer** [borglab/gtsam#1710]
The nightly Ubuntu Bionic builds break because the newly-added cephes library requires CMake 3.12 or higher
```
-- Found Eigen version: 3.3.4
CMake Error at gtsam/3rdparty/cephes/CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.12 or higher is required.  You are running version 3.10.2
```
Options:
1) Drop support for Ubuntu Bionic
2) Change required cmake version for libcephes to 3.10. I can build it locally on my machine without encountering errors. It is likely that libcephes does not rely on any features introduced between 3.10 and 3.12

**Comment by varunagrawal** [comment]
Fixed by #1711. Closing, thanks @berndpfrommer
