### ISSUE TITLE
ImportError in case of custom build of python package

### ISSUE THREAD

**Issue by Mikhail2017** [borglab/gtsam#1724]
Hi. I'm building a python package according to the instruction
https://github.com/borglab/gtsam/blob/develop/python/README.md
, but when I import a package like
`from gtsam import gtsam, utils`
it produces error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mika/.local/lib/python3.11/site-packages/gtsam/__init__.py", line 9, in <module>
    from gtsam import gtsam, utils
ImportError: /home/mika/.local/lib/python3.11/site-packages/gtsam/gtsam.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZTIN5gtsam11TableFactorE
```

Similar error is triggered in case of earlier versions too.
Strange, but I didn't face this issue in case of installing prebuilt package using pip.

gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
cmake version 3.19.0-rc1
Python 3.11.5

**Comment by ProfFan** [comment]
Are you absolutely sure that you do not have a second copy of GTSAM libraries installed? Sees like one

**Comment by Mikhail2017** [comment]
Thanks. It was a reason.
