### ISSUE TITLE
Question about symbolic computation: About addExpressionFactor

### ISSUE THREAD

**Issue by Zkjoker** [borglab/gtsam#1725]
I am performing a symbolic computation, and one of the steps involves extracting the third column from a rotation matrix. The subsequent calculations are based on this third column. Could you please help me check if the code is correct?

inline Point3 SymR3(const Rot3& rot, OptionalJacobian<3, 3> H) 
{
  if(H) *H = I_3x3;
  return rot.r3();
}

inline Vector3_ ForwardDirection(const Pose3_& pose)
{
  Rot3_ rot = Rot3_(&Pose3::rotation, pose);
  Vector3_ z_direction = Point3_(&SymR3,rot);
  return z_direction;
}

But I found that using this ForwardDirection function for symbolic computation seems to always yield inaccurate results. Please help me check if there is any issue, thank you.

**Comment by ProfFan** [comment]
Hi, do you mean the result OR the Jacobian is inaccurate?
