### ISSUE TITLE
VectorValues::vector() doesn't sort by key when GTSAM_WITH_TBB is ON

### ISSUE THREAD

**Issue by arutkowski** [borglab/gtsam#1731]
## Description

Without TBB, the function `VectorValues::vector()` sorts the output by key to form a `Vector`, regardless of the order in which the keys were inserted. When TBB is ON, this sorting doesn't happen.

For my use case, it is desirable to assume the `Vector` is ordered to make it more convenient to interface with another library built on Eigen without having to separately keep track of the ordering.

## Steps to reproduce

```    
gtsam::VectorValues vv;
vv.insert(1,gtsam::Point2(10,9));
vv.insert(4,gtsam::Point2(8,7));
vv.insert(3,gtsam::Point2(6,5));
vv.insert(2,gtsam::Point2(4,3));
std::cout << "vv = " << vv << std::endl;
std::cout << "vv.vector() = " << vv.vector().transpose() << std::endl;
```

## Expected behavior

Here's the output that I expect, which is what I get without TBB:
```
vv =   1: 10  9
  2: 4 3
  3: 6 5
  4: 8 7

vv.vector() = 10  9  4  3  6  5  8  7
```
With TBB, it looks like this (vv is correct, but vv.vector() is not ordered by key):
```
vv =   1: 10  9
  2: 4 3
  3: 6 5
  4: 8 7

vv.vector() =  8  7  4  3 10  9  6  5
```
## Environment

OS: Ubuntu 22.04
compiler: GCC 11.4.0
GTSAM_WITH_TBB: ON

## Additional information

It looks like the `for` loop was modified to get rid of `map_values` (and remove some more Boost stuff), which you can see in [this commit](https://github.com/borglab/gtsam/pull/1410/commits/4b40e6e34632ba199602d4b4c11fc372c2b3aabd). I didn't check if the previous code preserved the ordering by key when TBB is ON.

**Comment by dellaert** [comment]
Hmmm, yeah.
I have no objection to sorting. You could use the code from operator<<:

```c++
GTSAM_EXPORT std::ostream& operator<<(std::ostream& os, const VectorValues& v) {
    // Change print depending on whether we are using TBB
#ifdef GTSAM_USE_TBB
    std::map<Key, Vector> sorted;
    for (const auto& [key, value] : v) {
      sorted.emplace(key, value);
    }
    for (const auto& [key, value] : sorted)
#else
    for (const auto& [key,value] : v)
#endif
    {
      os << "  " << StreamedKey(key) << ": " << value.transpose() << "\n";
    }
    return os;
  }
```

Maybe even create a method `sorted` so we don't copy/paste that code.

Happy to review a PR to that effect.
