### ISSUE TITLE
Line cylinder factor

### ISSUE THREAD

**Issue by pie-leroy** [borglab/gtsam#1732]
Hello,

I'm working in python and I'm looking to model lines. For each image (front-end) I receive I detect poles which I model by a cylinder and I would like to use the axis of the cylinder as a landmark in gtsam.

I'm currently planning to project two Point3s for each axis, one at ground level and one at a fixed height.

Can you think of other ways?
Thanks

**Comment by dellaert** [comment]
Research question. You could ask this question on https://groups.google.com/g/gtsam-users
There is a Line3.h file, and I think we did something with it at one point but I forget...
Closing as not a GTSAM issue.
