### ISSUE TITLE
terminate called after throwing an instance of 'gtsam::ValuesKeyDoesNotExist'

### ISSUE THREAD

**Issue by JACKLiuDay** [borglab/gtsam#1746]
Hi, thank you for your great work about gtsam. I tried to use FixedLagSmootherExample.cpp for my own project. But it shows error after I run my ros bag.  My gtsam is 4.0.3.
![image](https://github.com/borglab/gtsam/assets/30967867/7d1841e9-c82b-42b7-b526-a8ce8c5c89bd)
I set the lag to be 2s. But when the factor size runs to 2.x s, the program dies.

**Comment by JACKLiuDay** [comment]
I just found something wrong with my code. If I use latestState = smootherBatch->calculateEstimate<Pose3>(currentKey);, the program runs without error. If I use latestState = smootherBatch->calculateEstimate(); there will be error gtsam::ValuesKeyDoseNotExist.
````
            fixsmoother->update(swGraph, swValues, newTimestamps);                                      // isam 更新状态
            // smootherBatch->update(swGraph, swValues, newTimestamps);
            for(size_t i = 1; i < 2; ++i)
            {
                fixsmoother->update();
            }

            pcl::PointXYZI thisPose3D;
            PointTypePose thisPose6D;
            Pose3 latestState;

            newTimestamps.clear();                                                                         
            swValues.clear();
            swGraph.resize(0);

            latestState = fixsmoother->calculateEstimate<Pose3>(currentKey);
            // latestState = fixsmoother->calculateEstimate<>();                                        // wrong!!!

**Comment by zzodo** [comment]
Hi,
Did you solved this issue?

I just wonder maybe you made some mistakes using the keys and symbols. (Sorry if it isn't) Other users can help you only if you provide the minimal reproducing code examples. :D

My guess is that you are using the variable `currentKey` as a `gtsam::Key`, not a symbol.
If then, try with `X(currentKey)` with the symbol shorthand.
