### ISSUE TITLE
typo in PreintegrationBase.cpp?

### ISSUE THREAD

**Issue by VRichardJP** [borglab/gtsam#1747]
Hello 

I am not sure I understand what the whole function is doing, but that `H2 || H2` looks like a typo to me (`H1` and `H2` are `OptionalJacobian`):

https://github.com/borglab/gtsam/blob/4abef9248edc4c49943d8fd8a84c028deb486f4c/gtsam/navigation/PreintegrationBase.cpp#L130-L132

Is it supposed to be `H1 || H2`?

**Comment by ProfFan** [comment]
Indeed looks like a typo, do you want to make a PR to fix this?
