### ISSUE TITLE
ROS2 Jazzy binaries not using GTSAM_USE_SYSTEM_EIGEN=ON

### ISSUE THREAD

**Issue by matlabbe** [borglab/gtsam#1759]
## Description

Currently with `ros-jazzy-gtsam` package, if your code is also including Eigen from another package like PCL, there will be a compilation error when including gtsam headers like this:

```
/opt/ros/jazzy/include/gtsam/base/Vector.h:76:30: error: static assertion failed: Error: GTSAM was built against a different version of Eigen
   76 |     GTSAM_EIGEN_VERSION_MAJOR==EIGEN_MAJOR_VERSION,
      |                              ^
/opt/ros/jazzy/include/gtsam/base/Vector.h:76:30: note: the comparison reduces to '(3 == 4)'
```
GTSAM is built with internal eigen version 3.3.7, while the system eigen is 3.4.0 on Ubuntu 24.04.

It seems that this patch https://github.com/ros2-gbp/gtsam-release/commit/0158c16db756e2ccc4720a85877d6f966f40ebc9 setting `GTSAM_USE_SYSTEM_EIGEN=ON ` hasn't been applied to jazzy release branch, which is probably causing the current issue.

Some downstream ros2 package(s) using gtsam failing: https://build.ros2.org/job/Jbin_uN64__gtsam__ubuntu_noble_amd64__binary/

**Comment by ProfFan** [comment]
Oh this is bad, pinging @jlblancoc for ROS2 stuff

**Comment by jlblancoc** [comment]
oh! thanks for bringing this up. 

It seems each new ROS release requires adding a new debian/patch branch to the gbp release repo. I'll do it.

**Comment by jlblancoc** [comment]
This should be fixed after https://github.com/ros/rosdistro/pull/41495 is merged, and Jazzy goes over a release cycle. 

You could leave this one open until it's verified that downstream packages are fixed.

**Comment by matlabbe** [comment]
Downstream looks good now: https://build.ros2.org/job/Jbin_uN64__gtsam__ubuntu_noble_amd64__binary/

Thanks!

**Comment by matlabbe** [comment]
I am sorry to re-open this issue, but the same fix would need to be applied also to rhel9 release on ros buildfarm. Downstream packages failing: https://build.ros2.org/job/Jbin_rhel_el964__gtsam__rhel_9_x86_64__binary/

FYI @marcoag

**Comment by jlblancoc** [comment]
@matlabbe I pushed a patch for RPM too: https://github.com/ros2-gbp/gtsam-release/commit/75ffb3dfcacb8f8b079f1bb965f7bb4366b01438 
Please, keep an eye on the [rosdistro PR](https://github.com/ros/rosdistro/pull/42200) and check if this change actually propagates to the build farm for rhel9.

**Comment by matlabbe** [comment]
Looks good now, thank you!
