### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by dolgae03** [borglab/gtsam#1767]
## Description
I followed all step introduced in INSTALL.md. However, it fails on cmake check. 

## Steps to reproduce

1.  Download Ubuntu 18.04 in Microsoft Store(WSL)
2.  git clone develop branch
3. `cd gtsam`
4. change mirror server to mirror.kakao.com
5. `sudo apt-get update`
6. `sudo apt-get install libboost-all-dev`
7. `sudo apt-get install cmake`
8. `sudo apt-get install libtbb-dev`
9. Follow installation Steps.

## Expected behavior

I tried to execute simplerotation example. However, while compiling it, It makes errors.

## Environment

OS : Unbuntu 
Language: C++
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
BOOST: 1.65.1.0ubuntu1

## Additional information
[tmux-buffer.txt](https://github.com/user-attachments/files/15942475/tmux-buffer.txt)

**Comment by ProfFan** [comment]
It seems that your GCC has bugs, which is expected because Ubuntu 18.04 is EOL in 2023, you should upgrade.
