### ISSUE TITLE
Numpy 2.0 arrays cause segfaults in many GTSAM constructors

### ISSUE THREAD

**Issue by meboler-snl** [borglab/gtsam#1771]
## Description

Passing a numpy 2.0 array into a GTSAM constructor will result in a segfault and a kernel crash.

## Steps to reproduce
```python
import gtsam
import numpy as np

mat = np.identity(3)
R = gtsam.Rot3(mat)

```

## Expected behavior

Successful construction of an object.

## Environment

Ubuntu 22.04
Python 3.10
GTSAM 4.2 (installed via pypi/pip)
Numpy 2.0 (installed via pypi/pip)

**Comment by meboler-snl** [comment]
![image](https://github.com/borglab/gtsam/assets/139389828/68794ea1-2c07-425b-90e7-3d889fb782c5)

**Comment by ProfFan** [comment]
Need upgrade to latest pybind11

**Comment by ProfFan** [comment]
Done in #1773, please test latest master and report back if you have other problems :)
