### ISSUE TITLE
Cannot build with msvc and C++20

### ISSUE THREAD

**Issue by asmei1** [borglab/gtsam#1788]
## Description

I'm trying to build GTSAM library using conan 1.62.0 using C++20. Compilation fails on `gtsam/base/chartTesting.h` file.
There is a function `testDefaultChart` used in `CHECK_CHART_CONCEPT` macro. 

To be more specific, compilation fails on `gtsam::DefaultChart<T>`. But what is weird for me that none of above types (function, macro, `gtsam::DefaultChart<T>` type) is not used anywhere.  The error was exactly the same as in [this comment](https://github.com/borglab/gtsam/pull/1502#issuecomment-1501315692).

When I remove this file, everything compiles. I think that this file is leftover after some cleaning and it should be removed in future

## Steps to reproduce

1. Build GTSAM with msvc, with C++20, build tools v143.

## Expected behavior

Successful build

## Environment
Gtsam (I tried 4.0.2, 4.0.3, 4.2)
Windows
MSVC; v143
C++20
conan 1.62.0
cmake 3.27.1

**Comment by adam-brz** [comment]
I've also stumbled upon this issue. It would be nice to further investigate this.
