### ISSUE TITLE
Local mapping 

### ISSUE THREAD

**Issue by jnaor** [borglab/gtsam#1794]
Hi,

What is the correct way to perform [Local Mapping](https://computersciencewiki.org/index.php/Local_mappinghttps://computersciencewiki.org/index.php/Local_mapping) using GTSAM? Can I do this using ISAM2 (i.e., to optimize only part of the graph, and leave the rest of it fixed), or should the local optimization be done in a batch on a local graph? Is there a publicly available example online?

Thanks,
Jonathan

**Comment by varunagrawal** [comment]
Hi Jonathan. I recommend asking this question on the Google Group, we have a lot of experienced users there who may be able to guide you better. Thanks!
