### ISSUE TITLE
It was found that the system would crash if there were more than 5000 nodes under Windows.

### ISSUE THREAD

**Issue by hunkyu** [borglab/gtsam#1826]
![image](https://github.com/user-attachments/assets/a9a05eda-3d8e-44eb-a3b0-a5603d53bee8)

**Comment by hunkyu** [comment]
Use the official demo

**Comment by ProfFan** [comment]
Please change your default stack size and report if that fix it?

**Comment by luyuanxunnuli** [comment]
> Please change your default stack size and report if that fix it?

Thank you for your reply. I have set the stack size of gtsam.dll and  programs which use gtsam.dll to 10M and 100M, but it crashes too.It is the same issue as #1827, #1827 is more detailed.

**Comment by ProfFan** [comment]
Many thanks @luyuanxunnuli ! I'll close this one as duplicate of #1827.

**Comment by hunkyu** [comment]
@ProfFan Setting the stack reserve size based on the VS software does not work
