### ISSUE TITLE
An unhandled exception occurred at 0xD3F1A9 (ntdll.dll) 

### ISSUE THREAD

**Issue by Qin-Yuan** [borglab/gtsam#1869]
## Description

After compiling GTSAM-develop with Win11+VS2022 and running the example program in the ISAM2Example_SmartFactor.cpp file in the example, the program can successfully run. However, when running the example program in my own project by using the find_package(GTSAM REQUIRED) command and target_link_libraries normally, the program generates the following error at the ISAM2Result result = isam.update(graph, initialEstimate) line in the code:
1. A breakpoint instruction has been executed in main.exe (__debugbreak() statement or similar call).
2. An unhandled exception occurred at 0xD3F1A9 (ntdll.dll) in main.exe: 0xC0000374: Stack has been corrupted. (Parameter: 0x03198B0).
Can you help me resolve this issue? Thank you very much.

## Environment
- windows 11
- Visual Studio 2022
- gtsam develop
- c++ 17
- ...

**Comment by varunagrawal** [comment]
Hi @Qin-Yuan. This does not seem to be a GTSAM code problem, so can you please ask this on the Google Group so others can help debug? Thanks.
