### ISSUE TITLE
Create new nodes and factor for matlab

### ISSUE THREAD

**Issue by ZhengCanlun** [borglab/gtsam#1873]
## Feature

I want to create a new factor in Matlab, with the estimate node consists of target position and velocity. How could I create a factor that correlated to the state? Since the exist factor including many unknown values, like 2960, 2961, 513... et.al.
![9b867eafd3be056d68098c495404cdf](https://github.com/user-attachments/assets/7c8e9d7e-0266-43d5-a4ec-7e0cb5e75847)

**Comment by varunagrawal** [comment]
Please ask this on the Google Group since that is the best place to receive support for questions like this.
