### ISSUE TITLE
Coordinate System Conversion Problem in IMUKittiExemplarGPS.cpp

### ISSUE THREAD

**Issue by HYD-PG** [borglab/gtsam#1882]
Hi！
When I am using my own data for data fusion, I am unable to confirm the carrier coordinate system and navigation coordinate system in IMUKittiExemplarGPS.cpp, which should involve its internal pre integration. So I want to know whether the navigation coordinate system in IMUKittiExemplarGPS.cpp is NED or ENU, which involves the direction of its carrier coordinate system, so that I can convert my own data.In the CPP program and MATLAB program for the same IMUKittiExemplarGPS, the images of the two show different angular orientations, and the CPP file appears to have been rotated 45 degrees based on this. The first image is a CPP file generated, and the second image is an official display on YouTube.（Version gtsam-develop）
![截图 2024-10-23 11-30-37](https://github.com/user-attachments/assets/3e69dbf2-2235-4694-8377-d9350a689d53)
![截图 2024-10-23 11-31-10](https://github.com/user-attachments/assets/d6d67551-6642-4c18-87f0-021678188a3a)

**Comment by Huang-Chuan** [comment]
@HYD-PG It should be ENU, as you can see in the code
`auto imu_params = PreintegratedImuMeasurements::Params::MakeSharedU(g);`

**Comment by ProfFan** [comment]
Closing since answer has been provided, thanks!
