### ISSUE TITLE
issue with copying gtsam objects in python

### ISSUE THREAD

**Issue by fatrybl** [borglab/gtsam#1931]
Hello, there is a problem with copying items in Python 3.11 and GTSAM API. 
Some objects can be copied and deepcopied successfully, some others - no. 

For example, gtsam.NonlinearFactorGraph() instance can be successfully copied.
<img src="https://github.com/user-attachments/assets/e4377021-b2b8-4f79-a2bd-5ea7f0dc99b8" width="500" >
<img src="https://github.com/user-attachments/assets/b54d6160-3a19-4a94-82e0-fca20ce370f1" width="500" >

whereas copying gtsam.PreintegratedCombinedMeasurements() instance  leads to errors in deepcopy module of Python.

<img src="https://github.com/user-attachments/assets/19f98d3f-12b0-47a1-bb49-a98e6e0d34de" width="500" >
<img src="https://github.com/user-attachments/assets/1f341f13-e3eb-493f-8c2c-5200f163ed41" width="500" >

as well as gtsam.PreintegratedImuMeasurements . **BUT** here is more interesting thing. If i create gtsam.NonlinearFactorGraph() instance, the gtsam.PreintegratedImuMeasurements() can be copied:
<img src="https://github.com/user-attachments/assets/d8a86e00-7b9b-4f34-8523-8d59155db8d6" width="500" >
<img src="https://github.com/user-attachments/assets/2899ae12-2ba8-42bd-850e-3e3054c185ce" width="500" >

and If i remove the creation of FactorGraph, the pim can not be copied anymore.
<img src="https://github.com/user-attachments/assets/dd528b43-8cb3-4766-9e0d-d4acd90dd7fc" width="500" >
<img src="https://github.com/user-attachments/assets/27749661-d124-4892-94af-aafd4aeea470" width="500" >

the same with  gtsam.PreintegrationParams: if gtsam.NonlinearFactorGraph() has been called before, params can be copied, otherwise - No. 

Also if one adds this IMU factor in NonlinearFactorGraph, the copying error occurs and it is not possible to copy the graph anymore. Meanwhile if one adds, for example, gtsam.PriorFactorPose3() to the graph, it can be copied successfully.

This issue is strange and maybe somehow connected with calling gtsam.NonlinearFactorGraph() before. However, for gtsam.PreintegratedCombinedMeasurements() instance the pre-calling of the graph still does not  allow to copy as "pickle error" occurs

this is clean python 3.11 and gtsam  4.2 installed with pip.

**Comment by ProfFan** [comment]
You just need to edit `navigation.i`:

```cxx

class PreintegratedCombinedMeasurements {
// Constructors
  PreintegratedCombinedMeasurements(const gtsam::PreintegrationCombinedParams* params);
  PreintegratedCombinedMeasurements(const gtsam::PreintegrationCombinedParams* params,
				    const gtsam::imuBias::ConstantBias& bias);
  // Testable
  void print(string s = "Preintegrated Measurements:") const;
  bool equals(const gtsam::PreintegratedCombinedMeasurements& expected,
      double tol);

  // Standard Interface
  void integrateMeasurement(gtsam::Vector measuredAcc, gtsam::Vector measuredOmega,
      double deltaT);
  void resetIntegration();
  void resetIntegrationAndSetBias(const gtsam::imuBias::ConstantBias& biasHat);

  gtsam::Matrix preintMeasCov() const;
  double deltaTij() const;
  gtsam::Rot3 deltaRij() const;
  gtsam::Vector deltaPij() const;
  gtsam::Vector deltaVij() const;
  gtsam::imuBias::ConstantBias biasHat() const;
  gtsam::Vector biasHatVector() const;
  gtsam::NavState predict(const gtsam::NavState& state_i,
      const gtsam::imuBias::ConstantBias& bias) const;

  // enabling serialization functionality
  void serialize() const;
};
```

**Comment by fatrybl** [comment]
@ProfFan,  the new line which is missing in the current implementation of navigation.i is : 
```
  // enabling serialization functionality
  void serialize() const;
```
right?
  then i copy-pasted  your full code  into gtsam/gtsam/navigation/navigation.i and freshly built with:
1. cmake .. -DGTSAM_BUILD_PYTHON=1 -DGTSAM_PYTHON_VERSION=3.11.10 -DCMAKE_INSTALL_PREFIX="./install" 
2. make check (tests passed)
3. make python-install
4. make python-tests (tests passed)
5. run my example with PreintegratedCombinedMeasurements from above and now it throws this error:

<img src="https://github.com/user-attachments/assets/da17120f-2928-43e7-81cf-fc2f6ea00904" width="300" >

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  pybind11::detail::instance::get_value_and_holder: `gtsam.gtsam.PreintegrationParams' is not a pybind11 base of the given `gtsam.gtsam.PreintegrationCombinedParams' instance

Process finished with exit code 134 (interrupted by signal 6:SIGABRT)
```

However, running the example with gtsam.PreintegratedImuMeasurements works fine now (without calling NonlinearFactroGraph() before). So the problem still exists only for Combined imu measurements instance.

P.s.
i`m not a c++ developer so can not fix it myself. I can only test the proposed solutions and fix python code.

**Comment by fatrybl** [comment]
and few more examples:

Params and pim objects can be successfully copied while ImuFactor() can not.

<img src="https://github.com/user-attachments/assets/da8ae570-f151-4267-b6c6-38f219538fc1" width="350" >
<img src="https://github.com/user-attachments/assets/c8426838-e6ad-4686-8952-e91577b5660a" width="350" >

as well as graph with ImuFactor can not be copied (but with different error) :

<img src="https://github.com/user-attachments/assets/97c6a10b-840a-419c-babc-73a0d28a8c69" width="350" >
<img src="https://github.com/user-attachments/assets/36a1f9c5-5f89-4dc0-9150-5188d4ea122d" width="350" >

**Comment by varunagrawal** [comment]
@fatrybl 2 things:

1. You are declaring the params incorrectly. They accept a 3d vector aka `np.asarray([0, 0, -9.81])`.
2. Please copy the code here rather than use screenshots? It makes it easier to try and reproduce the issue.

**Comment by fatrybl** [comment]
@varunagrawal, I built the project using the changes to navigation.i from this [PR](https://github.com/borglab/gtsam/pull/1939)
and ran my examples:
1) Now i`m able to deepcopy pim and params (as in your unit tests in the PR).
2) Still not able to copy ImuFactor or CombinedImuFactor --> can not copy the graph with these factors. The errors are the same as in screenshots above.

However, copying other factors (i.e. PriorFactorPose3) and the graph with them works well:

```
from copy import deepcopy
import gtsam.noiseModel
import numpy as np
from gtsam.symbol_shorthand import B, V, X

noise = gtsam.noiseModel.Isotropic.Sigma(6, 1)
prior = gtsam.PriorFactorPose3(X(0), gtsam.Pose3(), noise)

graph = gtsam.NonlinearFactorGraph()
graph.push_back(prior)

prior_copy = deepcopy(prior)
graph_copy = deepcopy(graph)
```

However, to reproduce copy error:
```
from copy import deepcopy
import gtsam.noiseModel
import numpy as np
from gtsam.symbol_shorthand import B, V, X

params = gtsam.PreintegrationParams(np.asarray([0, 0, -9.81]))
pim = gtsam.PreintegratedImuMeasurements(params)
imu_odom = gtsam.ImuFactor(X(0), V(0), X(1), V(1), B(0), pim)

imu_odom_copy = deepcopy(imu_odom)
```
```
Traceback (most recent call last):
  File "/home/mark/Desktop/PhD/ModuSLAM/phd/test.py", line 11, in <module>
    imu_odom_copy = deepcopy(imu_odom)
                    ^^^^^^^^^^^^^^^^^^
  File "/home/mark/miniconda3/envs/moduslam/lib/python3.11/copy.py", line 161, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle 'gtsam.gtsam.ImuFactor' object
```

P.s.
I used lists and tuples for gravity and other input params for gtsam-based objects (not np.array vectors) cause it worked fine all the times and did not influence computations. It seemed to me that gtsam is converting inputs to vectors itself. But Thank you for mentioning this, i`ll convert explicitly all inputs if it is a necessary requirement.

**Comment by varunagrawal** [comment]
So it seems that the wrapper we use around Pybind11 doesn't support deep copy yet ([Pybind11 DeepCopy](https://pybind11.readthedocs.io/en/stable/advanced/classes.html#deepcopy-support)).

Unfortunately, I cannot give you a timeline on when this feature will be added at the moment.

**Comment by varunagrawal** [comment]
Update: if the unit tests for #1939 pass, then the deep copy functionality should be good to go.

**Comment by fatrybl** [comment]
using the latest commits from the fix-pim-serialization branch with python 3.11 gives me the same error as in your pipeline for the unit test: test_ImuFactor (test_Serialization.TestDeepCopy)

**Comment by varunagrawal** [comment]
So I figured it out. The `PreintegratedImuMeasurements` object needs at least one `integrateMeasurement` call before it can be properly serialized. I have updated the test and will merge once CI passes.

**Comment by peci1** [comment]
More stuff that cannot be copied: ISAM2, ISAM2Params, LevenbergMarquardtParams...
