### ISSUE TITLE
TBB Deprecation Warnings

### ISSUE THREAD

**Issue by acxz** [borglab/gtsam#208]
## Description

TBB has been updated and now when building gtsam the build output is cluttered with deprecation warnings.
```
[ 42%] Building CXX object gtsam/CMakeFiles/gtsam.dir/symbolic/SymbolicEliminationTree.cpp.o
In file included from /home/acxz/vcs/git/github/acxz/gtsam/gtsam/base/treeTraversal/parallelTraversalTasks.h:25,
                 from /home/acxz/vcs/git/github/acxz/gtsam/gtsam/base/treeTraversal-inst.h:19,
                 from /home/acxz/vcs/git/github/acxz/gtsam/gtsam/inference/EliminationTree-inst.h:25,
                 from /home/acxz/vcs/git/github/acxz/gtsam/gtsam/symbolic/SymbolicEliminationTree.cpp:19:
/usr/include/tbb/task.h:21:139: note: #pragma message: TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.
   21 | #pragma message("TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
      |                                                                                                                                           ^
```

## Steps to reproduce

1. git clone https://github.com/borglab/gtsam
2. mkdir build && cd build && cmake .. && make

## Expected behavior

No TBB deprecation warnings.

## Environment

OS: ArchLinux
GTSAM version: latest `develop` branch (https://github.com/borglab/gtsam/commit/7ebfdadb2840949baac5d3b096459c5168d73d00) at time of posting
TBB version: 2020.2

## Additional information

Some helpful information on fixing this issue: https://github.com/oneapi-src/oneTBB/issues/243

**Comment by acxz** [comment]
Focal Fossa (the latest LTS version of Ubuntu) will be released on Apr 23rd [see](https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule)

The TBB version it will ship with is 2020.1 [see](https://packages.ubuntu.com/focal/libtbb2)
This will cause warnings that showed up in other distros like Arch to show up in Ubuntu.

If #209 still requires a longer time to review, can we bandaid the issue by suppressing the TBB warnings in the GTSAM code.

**Comment by ruffsl** [comment]
These deprecation warnings are getting spamy in my Ubuntu 20.04 build logs. It'd be nice to see #209 merged so we don't have to monkey patch other cmake projects that have drowned out warnings.

**Comment by dellaert** [comment]
> These deprecation warnings are getting spamy in my Ubuntu 20.04 build logs. It'd be nice to see #209 merged so we don't have to monkey patch other cmake projects that have drowned out warnings.

@ruffsl can you confirm #209 works for you as expected, and both TBB and non-TBB compile and run as expected?

**Comment by acxz** [comment]
@ruffsl the warnings up to TBB 2020.1 should be gone, there are still deprecation warnings with TBB 2020.2 that need to be addressed. Particularly the deprecation of `task.h` which affects quite a few classes and files in GTSAM.

**Comment by ruffsl** [comment]
Thanks @acxz , the downstream build logs are a quieter:

```
--- stderr: gtsam
/opt/ros/underlay_ws/src/borglab/gtsam/gtsam/3rdparty/CCOLAMD/Source/ccolamd.c: In function ‘ccolamd2’:
/opt/ros/underlay_ws/src/borglab/gtsam/gtsam/3rdparty/CCOLAMD/Source/ccolamd.c:1563:9: warning: variable ‘cs’ set but not used [-Wunused-but-set-variable]
 1563 |     Int cs ;
      |         ^~
---
```

Although, I only tested it with TBB enabled as thats what my project also needs to run.

**Comment by acxz** [comment]
Glad to hear that, that specific warning is due to CCOLAMD which is a 3rd party codebase.

**Comment by varunagrawal** [comment]
@acxz is this resolved?

**Comment by acxz** [comment]
Nope not yet. see #336 for a wip solution

**Comment by acxz** [comment]
Update:

Looks like intel released a better migration guide: https://docs.oneapi.com/versions/latest/onetbb/tbb_userguide/Migration_Guide/Task_API.html

Based on that I updated my attempt: https://github.com/acxz/gtsam/commit/825fe742528afce354778f9466a6bfbd8e65971f
Tests success has risen from 75% to 85% from my previous attempt. (Pardon the print statements)
