### ISSUE TITLE
hessian() doesn't work with constrained noise models

### ISSUE THREAD

**Issue by gchenfc** [borglab/gtsam#216]
## Description
Calling `graph.hessian()` on a graph with constrained factors throws error:

> TypeError: Incorrect arguments or types for method call.

## Steps to reproduce
please see
https://colab.research.google.com/drive/1NBO8vguh6TeWIwErY-2UiDDyI2yX5NrM

```python
A = np.eye(2)
b = np.zeros((2,))
x = gtsam.symbol(ord('x'), 0)

graph = gtsam.GaussianFactorGraph()
noise = gtsam.noiseModel_Constrained.All(2)
graph.add(x, A, b, noise)
print(graph.hessian())
```

## Expected behavior
Not sure, maybe something like
<pre>
[[ inf, 0],
 [ 0, inf]]
</pre>

## Environment

Python

## Additional information

Not clear what the expected behavior should be - will have to read code how GTSAM deals with constraints in the first place.

**Comment by varunagrawal** [comment]
This is in the docstring for `Constrained`:

```
* While a hard constraint may seem to be a case in which there is infinite error,
* we do not ever produce an error value of infinity to allow for constraints
* to actually be optimized rather than self-destructing if not initialized correctly.
```

Since constrained noise models can have certain sigmas be zero, calling `WhitenInPlace` on a constrained model will lead to numerical instability, so this is indeed expected behavior.
