### ISSUE TITLE
[RFC] Add GitHub Actions for CI

### ISSUE THREAD

**Issue by ProfFan** [borglab/gtsam#236]
Recently we have seen a number of CI failures in Travis CI as Travis is not allocating enough time or [not having enough memory](https://github.com/borglab/gtsam/runs/478262154) for GTSAM to build. This blocked some of our PRs.

So, I did a bit of experimenting on GitHub Actions, here are the results:

| Item  |  Travis  | GitHub Actions |
|------|--------|----------|
| Build time | 1h28m | 1h58m |
| (vs.) Test Matrix Size | 18 | 40 |
| Windows |  ❎ | ✅ |
| Linux | ✅ | ✅ |
| macOS | ✅ | ✅ |

Notably, no caching (`ccache`) is used currently with the GitHub Actions CI, so I expect build time to be further reduced if we implement caching. Also, we can reduce the size of the test matrix for non-PR builds, in my experiments if size=20 it can finish in 25 minutes.

My proposal is that we can implement both CI systems at the same time, and allow merging when any one CI passes so we do not get blocked by Travis timeouts.

An example of the current experiment results and setup can be seen at https://github.com/ProfFan/gtsam/actions

Pinging @dellaert @varunagrawal @jlblancoc for comments.

**Comment by varunagrawal** [comment]
I've seen a lot of positive reactions on Twitter for GitHub Actions so I fully support this proposal. Moreover, I would prefer to have a docker container prebuilt to be used for CI to save time over there (a lot of Travis errors are due to apt-get timeouts). The container template can also serve as a pseudo dependency guide for anyone wanting to install GTSAM from source or even play around with it.

**Comment by varunagrawal** [comment]
I've been playing around with workflows using Github Actions on a fork of GTSAM and I am not impressed with the overall feature set of Github Actions. Running a CI matrix is tedious and the setup stage (installing dependencies, setting env variables, etc) has been plenty painful.

@ProfFan I would love to see how you set up all the different jobs for the CI.

**Comment by ProfFan** [comment]
@varunagrawal https://github.com/ProfFan/gtsam/blob/feature/github_actions_ci/.github/workflows/build.yml

**Comment by ProfFan** [comment]
I am bringing this issue out again that:
1. The CI is fully working with Github Actions
2. No timeouts with Github Actions
3. Windows builds on Github actions is running smoothly

So I propose to remove AppVeyor and Travis (in the PyBind branch).

@dellaert @jlblancoc @varunagrawal For comments.

**Comment by dellaert** [comment]
sure :-)

**Comment by jlblancoc** [comment]
I was thinking of proposing you CircleCi to avoid the time outs, but if you have actions already set up and running... brilliant! LGTM

**Comment by varunagrawal** [comment]
Yes please! Whatever speeds up the CI pipeline (and you made excellent arguments for GitHub Actions). Minimizing the context switching should help with productivity immensely.

**Comment by varunagrawal** [comment]
We got this working!! :tada:
