### ISSUE TITLE
SymmetricBlockMatrix setzero problem.

### ISSUE THREAD

**Issue by shaolinbit** [borglab/gtsam#238]
In SymmetricBlockMatrix.h

/// Set the entire active matrix zero.
    void setZero() {
      full().triangularView<Eigen::Upper>().setZero();
    }

When matrix_.resize() is used in Hessian factor initialization, matrix_ may be not all zero since it may use a bulk of  dirty memory.
Maybe it should be written as follows.
   void setZero() {
      full() .setZero();
    }

**Comment by varunagrawal** [comment]
I don't think this is a bug, because even with an increase in rows and columns for the symmetric matrix, we only care about the upper triangular part for elimination. As long as that is set to 0, we should be fine.

I'll let @dellaert and @richardroberts chime in.

**Comment by varunagrawal** [comment]
Function in question is here https://github.com/borglab/gtsam/blob/develop/gtsam/base/SymmetricBlockMatrix.h#L263

**Comment by shaolinbit** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/8273582/76093690-6343b380-5ffc-11ea-9b2c-960c76ffc44d.jpg)
![327175025](https://user-images.githubusercontent.com/8273582/76093706-69399480-5ffc-11ea-9a7c-71679fffbe90.jpg)

Try this example. You will get the matrix results which is not zero after resize. Triangular set zero is no enough for some cases. 
/* ----------------------------------------------------------------------------

 * GTSAM Copyright 2010, Georgia Tech Research Corporation,
 * Atlanta, Georgia 30332-0415
 * All Rights Reserved
 * Authors: Frank Dellaert, et al. (see THANKS for the full author list)

 * See LICENSE for the license information

 * -------------------------------------------------------------------------- */

/**
 * @file RangeISAMExample_plaza1.cpp
 * @brief A 2D Range SLAM example
 * @date June 20, 2013
 * @author FRank Dellaert
 */

// Both relative poses and recovered trajectory poses will be stored as Pose2 objects
#include <gtsam/geometry/Pose2.h>

// Each variable in the system (poses and landmarks) must be identified with a unique key.
// We can either use simple integer keys (1, 2, 3, ...) or symbols (X1, X2, L1).
// Here we will use Symbols
#include <gtsam/inference/Symbol.h>

// We want to use iSAM2 to solve the range-SLAM problem incrementally
#include <gtsam/nonlinear/ISAM2.h>

// iSAM2 requires as input a set set of new factors to be added stored in a factor graph,
// and initial guesses for any new variables used in the added factors
#include <gtsam/nonlinear/NonlinearFactorGraph.h>
#include <gtsam/nonlinear/Values.h>

// We will use a non-liear solver to batch-inituialize from the first 150 frames
#include <gtsam/nonlinear/LevenbergMarquardtOptimizer.h>

// In GTSAM, measurement functions are represented as 'factors'. Several common factors
// have been provided with the library for solving robotics SLAM problems.
#include <gtsam/slam/PriorFactor.h>
#include <gtsam/slam/BetweenFactor.h>
#include <gtsam/sam/RangeFactor.h>
#include <gtsam/slam/dataset.h>

// Standard headers, added last, so we know headers above work on their own
#include <fstream>
#include <iostream>

using namespace std;
using namespace gtsam;
namespace NM = gtsam::noiseModel;

// data available at http://www.frc.ri.cmu.edu/projects/emergencyresponse/RangeData/
// Datafile format (from http://www.frc.ri.cmu.edu/projects/emergencyresponse/RangeData/log.html)

// load the odometry
// DR: Odometry Input (delta distance traveled and delta heading change)
//    Time (sec)  Delta Dist. Trav. (m) Delta Heading (rad)
typedef pair<double, Pose2> TimedOdometry;
list<TimedOdometry> readOdometry() {
  list<TimedOdometry> odometryList;
  string data_file = findExampleDataFile("Plaza2_DR.txt");
  ifstream is(data_file.c_str());

  while (is) {
    double t, distance_traveled, delta_heading;
    is >> t >> distance_traveled >> delta_heading;
    odometryList.push_back(
        TimedOdometry(t, Pose2(distance_traveled, 0, delta_heading)));
  }
  is.clear(); /* clears the end-of-file and error flags */
  return odometryList;
}

// load the ranges from TD
//    Time (sec)  Sender / Antenna ID Receiver Node ID  Range (m)
typedef std::tuple<double, size_t, double> RangeTriple;
vector<RangeTriple> readTriples() {
  vector<RangeTriple> triples;
  string data_file = findExampleDataFile("Plaza2_TD.txt");
  ifstream is(data_file.c_str());

  while (is) {
    double t, sender, range;
    double receiver;
    is >> t >> sender >> receiver >> range;
    triples.push_back(RangeTriple(t, receiver, range));
  }
  is.clear(); /* clears the end-of-file and error flags */
  return triples;
}

// main
int main (int argc, char** argv) {

  // load Plaza2 data
  list<TimedOdometry> odometry = readOdometry();
//  size_t M = odometry.size();

  vector<RangeTriple> triples = readTriples();
  size_t K = triples.size();

  // parameters
  size_t minK = 150; // minimum number of range measurements to process initially
  size_t incK = 25; // minimum number of range measurements to process after
  bool groundTruth = false;
  bool robust = true;

  // Set Noise parameters
  Vector priorSigmas = Vector3(1,1,M_PI);
  Vector odoSigmas = Vector3(0.05, 0.01, 0.2);
  double sigmaR = 100; // range standard deviation
  const NM::Base::shared_ptr // all same type
  priorNoise = NM::Diagonal::Sigmas(priorSigmas), //prior
  odoNoise = NM::Diagonal::Sigmas(odoSigmas), // odometry
  gaussian = NM::Isotropic::Sigma(1, sigmaR), // non-robust
  tukey = NM::Robust::Create(NM::mEstimator::Tukey::Create(15), gaussian), //robust
  rangeNoise = robust ? tukey : gaussian;

  // Initialize iSAM
  ISAM2 isam;

  // Add prior on first pose
  Pose2 pose0 = Pose2(-34.2086489999201, 45.3007639991120,
      M_PI - 2.02108900000000);
  NonlinearFactorGraph newFactors;
  newFactors.push_back(PriorFactor<Pose2>(symbol('P',0), pose0, priorNoise));
  Values initial;
  initial.insert(symbol('P',0), pose0);
  pose0.print();

  //  initialize points
  if (groundTruth) { // from TL file
    initial.insert(symbol('L', 1), Point2(-68.9265, 18.3778));
    initial.insert(symbol('L', 6), Point2(-37.5805, 69.2278));
    initial.insert(symbol('L', 0), Point2(-33.6205, 26.9678));
    initial.insert(symbol('L', 5), Point2(1.7095, -5.8122));
  } else { // drawn from sigma=1 Gaussian in matlab version
    initial.insert(symbol('L', 1), Point2(3.5784, 2.76944));
    initial.insert(symbol('L', 6), Point2(-1.34989, 3.03492));
    initial.insert(symbol('L', 0), Point2(0.725404, -0.0630549));
    initial.insert(symbol('L', 5), Point2(0.714743, -0.204966));
  }

  // set some loop variables
  size_t i = 1; // step counter
  size_t k = 0; // range measurement counter
  bool initialized = false;
  Pose2 lastPose = pose0;
  size_t countK = 0;

  // Loop over odometry
  gttic_(iSAM);
  for(const TimedOdometry& timedOdometry: odometry) {
    //--------------------------------- odometry loop -----------------------------------------
    double t;
    Pose2 odometry;
    boost::tie(t, odometry) = timedOdometry;
   // odometry.print();


    // add odometry factor
    newFactors.push_back(BetweenFactor<Pose2>(symbol('P',i-1), symbol('P',i), odometry,NM::Diagonal::Sigmas(odoSigmas)));

    // predict pose and add as initial estimate
    Pose2 predictedPose = lastPose.compose(odometry);
    lastPose = predictedPose;
    initial.insert(symbol('P',i), predictedPose);
   // predictedPose.print();


    //initial.print();
    // Check if there are range factors to be added
    while (k < K && t >= std::get<0>(triples[k])) {
      size_t j = std::get<1>(triples[k]);
      double range = std::get<2>(triples[k]);
      newFactors.push_back(RangeFactor<Pose2, Point2>(symbol('P',i), symbol('L', j), range,rangeNoise));
      k = k + 1;
      countK = countK + 1;
    }

    // Check whether to update iSAM 2
    //if ((k > minK) && (countK > incK))
    if (k > 5)
     {
      if (!initialized) { // Do a full optimize for first minK ranges
        gttic_(batchInitialization);
        LevenbergMarquardtOptimizer batchOptimizer(newFactors, initial);
        cout<<batchOptimizer.error()<<endl;
        initial = batchOptimizer.optimize();
        gttoc_(batchInitialization);
        initialized = true;
      }
      gttic_(update);
      isam.update(newFactors, initial);
      gttoc_(update);
      gttic_(calculateEstimate);
      Values result = isam.calculateEstimate();
      gttoc_(calculateEstimate);
      lastPose = result.at<Pose2>(i);
      newFactors = NonlinearFactorGraph();
      initial = Values();
      countK = 0;
    }
    i += 1;
    //--------------------------------- odometry loop -----------------------------------------
  } // end for
  gttoc_(iSAM);

  // Print timings
  tictoc_print_();

  exit(0);
}

**Comment by dellaert** [comment]
@shaolinbit it's a bit hard to see what you mean, sorry about that. How about adding a test in a fork in testSymmetricBlockMatrix.cpp that fails? You can do a PR with it or just paste a link to a 
 github gist with the test, and we'll look at it.

**Comment by shaolinbit** [comment]
When you use an Eigen resize function, you may get a matrix which may not be zero. The resize function allocate a memory bulk for the matrix, this bulk is not guaranteed zero. Thus,  if you only set half a part of the matrix to zero, the results are not right too. After setting zero,Rand 1 update will update the whole matrix which is not zero.  

   info_.setZero();
  for(const auto& factor: factors)
    if (factor)
      factor->updateHessian(keys_, &info_);
  gttoc(update);

**Comment by dellaert** [comment]
I know that you are worried about resize. But I don't see a resize in your code. I am looking for the specific gtsam use case that will yield a problem.

**Comment by shaolinbit** [comment]
In this current edition, Hessianfactor.cpp, Line 252.
/* ************************************************************************* */
HessianFactor::HessianFactor(const GaussianFactorGraph& factors,
    const Scatter& scatter) {
  gttic(HessianFactor_MergeConstructor);

  Allocate(scatter);

  // Form A' * A
  gttic(update);
  info_.setZero();
  for(const auto& factor: factors)
    if (factor)
      factor->updateHessian(keys_, &info_);
  gttoc(update);
}

**Comment by dellaert** [comment]
Great, that could be the problem. However, can you give me a *test* that fails? I.e., a unit test that calls this function (directly or indirectly) and exposes the problem?

**Comment by dellaert** [comment]
@shaolinbit What's the reason for closing? Did you realize it was not an issue?

**Comment by shaolinbit** [comment]
> @shaolinbit What's the reason for closing? Did you realize it was not an issue?

Sorry, U are right. This is not an issue. 
However, I tested the above example. It would collapse at CholeskyPartial. It is difficult for me to seek the origin of this bug. 
![1100985953](https://user-images.githubusercontent.com/8273582/76160628-a9b52180-6166-11ea-8f8c-eab89623e308.jpg)

**Comment by dellaert** [comment]
Thanks! Seems like you’re deep inside GTSAM. That’s non-obvious code :-)
If there is a bug you are encountering with GTSAM the best advice I can give you is to create a minimal failing unit test that calls GTSAM through the normal API, and share it with us.

**Comment by shaolinbit** [comment]
> Thanks! Seems like you’re deep inside GTSAM. That’s non-obvious code :-)
> If there is a bug you are encountering with GTSAM the best advice I can give you is to create a minimal failing unit test that calls GTSAM through the normal API, and share it with us.

I have spent two years in gtsam. Now I am trying to code a cuda version. I am not very familiar with github. 
Of course, I will report the bug if I encounter one.

**Comment by dellaert** [comment]
Awesome ! @dongjing3309 and @lvzhaoyang actually tried CUDA as a solver in MiniSAM, and it did not do a great job, performance-wise, if I recall correctly. It will require some thought :-) Easiest way is actually to replace the entire linear solver back-end, something @ProfFan and I are working to make possible (e.g, use SuiteSparse). If you'd like to chat/be involved, send me an email at frank@cc.gatech.edu and we can go from there.
