### ISSUE TITLE
Improved numerical stability for comparison of matrices and vectors

### ISSUE THREAD

**Issue by varunagrawal** [borglab/gtsam#244]
## Feature

Improve the numerical stability of comparison for matrices and vectors.
Reference: https://floating-point-gui.de/errors/comparison/

## Motivation

Currently, the comparison operation follows an older floating point comparison method which is unstable when the matrix/vector has both small and large values together. The larger values lose precision because of the smaller values and thus the comparison fails.

This is especially important since tests on calibration matrices with radial distortion can fail due to 
the instability.

## Pitch

Follow the correct floating point comparison method.

## Alternatives

It's an IEEE 754 standard, so no other option really.

**Comment by varunagrawal** [comment]
@dellaert @ProfFan I have a working implementation of this. Would you two have time to review this weekend?

**Comment by ProfFan** [comment]
I think I will give a shot.

**Comment by varunagrawal** [comment]
Fixed by #245
