### ISSUE TITLE
Tests fail when using Eigen::Transpose with quaternion representation

### ISSUE THREAD

**Issue by varunagrawal** [borglab/gtsam#253]
## Description

Various tests fail when using the Quaternion representation of rotations and the `transpose` return type is `const Eigen::Transpose<const Matrix3>`.
These same tests pass when using rotation matrices.

Specific test files are:

1. testImuFactor
2. testNavState
3. testScenario

## Steps to reproduce

1. Edit `Rot3*` files to return `Eigen::Transpose` for the return type of `transpose`.
2. Compile GTSAM with `GTSAM_USE_QUATERNIONS=ON` cmake flag.
3. Run tests.

## Expected behavior

All tests should pass indicating behavior similar to Rotation Matrices.

## Environment

Arch Linux with GCC 9.2.0.

**Comment by dellaert** [comment]
Is there not a Travis confit that checks the quarter ion setting? There should be, maybe add in “special” section.

**Comment by varunagrawal** [comment]
Linking an answer from StackOverflow that explains the issue really well

https://stackoverflow.com/questions/60749047/correct-way-to-use-eigentransposeconst-matrix3/60937475#60937475

**Comment by ProfFan** [comment]
IMHO this should be solved with either:
1. Just copy it.
2. Just copy it.

as we are calculating this value anyway :)

**Comment by dellaert** [comment]
Yes, let's just return a Matrix3 ? Is that not what is happening now? @varunagrawal close if you agree.

**Comment by varunagrawal** [comment]
Closing because this involves an unnecessary copy operation.
