### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by emma010165** [borglab/gtsam#278]
Hi everyone!
I got the the following build error:

[ 65%] Linking CXX executable Pose2SLAMExample_g2o
../gtsam/libgtsam.so.4.0.2: undefined reference to `boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::save(std::string const&)'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/Pose2SLAMExample_g2o.dir/build.make:105: recipe for target 'examples/Pose2SLAMExample_g2o' failed
make[2]: *** [examples/Pose2SLAMExample_g2o] Error 1
CMakeFiles/Makefile2:20919: recipe for target 'examples/CMakeFiles/Pose2SLAMExample_g2o.dir/all' failed
make[1]: *** [examples/CMakeFiles/Pose2SLAMExample_g2o.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

I am using Boost 1.65, gcc 4.8.5 and cmake 3.10.2.

Can someone help me solve this problem?
Thanks.

**Comment by varunagrawal** [comment]
What version of boost are you using?

**Comment by emma010165** [comment]
@varunagrawal I am using Boost version 1.65

**Comment by ProfFan** [comment]
@emma010165 Please attach all the relevant logs and the commands you have used to build GTSAM.

**Comment by emma010165** [comment]
Hi, I have changed my gcc version from 4.8 to a much newer one gcc 7 and it worked perfectly (same commands in readme for building GTSAM). Even though gcc4.8 is said to be supported for building gtsam, I don't really know why it didn't work for me. Thank you for your responses @profFan and @varunagrawal. I guess I'll close this issue.
