### ISSUE TITLE
Handling edgelet features 

### ISSUE THREAD

**Issue by kvmanohar22** [borglab/gtsam#286]
## Feature
Current implementation of bundle adjustment is limited to corner features. I am proposing for handling additional type of features i.e, edgelets.

## Motivation
Tracking pixels having any gradient as in semi-dense and dense approaches could make tracking more reliable in environments having little texture.

## Pitch
Implementing bundle adjustment for edgelet features could be a good start. This is proposed in [1], I am reposting the optimization function here
![image](https://user-images.githubusercontent.com/15105941/80868467-697ea500-8cb8-11ea-9404-693efea5a746.png)

The subtle change is to restrict reprojection error of edge features along the edge normal.

## Additional context
The usage of edgelet features is proposed in the following paper.

## References
[1] SVO: Semi-Direct Visual Odometry for Monocular and Multi-Camera Systems

**Comment by dellaert** [comment]
@akshay-krishnan

**Comment by dellaert** [comment]
Go for it ;-)

**Comment by dellaert** [comment]
Note, you can add a factor, but image processing and other front-end code is deliberately not included with GTSAM - which is focused on the back-end optimization. There are several line-based factors that might already be similar to what you want.

**Comment by varunagrawal** [comment]
@kvmanohar22 if you're still interested, we would love to have a PR for this feature. I am closing this issue for now since it is quite old.
