### ISSUE TITLE
Problem with Python wrapper: No module named 'gtsam.utils'

### ISSUE THREAD

**Issue by Study-is-happy** [borglab/gtsam#287]
First I turn on the GTSAM_INSTALL_CYTHON_TOOLBOX flag and turn off the GTSAM_ALLOW_DEPRECATED_SINCE_V4 flag in CMakeList.txt in gtsam home directory

Here is what I did:
cd gtsam
mkdir build
cd build
cmake ..
sudo make install
cd cython
sudo python setup.py install

But I failed to run any python examples, with error No module named 'gtsam.utils'
I can import gtsam but I cannot import any sub packages of gtsam

I am in virtualenv (actived) and Ubuntu 18.04

Thank you for providing and maintaining such an amazing library for SLAM!!!

**Comment by ProfFan** [comment]
Actually I think I encountered this problem when debugging in a Ubuntu 18.04 container. The simple solution is to go to the `build/cython/gtsam` folder, `ln -s $(pwd)/../../cython/gtsam/utils ./utils`, and run setup again.

**Comment by ProfFan** [comment]
Short explanation: it failed to create the symlink to `utils`, so you can manually create it.

**Comment by Study-is-happy** [comment]
> Short explanation: it failed to create the symlink to `utils`, so you can manually create it.

I linked utils, and I can see the red symlink in gtsam/build/cython/gtsam
![Screenshot from 2020-05-02 22-44-20](https://user-images.githubusercontent.com/38361616/80897432-84581600-8cc6-11ea-9c2b-5d3ecb095b30.png)

And I run setup again, still not working :(

**Comment by ProfFan** [comment]
Try `ls utils` and see if it's a broken symlink? Don't copy my command, the linked path should be in the source folder, a.k.a `<gtsam>/cython/gtsam/utils`.

**Comment by Study-is-happy** [comment]
> Try `ls utils` and see if it's a broken symlink? Don't copy my command, the linked path should be in the source folder, a.k.a `<gtsam>/cython/gtsam/utils`.

I correct the link path and the symlink is working now, it turned blue. But I setup again and still not working :(

**Comment by ProfFan** [comment]
@Study-is-happy do a cleanup by `pip uninstall gtsam` and do it again, if that still fails you can manually copy the contents of `utils` to the `site-packages/gtsam***` directory.

**Comment by dellaert** [comment]
Try it in a new conda environment, making sure to run install with the environment’s python.

**Comment by varunagrawal** [comment]
@Study-is-happy any updates on this?

We added a new `make python-install` command that should install everything for you (also cleaned up the cmake quite a bit).
Hopefully that works for you?

**Comment by ProfFan** [comment]
I kind of know what is the problem, he is probably importing the gtsam "folder" because he is running the examples under some folder with a subfolder called `gtsam`.

**Comment by dellaert** [comment]
Re-open if still an issue

**Comment by liuhj86** [comment]
-DGTSAM_WITH_TBB=OFF works for me. Just do everything from the very beginning.
