### ISSUE TITLE
Failed test on 32bit architectures

### ISSUE THREAD

**Issue by jlblancoc** [borglab/gtsam#306]
## Description

One unit test fails to pass in `armhf`

```
186/234 Test #186: testQPSolver ...........................***Failed    0.04 sec
Not equal:
expected:
4.371875
actual:
290687824935850081763694373348985159914898047944127280960733468936086603046127808004981004843733268589327788990324383899071870077623672891177494692327651468166411650774643726713810200573276388989574637258303295240952023116603342313435955200.000000
/<<PKGBUILDDIR>>/gtsam_unstable/linear/tests/testQPSolver.cpp:330: Failure: "assert_equal(0.437187500e01,error_actual, 1e-7)" 
There were 1 failures 
```

## Steps to reproduce

1. Build and run tests on architectures != amd64.

## Expected behavior

All unit tests should pass! :-)

## Environment

See build logs in:
https://launchpad.net/~joseluisblancoc/+archive/ubuntu/gtsam-develop/+packages

Note that right now, tests can't run for `ppc64el` and `arm64`, but errors there seem to be related to limited RAM in the builders instead.

**Comment by jlblancoc** [comment]
Progress: I traced this down to a problem parsing QPS files. 

For instance, in 64bit builds the file [examples/Data/QPTEST.QPS](https://github.com/borglab/gtsam/blob/develop/examples/Data/QPTEST.QPS) is correctly parsed as:
``` 
QPTEST.QPS: 
Quadratic cost factors: 
size: 1
factor 0: 
 keys: X1(1) X2(1) 
Augmented information matrix: [
	   8,    2, -1.5;
 	   2,   10,    2;
 	-1.5,    2,    0
]
...
```

while in i386 it's read as:
```
QPTEST.QPS 
Quadratic cost factors: 
size: 1
factor 0: 
keys: X1(1) X2(1) 
Augmented information matrix: [
     8,            2,         -1.5;
     2,           10,            2;
  -1.5,            2, **2.36234e+111**
]
...
```

I'm not familiar with the QPS file format... any pointers? :-)

**Comment by jlblancoc** [comment]
PS: it totally looks like an uninitialized vector somewhere, pretty much like those recently fixed by @ProfFan ...

**Comment by dellaert** [comment]
Valgrind say anything?

**Comment by dellaert** [comment]
@jlblancoc many many thanks for tracking this down !

**Comment by ProfFan** [comment]
Valgrind probably won't say anything here as this is the de factor behavior of Eigen... However I would guess it's where we initialize the Augmented information matrix. For example, a default constructor call/a "static" ( `Matrix3 xxx;` like) declaration of a matrix.

**Comment by jlblancoc** [comment]
This is fixed now, Yay! 
It was this tiny thing: b73f03646d4c682399ad6304b03ffa6645858088

Fixed by PR #310

**Comment by jlblancoc** [comment]
Reopening since the former proposed solution was actually a workaround, a better solution would be to fix the construction of the quadratic cost factor in the test referenced above.

**Comment by varunagrawal** [comment]
I'm seeing this issue on GCC compilers (Clang works fine) and a 64-bit architecture. I'd like to fix this before the weekend.

**Comment by ProfFan** [comment]
It's 100% UB... UBSan didn't report anything so I think you need to manually scan for it :)

**Comment by varunagrawal** [comment]
Here's some more info:

I tried commenting out the other tests so that I could isolate the issue better. Funnily enough, the test in question passes, when you comment out the other tests. I tracked down the culprit and it seems like the `CHECK` in `TEST(QPSolver, HS268)` is causing some weirdness, because if I only comment out that one line, everything works fine. Even on inspecting the Hessian factors, it is correctly initialized.

Any thoughts?

**Comment by varunagrawal** [comment]
Found the issue. It's the damn parser not reading the constant term correctly. _sigh_

**Comment by varunagrawal** [comment]
The fix is the dumbest thing: In `QPSVisitor` force `f = 0` by explicitly initializing it.

**Comment by varunagrawal** [comment]
@jlblancoc can you please test the fix in #607 on the arm builds?

PS a few PRs more and we could have had the fix in 306*2 = 612. :joy:

**Comment by varunagrawal** [comment]
@jlblancoc gentle reminder.

**Comment by jlblancoc** [comment]
copy that...

**Comment by jlblancoc** [comment]
Yay, [it's fixed](https://launchpad.net/~joseluisblancoc/+archive/ubuntu/gtsam-develop/+packages)! :+1:

**Comment by jlblancoc** [comment]
Confirmed: #306 closed via #607

**Comment by varunagrawal** [comment]
Yes!!! Awesome

**Comment by varunagrawal** [comment]
We can now experiment with embedded ARM platforms. 😁
