### ISSUE TITLE
AddPrior should be available in Wrappers

### ISSUE THREAD

**Issue by dellaert** [borglab/gtsam#322]
## Feature

Make AddPrior available in wrappers
## Motivation

It is very handy in C++, want it in python MATLAB as well!

## Pitch

Simpler code, copy/pasted code will comply

## Alternatives

Just use add.

## Additional context

See PR #280

**Comment by varunagrawal** [comment]
This is pretty easy and I can get it done in 15 minutes. Should I?

**Comment by dellaert** [comment]
Sure.
