### ISSUE TITLE
Install Error: undefined reference to boost::archive

### ISSUE THREAD

**Issue by why-freedom** [borglab/gtsam#327]
## Description

make install 

../gtsam/libgtsam.so.4.0.2: undefined reference to `boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::save(std::string const&)'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/VisualISAM2Example.dir/build.make:108: recipe for target 'examples/VisualISAM2Example' failed
make[2]: *** [examples/VisualISAM2Example] Error 1
CMakeFiles/Makefile2:21115: recipe for target 'examples/CMakeFiles/VisualISAM2Example.dir/all' failed
make[1]: *** [examples/CMakeFiles/VisualISAM2Example.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

## Steps to reproduce

1. 
2.

## Environment
Ubuntu16.04
gcc 5.4.0
boost 1.58
cmake 3.92
gtsam 4.0.2 & 4.0.0

**Comment by dellaert** [comment]
Sorry -this is most likely an issue with your setup, and this is not a support forum.
If you find out otherwise and are convinced you have uncovered a real issue, please re-open with an actionable description.
