### ISSUE TITLE
Travis - Set verbose makefile to OFF

### ISSUE THREAD

**Issue by varunagrawal** [borglab/gtsam#355]
## Feature

Currently Travis builds GTSAM with the flag `-DCMAKE_VERBOSE_MAKEFILE=ON` which leads to a lot of output from the compiler, slowing down build times.

If there is a compilation issue, `make` will report it as needed, making this flag somewhat useless.

As an alternative, we could set the flag to ON for the build stage but to OFF for all other stages.

## Motivation

This would potentially help speedup the CI since IO is always the bottleneck.

## Pitch

Set the default value of the `CMAKE_VERBOSE_MAKEFILE` flag to `OFF`.

**Comment by dellaert** [comment]
I agree with that

**Comment by ProfFan** [comment]
2nd
