### ISSUE TITLE
Resolve Pose3 pose graph optimization before 4.0.3

### ISSUE THREAD

**Issue by dellaert** [borglab/gtsam#412]
I believe we should resolve this, and change the defaults if the data supports this. So, I think we should give up on 4.1 for this week and instead concentrate on the combined 4.0.3 + PGO blog post+ default change, and release 4.0.3 that way.

**Comment by dellaert** [comment]
So, @ProfFan ? I guess we still need a PR that changes the default? Anything else?

**Comment by ProfFan** [comment]
I'll prepare a PR shortly.
