### ISSUE TITLE
references

### ISSUE THREAD

**Issue by xdtl** [borglab/gtsam#421]
## Feature

reference list

## Motivation

In the code I saw comments such as: refer to reference [2]. Can I have the reference list somewhere?

## Pitch

Add a link to the list of references.

Thanks!

**Comment by jlblancoc** [comment]
BTW: Doxygen supports citations from a .bibtex file. Could be done that way?

**Comment by acxz** [comment]
> In the code I saw comments such as: refer to reference [2]. Can I have the reference list somewhere? 

Can you explicitly link to where this occurs?

> BTW: Doxygen supports citations from a .bibtex file. Could be done that way?

o.O that's something neat I didn't know

**Comment by xdtl** [comment]
Thank you both for your replies!

I saw them in gtsam\gtsam\navigation\CombinedImuFactor.cpp, line 74-78. Now I actually see the reference list at the beginning of CombinedImuFactor.h. That's all I need. Thank you for the great work!

**Comment by acxz** [comment]
@xdtl Glad to see the reference was there! You can go ahead and close the issue if you got it figured out.
