### ISSUE TITLE
why gtsam4.0.2 crash my eigen and pcl and g2o ?

### ISSUE THREAD

**Issue by qpc001** [borglab/gtsam#446]

**Comment by varunagrawal** [comment]
Hi @qpc001. We're going to need more information than this.

Can you please follow the issue template and provide all the information?

**Comment by jlblancoc** [comment]
My trained neural network predicts that the missing information will point towards the need to:
- enable use system eigen in cmake
- disable build with -march=native, in cmake too.

;-)

**Comment by qpc001** [comment]
I got that ,the problem is :
 i add a line of  "/usr/local/lib " into the file `/etc/ld.so.conf` when I'm installing the g2o.
 and just remove this line , it solved.
