### ISSUE TITLE
The mechanism in the propagation of covariance.

### ISSUE THREAD

**Issue by Gaochao-hit** [borglab/gtsam#456]
Recently I run LIO_SAM which uses GTSAm for optimization. And find that  it's weird that the covariance of odometry flutuates which should increse constantly. And the author also don't know the reason for sure, so I asked the question. the link is here https://github.com/TixiaoShan/LIO-SAM/issues/49

**Comment by varunagrawal** [comment]
Why would the pose covariance be non-decreasing? If you provide sufficient constraints in your problem via measurements, then the covariance can go down since your certainty is going up.

Can you please provide a minimal working example? The code + data.

**Comment by varunagrawal** [comment]
Also, for faster answers, I recommend asking this question on the [GTSAM Google Group](https://groups.google.com/forum/#!forum/gtsam-users).

**Comment by jlblancoc** [comment]
As proved in [a seminar paper](https://www.semanticscholar.org/paper/A-solution-to-the-simultaneous-localization-and-map-Dissanayake-Newman/d7aa257db5f2cc40e486f677b4378b219727459e), the inferior limit in the covariance of the map is determined by the initial covariance of the pose... which in VIO is zero. Together with the fact that we have *inertial* global observations (acceleration), it *might* be correct to see the covariance of VIO to shrink over time. 
OTOH, it might be a bug in the marginalization of past variables... As @varunagrawal suggested, this is probably better a question for the mailing list.

**Comment by Gaochao-hit** [comment]
> As proved in [a seminar paper](https://www.semanticscholar.org/paper/A-solution-to-the-simultaneous-localization-and-map-Dissanayake-Newman/d7aa257db5f2cc40e486f677b4378b219727459e), the inferior limit in the covariance of the map is determined by the initial covariance of the pose... which in VIO is zero. Together with the fact that we have _inertial_ global observations (acceleration), it _might_ be correct to see the covariance of VIO to shrink over time.
> OTOH, it might be a bug in the marginalization of past variables... As @varunagrawal suggested, this is probably better a question for the mailing list.

I agree with you. But there seems only prior constraint and  sequencial constraints in the mapoptimization.cpp of [LIO_SAM,](https://github.com/TixiaoShan/LIO-SAM) and no other redundant constraints. I have asked the author of LIO-SAM to give you some feedback.
