### ISSUE TITLE
Support for super-fisheye camera (larger than 180 deg of FOV)

### ISSUE THREAD

**Issue by acloitre** [borglab/gtsam#461]
## Feature
Change the intrinsic coordinate representation of 3D direction vectors to support super-fisheye cameras that have field-of-views larger than 180 degrees.

## Motivation
GTSAM currently proposes a camera model capable of handling very large FOV in theory, but not in practice. The Unified model from Mei and Rives (2007) can handle such cameras thanks to its extra parameter, the mirror parameter. This allows to uncalibrate image points that are within the camera's field of view, yet lie behind the camera, or exactly at 90 degrees from its optical axis.

However, GTSAM models 3D direction vectors as normalized 2D points: X = [x, y, z] becomes X = [x/z, y/z, 1.0], with the 3rd coordinate being dropped. Because of this representation, a super-fisheye camera cannot be modelled in GTSAM, since a unit direction vector X = [1, 0, 0] would create a normalized 2D point at infinity.

## Pitch
We can keep a normalized 2D representation of a 3D direction vector, by encoding its projection on the camera-centered unit sphere, and by using spherical coordinates (latitude + longitude). Switching from Cartesian to Spherical coordinates for the representation of the intrinsic coordinates will not increase the dimensionality of the intrinsic coordinates and will make them general to any central camera.

A 3D direction vector X = [x, y, z] would not be normalized as X = [x/z, y/z, 1], but as X = [theta, phi, r = 1] with:

- theta = arccos(z / sqrt(x^2 + y^2 + z^2))
- phi = arctan2(y, x)

The 3rd coordinate of this representation, r, can also be dropped, as it would always be equal to 1.

## Alternatives
The alternative solution I have used so far, was to create 5 virtual perspective cameras for each of my super-fisheye cameras. These 5 virtual cameras are configured and arranged to exactly cover each side of a cube, except for the 6th face which is placed directly behind the actual camera. This allows to model super-fisheye cameras with FOV up to 270 degrees. Whenever I need to project or lift a feature, I would identify which virtual camera it belonged to, and project/lift the feature using this perspective camera model. 

This solution works in practice, but at the cost of a drastically bigger graph (5 virtual cameras per real camera), and at the cost of added complexity (search for the valid cube face for each feature, and map each measurement on the real image to a virtual measurement on a virtual camera image).

## Final thoughts
I am not sure of how big of an update it would be to make this change in the code. Please let me know if there is an obvious solution to this problem that I am not seeing. I appreciate the work you have put in with GTSAM, and I thank you for making this library open source.

**Comment by varunagrawal** [comment]
Hi @acloitre. Apologies for the late response. You'll be happy to know that we recently streamlined all the camera calibration models so that there is less duplication and clutter, so I imagine this feature wouldn't be too big of an issue. Can you please take a look at `Cal3_S2.h` and the related files and start a PR?

Since you already have the equations figured out, it should be straightforward and I am here to help review. :slightly_smiling_face:

**Comment by acloitre** [comment]
Hello @varunagrawal ,
Thank you for your reply.
Should I implement the change as two separate functions, e.g. `calibrateSpherical` and `uncalibrateSpherical`?
Or should I modify the existing `calibrate` and `uncalibrate` functions, as well as all the other functions in gtsam that use these functions' outputs?

**Comment by varunagrawal** [comment]
You could just create a subclass.

**Comment by varunagrawal** [comment]
Would it be possible to simply subclass Cal3Fisheye? That way you'd have very little to do.

**Comment by dellaert** [comment]
Actually, please note that there is already a normalized direction class, Unit3. And that several (if not all?) camera models *already* support a Unit3 measurement. I recommend reading the code to inform you of the shortest path here.

**Comment by varunagrawal** [comment]
@acloitre any updates on this?

**Comment by acloitre** [comment]
Hello @varunagrawal,
My application ended-up not needing a fisheye lens and I did not implement the change listed above. 
I expect this to change in the coming months, and in which case, I will update this post.
Best regards,
Audren

**Comment by varunagrawal** [comment]
Fair enough. I'll close this for now, please reopen if and when things change.

**Comment by acloitre** [comment]
Hello @varunagrawal,

I am back to implementing a fisheye lens on my application and restarting this issue as I think I got to the core of it.
Cameras in GTSAM are virtually all derived from the class `PinholeBase` defined in the file `CalibratedCamera.h` and implemented in the file `CalibratedCamera.cpp`.
This class has a function `Project` which projects a point to the normalized plane, at `z=1`.
Prof. @dellaert mentioned that a `Unit3` direction vector can be used in place of a 3D point, but both implementation of the `Project` function returns the normalized point `pn = [x/z, y/z]`, which is only defined for `z > 0`.

I will attempt to implement a `SphericalCameraBase` class that uses the spherical coordinate system described in my original post in order to maintain the dimensionality of the measurement to be 2, while allowing to project points at arbitrary locations with respect to the camera.

My question for you is the following: does the above make sense? Or am I still missing an important insight as to how GTSAM handles visual measurements?

Thank you for any help you can provide.

Audren
