### ISSUE TITLE
warnings: qualifier applied to function typ

### ISSUE THREAD

**Issue by dellaert** [borglab/gtsam#474]
## Description

New CI Action on windows produces warnings like:

`C:\hostedtoolcache\windows\boost\1.72.0\x86_64\include\boost/optional/detail/optional_reference_spec.hpp(101): warning C4180: qualifier applied to function type has no meaning; ignored (compiling source file D:\a\gtsam\gtsam\gtsam\nonlinear\Marginals.cpp) [D:\a\gtsam\gtsam\build\gtsam\gtsam.vcxproj]
`
## Steps to reproduce

see e.g. https://github.com/borglab/gtsam/pull/473/checks?check_run_id=991973569

## Expected behavior

no warning

## Environment

Windows CI

## Additional information

would be great if someone could fix this and also track down otehr warnings on windows.

**Comment by varunagrawal** [comment]
This is a boost warning displayed on the debug build. We can safely ignore it.
