### ISSUE TITLE
Remove Appveyor

### ISSUE THREAD

**Issue by varunagrawal** [borglab/gtsam#475]
## Feature

Now that we've moved to Github Actions with a CI for Windows, we need to remove the CI from Appveyor.

Instructions:
 https://help.appveyor.com/discussions/questions/1393-how-to-turn-off-appveyor-for-a-project

## Motivation

Github will keep reporting failure since the appveyor files were removed by #472.

## Pitch

Follow the instructions in the link above. Needs admin access aka @dellaert.

**Comment by ProfFan** [comment]
Just remove the app from Settings of the repo, very easy :) @dellaert

**Comment by varunagrawal** [comment]
That's literally what the link says :joy:

**Comment by jlblancoc** [comment]
Remember to also remove the badges from the README and add the new ones... perhaps that's already in another PR but couldn't see it, sorry if it's already WIP.

**Comment by varunagrawal** [comment]
Ah thanks for the reminder @jlblancoc. I just updated #476 to ensure the correct badges.

**Comment by dellaert** [comment]
Done
