### ISSUE TITLE
FindExampleDataFile in python wrapper does not work

### ISSUE THREAD

**Issue by dellaert** [borglab/gtsam#500]
## Description

Seems like the path used in gtsam::findExampleDataFile is the one from the python wheel build.

```
ValueError: gtsam::findExampleDataFile could not find a matching file in
/Users/runner/work/gtsam-manylinux-build/gtsam-manylinux-build/gtsam/examples/Data
```

## Steps to reproduce

```python
import gtsam
_ = gtsam.findExampleDataFile("toyExample.g2o")
```

## Expected behavior

Should look in directory where python wheel was installed

## Environment

MacOS, python 3.8

## Additional information

Could be hard to solve

**Comment by varunagrawal** [comment]
I'll take care of this. It's some simple setup.py foo.

**Comment by ProfFan** [comment]
Should probably be replaced by a Python version
