### ISSUE TITLE
Feature Request: Make uninstall option

### ISSUE THREAD

**Issue by dwisth** [borglab/gtsam#51]
Hello,

Just a feature request. It would be great to have a `make uninstall` option. I uninstall gtsam (e.g. to upgrade to a new version) by using ```rm `cat install_manifest.txt` ``` but an uninstall option would be helpful.

Thanks!
David

**Comment by jlblancoc** [comment]
Here you go: https://github.com/borglab/gtsam/pull/52
Please, give it a try and let us know if it works as expected (it should). 

Anyway: avoid doing "make install" as much as possible. CMake always allows you to use gtsam or any other project **without** installing it to any special path.

**Comment by dwisth** [comment]
Thanks for the quick response!

I just tested it on my computer and it works perfectly.

**Comment by jlblancoc** [comment]
Cool. Closing. 

(cc: @dellaert, @chrisbeall  )
