### ISSUE TITLE
How to distinguish between IMU factor and landmark factors

### ISSUE THREAD

**Issue by Joechencc** [borglab/gtsam#512]
New to GTSAM! I am currently working on ISAM2 Optimization and using landmarks and IMU to optimize the trajectory in real-time. I am using "initialEstimate.insert" to add the GPS location of the node. And **graph.emplace_shared<IMUFactor>** and **graph.emplace_shared<GenericProjectionFactor<Pose3, Point3, Cal3_S2> >**  are used to add IMU factor and 3D landmark pose(x,y,z, I might be wrong here, please advise the correct factor). 

1. I wonder in the GTSAM framework, how does the code distinguish IMU factor and landmark factor?? Is that by parameter in graph.emplace_shared<parameter>??

2. If factor is the key to distinguish the type of measurement, what factor should we use for 3D landmark(x,y,z can be obtained)

**Comment by dellaert** [comment]
1. Indeed.
2. I think maybe you should look for help locally and/or read Intro to GTSAM tech report first.
PS there is a Google group for questions like this (it is mentioned when you create an issue), but I encourage you to read more before asking there, as well.
Closing this as not an issue with GTSAm.
