### ISSUE TITLE
Is there an easy way to fuse  a few  'tiny' factors to a 'big' single factor?

### ISSUE THREAD

**Issue by solution3000** [borglab/gtsam#524]
Hi, 

In kitti example, I want to define my own type, just like:
 
struct NavStateWithBias
{
   Pose3 pose_;
   Velocity3 velocity_;
  imuBias::Constant bias_;
}；  

and try to combine {ImuFactor, PriorFactor{s}, BetweenFactor} to a single factor.
I can do this by defining a customized factor, but I  want to know whether there is an easy way to do that!

By defining a big type 'NavStateWithBias', I can get a well-structured Hessian which is a block-tridiagnol matrix with 15x15 blocks,  then can solve AtA*x=Atb by block Cholesky factorization!

**Comment by dellaert** [comment]
Absolutely. You need to use C++ traits to make your new type available to GTSAM optimization, though. Take a look at NavState.h on how to do this.

BTW, GTSAM already does sparse Cholesky so this might not give rise to the savings you want.

Closing as not an actual issue (consider using Google group for questions like this).
