### ISSUE TITLE
how can i uninstall gtsam?

### ISSUE THREAD

**Issue by w634307272** [borglab/gtsam#562]
I want to change the version of gtsam

**Comment by dwisth** [comment]
Navigate to your gtsam build folder and run `make uninstall`. This should hopefully remove it from your system.

**Comment by varunagrawal** [comment]
Generally having a `make uninstall` command is a bad idea, since due to different user configurations it is hard to specify what should be uninstalled.

The foolproof way is to go to your `build` directory and run `xargs rm -rf < install_manifest.txt`.

**Comment by varunagrawal** [comment]
Optionally, if you are building from source, just pull the latest changes and run the build and install process again. It will override the previous versions.
