### ISSUE TITLE
What is the difference between PreintegratedImuMeasurements and PreintegratedCombinedMeasurements 

### ISSUE THREAD

**Issue by rginjapan** [borglab/gtsam#573]
As the title, could u plz give some explanations?
CombinedImuFactor and ImuFactor as well, thanks!

**Comment by varunagrawal** [comment]
`PreintegratedImuMeasurements` only takes into account the position, velocity and rotation measurements (9 dimensional vector).
`PreintegratedCombinedMeasurements` takes into account the above, plus the bias values for the gyro and the accelerometer (9+6 dimensional vector).

For future reference, please ask conceptual questions on the GTSAM Google Group. :slightly_smiling_face:
