### ISSUE TITLE
Add GTSAM citation

### ISSUE THREAD

**Issue by varunagrawal** [borglab/gtsam#581]
## Feature

Generate a bibtex citation for use in academic publishing.

## Motivation

We use GTSAM for research, and Github repositories get cited all the time these days.

## Pitch

The process is really simple:

1. Link this repo with Zenodo (instructions [here](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/referencing-and-citing-content)). This will create DOIs for each new release. Only @dellaert can do this since it requires admin privileges.
2. Create a bibtex citation in the README as per [this tutorial](https://github.com/AASJournals/Tutorials/blob/master/Repositories/CitingRepositories.md).

## Alternatives

NA

## Additional context

NA

**Comment by dellaert** [comment]
Feel free to start a draft about GTSAM 4

**Comment by varunagrawal** [comment]
If you create the DOI, I can add the badge to the README as well as autogenerate the BibTex via a `curl` command.

**Comment by varunagrawal** [comment]
An attempt at humor in this repo. Seemed apt for this issue.

![what_prof_read](http://phdcomics.com/comics/archive/phd080709s.gif)

**Comment by dellaert** [comment]
You're gonna have to me walk through what needs to happen next time we meet

**Comment by varunagrawal** [comment]
@dellaert we can now finish this. We should do it in our next meeting.
