### ISSUE TITLE
Python nonlinearfactorgraph api save via graphviz

### ISSUE THREAD

**Issue by Harsharma2308** [borglab/gtsam#618]
## Feature
`graph = gtsam.NonlinearFactorGraph()`
`graph.save_graph(format='graphViz')`

## Motivation
Hi visualizing the graph is very important especially if optimization is done incrementally. GraphViz seems very useful for this purpose and I was wondering if python nonlinearfactorgraph could be saved in graphviz format.
## Pitch

For my usecase where I am working on tracking algorithm on a given image/lidar sequence(Kitti), I want to be able to do the following- 

1. Add factors to my graph 
2. Call isam.optimize() at each step when a factor is added.
3. At the end when the sequence finishes visualize the entire graph created.(Also in the middle for debugging purposes)

## Alternatives

**Comment by varunagrawal** [comment]
Thanks for the suggestion. Would you be able to create a PR for this?

**Comment by ProfFan** [comment]
I remember we have a `dot` output?

**Comment by dellaert** [comment]
@Harsharma2308 we actually already have this, right? Please confirm by checking out code that produces .dot file and re-open this issue if that is not what you meant :-)

**Comment by Harsharma2308** [comment]
Sorry could you explain the exact function call? `graph.saveGraph` in Python doesn't exist right now.

**Comment by varunagrawal** [comment]
It should be `isam2.saveGraph`.
