### ISSUE TITLE
Closest way to approximate a GPS factor with rotation?

### ISSUE THREAD

**Issue by Harsharma2308** [borglab/gtsam#631]
I have an oracle giving the measurement for the 6DOF pose of my robot.
I have been using GPS factor so far and only passing the translation component from this oracle in the factor graph.
How do I use gps factor in gtsam with rotation component as well?

**Comment by varunagrawal** [comment]
Hi @Harsharma2308. The [Google Group](https://groups.google.com/g/gtsam-users) might be a better and faster place to get support on this.

You may be interested in the AHRSFactor, which specifically deals with (preintegrated) rotations.
