### ISSUE TITLE
Use isam to add planefactor to prompt error

### ISSUE THREAD

**Issue by hunkyu** [borglab/gtsam#666]
## Description
Hello everyone, I am using planefactor and isam to report an error, but there is no problem using Gauss Newton? I think it’s weird, but I changed the optimizer, and it seems that the writing is problematic.

## Steps to reproduce

1. Add two P and X
2.ISAM optimization

#include <gtsam/slam/OrientedPlane3Factor.h>
#include <gtsam/slam/PriorFactor.h>
#include <gtsam/base/numericalDerivative.h>
#include <gtsam/inference/Symbol.h>
#include <gtsam/nonlinear/GaussNewtonOptimizer.h>
#include <gtsam/nonlinear/ISAM2.h>

#include <CppUnitLite/TestHarness.h>

#include <boost/assign/std/vector.hpp>
#include <boost/assign/std.hpp>
#include <boost/bind.hpp>

using namespace boost::assign;
using namespace gtsam;
using namespace std;

GTSAM_CONCEPT_TESTABLE_INST(OrientedPlane3)
GTSAM_CONCEPT_MANIFOLD_INST(OrientedPlane3)

/* ************************************************************************* */
int main() {
//  srand(time(nullptr));
//  TestResult tr;
//  return TestRegistry::runAllTests(tr);

    // Typedefs
    using symbol_shorthand::P;  //< Planes
    using symbol_shorthand::X;  //< Pose3 (x,y,z,r,p,y)
    using Plane = OrientedPlane3;

    NonlinearFactorGraph graph;

    // Setup prior factors
    Pose3 x0_prior(
        Rot3(0.799903913, -0.564527097, 0.203624376, 0.552537226, 0.82520195,
             0.117236322, -0.234214312, 0.0187322547, 0.972004505),
        Vector3{-91.7500013, -0.47569366, -2.2});
    auto x0_noise = noiseModel::Isotropic::Sigma(6, 0.01);
//    graph.addPrior<Pose3>(X(0), x0_prior, x0_noise);
//    graph.emplace_shared<PriorFactor<Pose3>>(X(0), x0_prior, x0_noise);

  //   Plane p1_prior(0.211098835, 0.214292752, 0.95368543, 26.4269514);
  //   auto p1_noise =
  //       noiseModel::Diagonal::Sigmas(Vector3{0.785398163, 0.785398163, 5});
  //   graph.addPrior<Plane>(P(1), p1_prior, p1_noise);

  // ADDING THIS PRIOR MAKES OPTIMIZATION FAIL
  //   Plane p2_prior(0.301901811, 0.151751467, 0.941183717, 33.4388229);
  //   auto p2_noise =
  //       noiseModel::Diagonal::Sigmas(Vector3{0.785398163, 0.785398163, 5});
  //   graph.addPrior<Plane>(P(2), p2_prior, p2_noise);

    // First plane factor
    Plane p1_meas = Plane(0.0638967294, 0.0755284627, 0.995094297, 2.55956073);
    const auto x0_p1_noise = noiseModel::Isotropic::Sigma(3, 0.0451801);
    graph.emplace_shared<OrientedPlane3Factor>(p1_meas.planeCoefficients(),
                                               x0_p1_noise, X(0), P(0));

    // Second plane factor
    Plane p2_meas = Plane(0.104902077, -0.0275756528, 0.994100165, 1.32765088);
    const auto x0_p2_noise = noiseModel::Isotropic::Sigma(3, 0.0322889);
    graph.emplace_shared<OrientedPlane3Factor>(p2_meas.planeCoefficients(),
                                               x0_p2_noise, X(0), P(1));

    // Optimize
//    try {
      // Initial values
      Values initialEstimate;
      Plane p1(0.211098835, 0.214292752, 0.95368543, 26.4269514);
      Plane p2(0.301901811, 0.151751467, 0.941183717, 33.4388229);
      Pose3 x0(
          Rot3(0.799903913, -0.564527097, 0.203624376, 0.552537226, 0.82520195,
               0.117236322, -0.234214312, 0.0187322547, 0.972004505),
          Vector3{-91.7500013, -0.47569366, -2.2});
      initialEstimate.insert(P(0), p1);
      initialEstimate.insert(P(1), p2);
      initialEstimate.insert(X(0), x0);

      gtsam::ISAM2Params params;
      params.relinearizeThreshold = 0.01;
      params.relinearizeSkip = 1;

      //        parameters.setFactorization("CHOLESKY");
      //        parameters.setRelinearizeSkip(10);

      gtsam::ISAM2DoglegParams dogleg_param;
      dogleg_param.setVerbose(false);
      params.setOptimizationParams(dogleg_param);

      ISAM2 isam(params);

//      Ordering ordering = list_of(P(0))(X(0));  // make sure P1 eliminated first
//      params.setOrdering(ordering);
//      params.setLinearSolverType("SEQUENTIAL_QR");  // abundance of caution
//      params.setVerbosity("TERMINATION");  // show info about stopping conditions

      isam.update(graph,initialEstimate);
      isam.update();
//      graph.resize(0);
      initialEstimate.clear();
      isam.calculateBestEstimate();

//      GaussNewtonParams params;
//      GTSAM_PRINT(graph);
//      Ordering ordering = list_of(P(0))(X(0));  // make sure P1 eliminated first
//      params.setOrdering(ordering);
//      params.setLinearSolverType("SEQUENTIAL_QR");  // abundance of caution
//      params.setVerbosity("TERMINATION");  // show info about stopping conditions
//      GaussNewtonOptimizer optimizer(graph, initialEstimate, params);
//      Values result = optimizer.optimize();
//      EXPECT_DOUBLES_EQUAL(0, graph.error(result), 0.1);
//    } catch (IndeterminantLinearSystemException e) {
//      std::cerr << "CAPTURED THE EXCEPTION: " << e.nearbyVariable() << std::endl;
//    }

}

## Expected behavior

terminate called after throwing an instance of 'gtsam::IndeterminantLinearSystemException'
  what():  
Indeterminant linear system detected while working near variable
8070450532247928832 (Symbol: p0).

Thrown when a linear system is ill-posed.  The most common cause for this
error is having underconstrained variables.  Mathematically, the system is
underdetermined.  See the GTSAM Doxygen documentation at
http://borg.cc.gatech.edu/ on gtsam::IndeterminantLinearSystemException for
more information.

## Environment

ubuntu 18.04 
gtsam 4.0.2

**Comment by Jontseh** [comment]
I encountered a similar problem. Have you solved it
