### ISSUE TITLE
Can isam perform accelerated processing?

### ISSUE THREAD

**Issue by hunkyu** [borglab/gtsam#667]
## Feature
Whether the Bayesian tree adjusts the node optimization position so that the optimization can be accelerated

## Motivation

I want to do a stress test to see the node size and the efficiency of isam optimization

## Pitch

When the number of factor nodes is greater than 5000, it contains three factors (betweent facotr gps factor prior factor), and isam update() takes 100ms. Is this normal?

## Alternatives

Whether the Bayesian tree adjusts the node optimization position so that the optimization can be accelerated

## Additional context
![1010337464](https://user-images.githubusercontent.com/20533364/104558122-472d8b80-567d-11eb-82ee-e2f118670e63.jpg)

**Comment by dellaert** [comment]
There are several mechanisms in iSAM that are governed by parameters. for `calculateEstimate` the wildfire threshold especially might matter to you. I suggest you read the paper thoroughly and examine what exactly makes this slow, and then come up with a concrete proposal if you think it is not yet implemented and will make a real difference.

**Comment by hunkyu** [comment]
@dellaert  The iSAM parameter I use is like this   :
gtsam::ISAM2Params parameters;
        parameters.relinearizeThreshold = 0.01;
        parameters.relinearizeSkip = 1;
        gtsam::ISAM2DoglegParams dogleg_param;
        dogleg_param.setVerbose(false);
        parameters.setOptimizationParams(dogleg_param);

**Comment by dellaert** [comment]
I suggest you read the paper thoroughly and examine what exactly makes this slow, and then come up with a concrete proposal if you think it is not yet implemented and will make a real difference.

**Comment by varunagrawal** [comment]
@hunkyu closing this for now. Please reopen if you'd like to explore this further.
