### ISSUE TITLE
Typo in docs LieGroups.pdf

### ISSUE THREAD

**Issue by melhashash** [borglab/gtsam#692]
In `LieGroups.pdf`, section 5.3, is the point `p` missing from the equation explained in the first scenario?

**Comment by mikesheffler** [comment]
I believe you're right; under heading `1.`, `p` should be to the right of  `R^T`, correct?

@dellaert

**Comment by melhashash** [comment]
yes, I think so. I have created a PR for the `LieGroups.lyx` file. https://github.com/borglab/gtsam/pull/693

**Comment by mikesheffler** [comment]
I'm not sure what the deal is with the corresponding .pdf (Do *you* make it? Does someone else?), so I didn't approve it yet. Let's let someone else chime in.
