### ISSUE TITLE
Pinhole camera factor for localization only

### ISSUE THREAD

**Issue by jlblancoc** [borglab/gtsam#697]
## Feature

Having a factor where the pose of the camera is the only variable, with fixed landmarks and calibration.

## Motivation

Vision-based localization / tracking / etc.

## Additional context

I have already written such a factor by modifying the existing `GenericProjectionFactor`... would it be useful to integrate it into GTSAM? If yes: any preference on its name?

**Comment by dellaert** [comment]
There is also one in unstable, and @lucacarlone is creating another one. We could probably benefit from coordinating :-)

**Comment by jlblancoc** [comment]
:+1:

In gtsam_unstable, I found `ProjectionFactorPPP` and `ProjectionFactorPPPC`, which estimate *more* variables (body-camera pose), but landmarks are still an unknown too. I'll let Luca to decide whether his proposal in #696 makes this one #697 unnecessary.
