### ISSUE TITLE
Boost on Github Actions

### ISSUE THREAD

**Issue by varunagrawal** [borglab/gtsam#717]
## Description

Boost is no longer supported by default on Github Actions images. The corresponding issue is https://github.com/actions/virtual-environments/issues/2667.

## Steps to reproduce

CI is currently broken and will be broken until we figure this out.

## Expected behavior

CI should have Boost installed in the environment.

**Comment by jlblancoc** [comment]
@varunagrawal I loved your "reaction" to the upstream issue :-)

**Comment by varunagrawal** [comment]
The reasoning they are providing seems very artificial. "Not enough usage"? Do they expect every single Actions build to use Boost?

**Comment by varunagrawal** [comment]
@dellaert FYI
