### ISSUE TITLE
How to get the matrix value of a noiseModel::Robust variable?

### ISSUE THREAD

**Issue by yeweihuang** [borglab/gtsam#759]
I want to get the covariance of BetweenFactor<Pose3> variables, which is a Cauchy noise model. I could print the covariance on the screen by print() function, but how to get the value as an Eigen matrix?

**Comment by varunagrawal** [comment]
You can call `->noise()` (assuming you are using the default shared_ptr) which will give you the underlying noise model. You can directly access the covariance matrix from the noise model.

If you have more questions, please ask them on the Google Group. You'll get a faster response there.

**Comment by yeweihuang** [comment]
Got it, thank you! Will try the Google group next time!
