### ISSUE TITLE
Pose3 derivative w.r.t. quaternion components

### ISSUE THREAD

**Issue by vovo-4K** [borglab/gtsam#76]
I'm trying to implement custom factor derived from _NoiseModelFactor1\<Pose3\>_
As I understood concepts in method evaluateError() I should provide Jacobian matrix for error function with respect to pose vector components i.e. _Rx, Ry, Rz, x, y, z_, where Rx, Ry and Rz are euler angles components of corresponding _Pose3_.
In my case I need to perform some operations with rotation, which is better to do with quaternions. Also it helps to avoid trigonometric functions like sin/cos in error function and much simplifies derivatives.

Is there any way to provide Jacobian with respect to _qw, qx, qy, qz_ of _Pose3_ with no breaking compatibility with current gtsam architecture and already implemented factors?

I've tried to set parameters USE_QUATERNIONS but it affects only internal representation of Rot3.

**Comment by dellaert** [comment]
Not an issue but a question. I propose you re-pose it on Google group: https://groups.google.com/forum/#!forum/gtsam-users

Short answer: the tangent space of quaternion and matrix representations is identical and is isomorphic to R^3. Please read PDFS in docs folder to get some help on this.
