### ISSUE TITLE
gtsam_unstable not exporting SmartStereoProjectionPoseFactor

### ISSUE THREAD

**Issue by bryanhpchiang** [borglab/gtsam#776]
I'm trying to run the [SmartStereoProjectionPoseFactor example](https://github.com/borglab/gtsam/blob/release/4.0.3/gtsam_unstable/examples/SmartStereoProjectionFactorExample.cpp) through the Python bindings, but it seems like the factor class itself is not exported from the header file:

https://github.com/borglab/gtsam/blob/release/4.0.3/gtsam_unstable/gtsam_unstable.h

Is there any way I can still access the class? Thanks!

**Comment by ProfFan** [comment]
Similar to #778
