### ISSUE TITLE
Can not find PythonConfig.cmake when cmake Matlab wrapper

### ISSUE THREAD

**Issue by luokerenxxz** [borglab/gtsam#787]
The installation without Matlab wrapper is fine. But I got a cmake warning, which means cmake in “warp” can not find python, when setting ‘-DGTSAM_INSTALL_MATLAB_TOOLBOX=ON -DGTSAM_PYTHON_VERSION=3.6’.  This leads to an error when compilling.

I am working on a clean Ubuntu 18.04 using VMWare virtual machine.

I tried to set 

'-DPYTHON_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")‘
’-DPYTHON_LIBRARY=$(python3 -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))") ‘
’-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3'

But it doesn't work.

Thanks！
 
![Screenshot from 2021-06-08 06-20-28](https://user-images.githubusercontent.com/38988146/121192751-d2fbba80-c89f-11eb-9152-33468275f51c.png)
![Screenshot from 2021-06-08 06-20-35](https://user-images.githubusercontent.com/38988146/121192785-dbec8c00-c89f-11eb-947d-35967af251fe.png)
![Screenshot from 2021-06-08 06-20-39](https://user-images.githubusercontent.com/38988146/121192794-de4ee600-c89f-11eb-8558-45c16c4551c2.png)

**Comment by ProfFan** [comment]
Did you follow the tutorials *exactly* and install the package `python3-dev`?

**Comment by luokerenxxz** [comment]
> Did you follow the tutorials _exactly_ and install the package `python3-dev`?

Yes, I followed the instructions in https://github.com/borglab/gtsam/blob/develop/matlab/README.md, and updated the wrap library. Also I tried `sudo apt-get install python3-dev`, it showed that python 3.6.9 has already been installed.

**Comment by ProfFan** [comment]
Maybe @varunagrawal has some idea on this? Also @luokerenxxz Please post your entire log in text here.

**Comment by ProfFan** [comment]
@luokerenxxz Do you still have this issue?

**Comment by varunagrawal** [comment]
Closing due to lack of a response. Please re-open if the issue persists.
