### ISSUE TITLE
SO3 dexp problem

### ISSUE THREAD

**Issue by alongqiyue** [borglab/gtsam#807]
Accoding to formula 7.37a in State Estimation for Robotics,  the left jacobian of SO3 is different with code implementation in gtsam?
dexp_ = I_3x3 - a * K + b * KK;(gtsam implementation)
dexp_ = I_3x3 + a * K + b * KK;(Derived from formula 7.37a)
which one is right?

**Comment by Edwinem** [comment]
So be aware that GTSAM uses the right jacobian. Not the left one.

So I am guessing both are correct.

**Comment by dellaert** [comment]
@alongqiyue see comment by @Edwinem ; if you find a formula for right-jacobian that is in conflict, feel free to re-open this issue.
