### ISSUE TITLE
PinholeCamera symbols not exported

### ISSUE THREAD

**Issue by sneik555** [borglab/gtsam#808]
## Description
I want to use PinholeCamera from gtsam, but I have linking error:

gtsam.lib(gtsam.dll) : error LNK2005: "public: __cdecl gtsam::PinholeCamera<class gtsam::Cal3_S2>::PinholeCamera<class gtsam::Cal3_S2>(class gtsam::Pose3 const &,class gtsam::Cal3_S2 const &)" (??0?$PinholeCamera@VCal3_S2@gtsam@@@gtsam@@QEAA@AEBVPose3@1@AEBVCal3_S2@1@@Z) already defined in my_lib.lib(File.obj) [path_to_unit_tests.vcxproj]

## Steps to reproduce

1. Build shared gtsam
2. Use PinholeCamera in your source
3. Build your code in shared configuration

## Expected behavior

Linking properly

## Environment

C++17, VS2017

## Additional information

I already fixed this issue. There are 2 ways to do it:
a) use SimpleCamera.h, but it is deprecated:
```
/**
 * @deprecated: SimpleCamera for backwards compatability with GTSAM 3.x
 * Use PinholeCameraCal3_S2 instead
 */
class GTSAM_EXPORT SimpleCamera : public PinholeCameraCal3_S2 {
```
b) option wich in my opinion should be added to gtsam - change PinholeCamera.h:
from:
`class PinholeCamera: public PinholeBaseK<Calibration> {`
to
`class GTSAM_EXPORT PinholeCamera: public PinholeBaseK<Calibration> {`

**Comment by varunagrawal** [comment]
Make a PR!! Your option b solution is the correct one, but we don't use Windows in the lab so don't really have ways to check this. The fix is simple, plus you can call yourself a GTSAM contributor. :slightly_smiling_face:
