### ISSUE TITLE
#800 causes Levenberg-Marquardt optimisation to crash

### ISSUE THREAD

**Issue by HMellor** [borglab/gtsam#809]
## Description

When updating to the latest commit of the `develop` branch my existing codebase that uses GTSAM started crashing when running LM. 

There is no stack-trace, only an error saying the process has died:
```
[ERROR] [fgo-1]: process has died [pid 8821, exit code -11,
    cmd '/home/user/ros_ws/install/fgo/lib/fgo/fgo--ros-args -r __node:=fgo
    --params-file /tmp/launch_params__dkrh3ic --params-file /tmp/launch_params_8v56gi4f
    --params-file /tmp/launch_params_btvjwucu'].
```

I have narrowed it down to 6ee17c2ed7b2a89f4a25ae568009bb9385061ad1 which comes from #800.  Checking out the previous commit causes the program to no longer crash.

It may help to list some classes I'm using:
* NonlinearFactorGraph
* CombinedImuFactor
* GPSFactor

## Expected behavior

Should not crash

## Environment

 * **OS**
    * Distributor ID: Ubuntu
    * Description:    Ubuntu 20.04.2 LTS
    * Release:        20.04
    * Codename:       focal
* **ROS**
    * Foxy
* **TBB Version (relevant to #800)**
    * libtbb-dev/focal,now 2020.1-2 amd64 [installed]
    * libtbb2/focal,now 2020.1-2 amd64 [installed,automatic]
* **Language**
    * C++

**Comment by ProfFan** [comment]
@acxz Could you take a look?

**Comment by ProfFan** [comment]
Also, @HMellor could you provide a minimal reproducer (one cpp file, no other dependencies)?

**Comment by dellaert** [comment]
@acxz this was your PR - could you weigh in? @HMellor thatnks for letting us know the TBB versions you used.

**Comment by acxz** [comment]
This might be an issue similar to why the testGncOptimize test failed once out of 100 runs. I could take a deeper look into this issue with a minimal reproducing example.

In the meanwhile, it may be better to just revert my PR.
