### ISSUE TITLE
[Deprecation] Properly mark deprecated functions in C++

### ISSUE THREAD

**Issue by ProfFan** [borglab/gtsam#889]
We should mark deprecated functions both in Doxygen and **in C++**.

For example,

In `EliminateableFactorGraph-inst.h` Line 39 it's calling deprecated function.

**Comment by dellaert** [comment]
I think this was incorrectly closed

**Comment by varunagrawal** [comment]
What is needed to close this? PR #925 added the macros for conditonal compilation.
