### ISSUE TITLE
Partial Optimization over a subset of keys

### ISSUE THREAD

**Issue by chihyuanchiu** [borglab/gtsam#911]
Is there a feature in the GTSAM code that allows for the factor graph to be optimized over a certain subset of keys, while keeping all other keys fixed? I.e., similar to marginalization, but instead of removing a certain subset of keys (and associated factors), we merely optimize over them while keeping other keys fixed.

Thanks.

**Comment by ProfFan** [comment]
Hi @chihyuanchiu, please use the mailing list for questions: https://groups.google.com/g/gtsam-users
