### ISSUE TITLE
Bearing range 3D factor in python

### ISSUE THREAD

**Issue by xieshuqin** [borglab/gtsam#912]
hi,

Thanks for the awesome work!

I wonder if the BearingRangeFactor for Pose3 and Point3 is also ported to Python? I install gtsam via pip and it doesn't have BearingRangeFactor3D.

**Comment by ProfFan** [comment]
Hi, if you want to export some function not available in Python, please edit the corresponding `.i` files and add the export yourself :)

**Comment by xieshuqin** [comment]
hi Frank,

Thanks for the reply. I have exported the function. I have one more question about the noise model used by BearingRange3D. I wonder what is the correct physical meaning for the 3 variables of BearingRange3D's noise model? Is it XYZ?

**Comment by dellaert** [comment]
> hi Frank,
> 
> Thanks for the reply. I have exported the function. I have one more question about the noise model used by BearingRange3D. I wonder what is the correct physical meaning for the 3 variables of BearingRange3D's noise model? Is it XYZ?

Will you create a PR? That would be awesome :-)

I’m not near a computer, but 3-D bearing is two dimensional, and range is one dimensional. So I think the first two are radians and the second is distance.You should look at the code to be sure.

**Comment by xieshuqin** [comment]
No problem, I will try to create a PR this weekend.

**Comment by dellaert** [comment]
Why don't you close when the PR lands. Can be done automatically by mentioning issue # in PR comment.

**Comment by ayushsharma-crypto** [comment]
Hello @xieshuqin  and @ProfFan, I'm also trying to use BearingRangeFactor3D in gtsam python wrapper. Could you please provide the link for the `.i` file that you were referring to?

**Comment by varunagrawal** [comment]
@ayushsharma-crypto please look in `sam.i`.
