### ISSUE TITLE
What is the gps and imu coorrdinate in ImuFactorsExample.cpp?

### ISSUE THREAD

**Issue by zhaoworking** [borglab/gtsam#924]
Recently ,I want to use the ImuFactorsExample.cpp to test my own data , but I am confused with the data coorrdinate in the file. Moreover, I do not find any transformation between IMU and GPS data. So , is that the IMU coordinate is as the same as GPS , thus called the Body coordinate. Otherwise, the raw data is aligned already before feed in algorithm?

**Comment by ProfFan** [comment]
This is a question rather than a issue, which I suggest you post in the GTSAM mailing list instead.

**Comment by zhaoworking** [comment]
> GTSAM mailing list i

Where  is the GTSAM mailing , do u mean Google group?

**Comment by ProfFan** [comment]
Yes, the Google group.
