### ISSUE TITLE
Add Deprecation Pragmas

### ISSUE THREAD

**Issue by varunagrawal** [borglab/gtsam#927]
## Feature

Add the following deprecation pragmas and use them so that GTSAM warns users during compilation of their projects.
Creating this issue so we can track this.

```
#if defined(__GNUC__) || defined(__clang__)
#define GTSAM_DEPRECATED __attribute__((deprecated))
#elif defined(_MSC_VER)
#define GTSAM_DEPRECATED __declspec(deprecated)
#else
#define GTSAM_DEPRECATED
#endif
```

## Motivation

Deprecation warnings!

**Comment by jlblancoc** [comment]
For the records: This one could be replaced by standard C++14 [deprecated attribute](https://en.cppreference.com/w/cpp/language/attributes/deprecated), if #937 ever got addressed.
