### ISSUE TITLE
[RFC] Retire Boost in light of Default C++17 Support in Ubuntu 18.04+

### ISSUE THREAD

**Issue by ProfFan** [borglab/gtsam#937]
# Pitch

There is no need to use boost anymore because C++17 is supported on all platforms we currently support.

GCC 8 is supported on Ubuntu 18.04, which includes C++17 support.
macOS and Windows also fully support C++17 now.

## Python distribution (PyPI)

The `manylinux2014` target we are currently using supports C++17 as well.

# Implementation

I have a branch (https://github.com/ProfFan/gtsam/pull/8) that I put together in my weekends, which uses cereal (https://uscilab.github.io/cereal/index.html) for serialization and ripped almost all boost components except:

- [ ] `ptr_map` (see also #935 #936)
  - it can be replaced by a structure wrapping `std::map<Key, Value*>`
- [ ] some leftovers in `discrete`
- [ ] `boost::optional<Value&>` which really should be replaced with a simple pointer `Value*`

**All unit tests pass locally** including the serialization tests. CI infra has to be updated to deal with this

Anyone interested in this should clone the fork above and try integrating with their projects and report the results.

# How to proceed

I propose this be executed in the GTSAM `develop` branch after our 4.1 release, and `develop` will become GTSAM 5.

# RFC

This thread is for open discussion on the direction we should move on.

**Comment by asa** [comment]
Amazing! Yes!

**Comment by varunagrawal** [comment]
We can use `std::optional` rather than pointers. Make the code safer.

**Comment by ProfFan** [comment]
The issue is optionals should never take references. In C++17 this is explicitly disallowed.

**Comment by jlblancoc** [comment]
Awesome move, I would love to see C++17 finally here, Yay!

On optional references, they can be used, indeed: check this and search in
the project for some uses for syntax examples and such:

https://github.com/MRPT/mrpt/blob/develop/libs/core/include/mrpt/core/optional_ref.h

Feel free of copying that type definition and play with it as a direct
replacement of boost's optional.

**Comment by dellaert** [comment]
This is very cool. Probably should leave this until after the journal submission deadline :-) two questions:
– you say all platforms, but is C++ 17 supported on all popular embedded platforms?
– We should definitely do a 4.1 release before switching.

**Comment by ProfFan** [comment]
> This is very cool. Probably should leave this until after the journal submission deadline :-) two questions:
> – you say all platforms, but is C++ 17 supported on all popular embedded platforms?

Yes

> – We should definitely do a 4.1 release before switching.

And yes. Since quals is done I'll start the release.

**Comment by varunagrawal** [comment]
We could replace `boost::optional` with `std::optional`. That should make porting far easier than switching to pointers.

**Comment by ProfFan** [comment]
std::optional + std::reference_wrapper has some issues - I tried but it broke something that I have not identified. Since I am free of quals now I can start investigating. @varunagrawal do you want to pair program on this?

**Comment by dellaert** [comment]
I have been thinking about this. While there can be some (mild) API changes in 4.2, 4.3..., I see removing boost and moving to c++17 is more of "5.0" move. Also, in terms of reviewing this and assessing consequences on correctness, performance, it would have to be executed in a series of small, targeted PRs that tackle different issues, and are easy to review. Happy to chat more in person on creating a time line/roadmap for this.

**Comment by varunagrawal** [comment]
@ProfFan I am closing this since it is superseded by #1414 and we've already moved to C++17. But this was an awesome RFC 😄
