### ISSUE TITLE
derivate in Point3::normalize()

### ISSUE THREAD

**Issue by TobiasLangner-TomTom** [borglab/gtsam#952]
https://github.com/borglab/gtsam/blob/c7781961e66b79cfe17e4084b2ea15b94a2d2a95/gtsam/geometry/Point3.cpp#L58

Shouldn't this line be : 
*H /= pow(x2 + y2 + z2, **0.5**);

https://math.stackexchange.com/a/2161888

**Comment by varunagrawal** [comment]
Nope, 1.5 is correct. I guess you're missing that s = v / λ so the extra λ terms come into the denominator in the final expression.

I recommend deriving this yourself on pen and paper and you'll see for yourself. If you still think this is wrong, we would really appreciate a unit test demonstrating it is incorrect. I believe we already have a unit test for checking the correctness of this Jacobian. :slightly_smiling_face:

**Comment by TobiasLangner-TomTom** [comment]
My bad. The derivation I have linked defines H in terms of the normalized point, while the GTSAM implementation uses the unnormalized point.

**Comment by varunagrawal** [comment]
No worries. This is non-trivial stuff.
